statelyai/xstate

README.md
=> Update YouTube link to README.md

README.md
ported your video goat example from your react rally talk using the github api
=> Updated Readme.md with a simple react example

.prettierrc, package.json, src/State.ts, src/constants.ts, src/graph.ts, src/index.ts, src/mapState.ts, src/matchesState.ts, src/types.ts, src/utils.ts, test/examples/6.16.ts, test/examples/6.17.ts, test/examples/6.8.ts, test/examples/6.9.ts, test/examples/cd.ts, yarn.lock
There was a failure while running tests before I made any changes. I'm not quite sure what to do about it. 
Here is the message: 
``` bash
TSError: ⨯ Unable to compile TypeScript
test/graph.ts (177,9): Object is possibly 'undefined'. (2532)
```
Fixes #18
=> Include Prettier configs and run with tests

docs/api/config.md, docs/api/state.md
Tiny fixes for broken links in the docs.
=> Fix 404 errors in the docs

src/State.ts, src/actions.ts, src/constants.ts, src/index.ts, src/types.ts, test/actionCreators.test.ts, test/activities.test.ts
This PR adds support for activities.
Main file to look at is `activities.test.ts` to ensure that the behavior is correct. cc. @mogsie
=> Activities

docs/guides/complete.md
replace log action with logResult
=> fix typo in complex star wars example

.gitignore, examples/guards/index.html
This adds a new interactive example of how to use guards to conditionally transition between states.
I wanted to create this to get a handle on how conditional transitions work, and explore how to handle using a single action to conditional transition to different states, based on this discussion I started here: https://github.com/davidkpiano/xstate/issues/88#issuecomment-380801734
Now that I understand how this works I'll follow up with another PR to updates the docs for guards.
=> Add example of how to use guards

test/transient.test.ts
The machine has orthogonal regions A, B, C.
A and B react to the event E by transitioning, and when this happens,
they raise two separate events, INT1 and INT2.
State C is sitting waiting on INT1 and INT2, and handles them by
trying to get to state C4, indicating that both INT1 and INT2 were
indeed attempted (in any order).
The test fails with
AssertionError: expected
{ A: 'A2', B: 'B2', C: 'C2' } to deeply equal
{ A: 'A2', B: 'B2', C: 'C4' }
It sits in C2 instead of C4.
=> Failing test that exposes #106

test/activities.test.ts
This was based on observed behaviour, so keeping the test just the
same.
They pass, the problem is elsewhere.
Opening anothe PR for the Actual problem, but thought it would be OK to leave these test in place.
=> Added test to verify parallel activities.

test/transient.test.ts
When a state transitions to some state X, and X has no more automatic
transitions, other states that are guarded with 'in X' for some reason
don't seem to go forward to their intended states.
This test exposes that bug.
=> Exposed a bug with guarded transitions

test/parallel.test.ts
Added a test to show different behavior from 3.2.1 (test passing) to 3.3.0 (test failing).
=> Added a test for parallel state machine breaking on 3.3.0

test/invalid.test.ts
The four tests are failing in master
=> Expose #108 by way of four pending tests

test/history.test.ts
I've added a really simple test which fails right now.  
Unfortunately, I haven't done the work to determine how to fix it as I haven't quite gotten familiar w/ the code yet 😬.  Hopefully this helps.
=> History is deleted on transition through a transient state

test/history.test.ts
Added tests for both machines in issue #133, from me and @dannsam.
=> Add more history tests for #133

test/parallel.test.ts
Add failing test for issue #140.
=> #140 - Add failing parallel state test with event raising

test/parallel.test.ts
Add failing test for issue #144.
=> Add failing test for issue #144.

docs/api/actions.md
I also was confused by the documentation/behvior on action-functions as in #150 - this adds a small note to aid future readers.
=> Add note on action functions

docs/guides/internal.md
=> Fix internal transition guide example

docs/api/machine.md
I noticed this was missing from the docs.
=> readme: add docs for Machine#handles

src/StateNode.ts
=> Fix getStateNodeByPath method argument mutation

docs/.vuepress/config.js, docs/examples/todomvc.md, docs/sandboxes/todomvc/.editorconfig, docs/sandboxes/todomvc/.gitattributes, docs/sandboxes/todomvc/.gitignore, docs/sandboxes/todomvc/Todo.jsx, docs/sandboxes/todomvc/Todos.jsx, docs/sandboxes/todomvc/index.html, docs/sandboxes/todomvc/index.js, docs/sandboxes/todomvc/package.json, docs/sandboxes/todomvc/readme.md, docs/sandboxes/todomvc/todoMachine.js, docs/sandboxes/todomvc/todosMachine.js, docs/sandboxes/todomvc/useHashChange.js, docs/sandboxes/todomvc/useMachine.js, package-lock.json, package.json
Using this integration all the examples can be easily maintained in this repo. Also, the repo is the single source of truth and there is less risk of accidentally broken examples.
So, for adding more examples we should:
- Add a folder with the sandbox to `docs/sandboxes`.
- Add it to the documentation using this syntax: `@[codesandbox](example-name)`.
- Make a PR.
=> Add Codesandbox integration to docs

src/StateNode.ts, test/history.test.ts, test/machine.test.ts
=> Stop retaining vast amounts of history

docs/recipes/rxjs.md
Copy-pasted you Rxjs recipe to play with noticed this little error.
=> Correct recipe example for Rxjs

docs/guides/internal.md
https://github.com/davidkpiano/xstate/pull/344
=> Revert previous change: add "child states" back.

docs/guides/communication.md
"The actor model in 10 minutes" is a friendly resource to explain the actor model.
=> Invoking Services Guide: replace actor model explanation link

packages/xstate-react/package-lock.json, packages/xstate-react/package.json
=> xstate is now a peerDep of @xstate/react

src/interpreter.ts
Seems to me that this is more correct - at least in other systems. If you believe this change is wrong then feel free to close it, but I believe that **at least** next/complete/handleError shouldn't be called after subscriber unsubscribe itself - either based on newly introduced  `unsubscribed` flag or based on existing `canceled` (if you decide that subscribers should be able to stop the whole service).
If you agree with this one, I'm going to write tests & look into other service types to cover this in the same manner.
The interesting question is if subscribers should be notified after service has been stopped?
=> Fix logic around actors subscriptions

packages/xstate-react/src/index.ts
Related to https://github.com/davidkpiano/xstate/commit/4f2701c566d4492e3e639cef1012021835c756cd#r33762426
=> useService: explain the additional state update that might look unnecessary

package.json, packages/xstate-fsm/package.json, packages/xstate-graph/package.json, packages/xstate-immer/package.json, packages/xstate-react/package.json, packages/xstate-scxml/package.json
=> Add "sideEffects": false declaration to package.json files

src/StateNode.ts, src/interpreter.ts, src/utils.ts
More to come in the future, those were just the easiest ones to fix - others need more codebase exploration on my side.
=> Make few internal things compatible with TS strict setting

packages/xstate-react/src/index.ts, packages/xstate-react/test/useMachine.test.tsx
Compilation will fail due to `UseMachineOptions` warning.
As I don't know TS, I'll need help to fix it.
cc @davidkpiano @Andarist
=> @xstate/react: add context option for convenience

.gitignore, .vscode/settings.json, package-lock.json, package.json, packages/xstate-graph/package-lock.json, packages/xstate-graph/package.json, packages/xstate-react/package-lock.json, packages/xstate-react/package.json, packages/xstate-scxml/package-lock.json, packages/xstate-scxml/package.json, src/StateNode.ts, src/interpreter.ts, src/types.ts, test/machine.test.ts, test/state.test.ts, test/stateNode.test.ts
This PR is not ideal - I had to force cast a few things to make it work, technically it doesn't regress anything though, because those places were already broken (TS-wise). At the same time I've managed to fix some minor issues.
=> Upgrade to TS@3.5

src/StateTree.ts, test/actions.test.ts
fixes #507 
Reasoning - https://github.com/davidkpiano/xstate/issues/507#issuecomment-511187495
=> Fixed exitting a state on a parent's targetless transition

docs/guides/communication.md
…`data` being machine-specific.
=> Tweak `invoke` object description with information about `data` being machine-specific.

docs/guides/communication.md
Hi, I found this broken link and tried to replace with what looks like should be the correct link
=> docs: fix link to send actions

src/StateNode.ts, test/eventDescriptors.test.ts
=> Support wildcard event descriptor

docs/guides/transitions.md
=> Fix multiple targets example in the docs

src/StateNode.ts, src/types.ts, test/guards.test.ts, test/parallel.test.ts
=> Add dev-only warning for misconfigured transitions (when non-last possible transition is unguarded)

src/interpreter.ts, test/invoke.test.ts
=> Forward events before processing

jest.config.js, package-lock.json, package.json
This provides a nice enhancement to watch mode test filtering - https://github.com/jest-community/jest-watch-typeahead
=> Add jest-watch-typeahead

src/StateNode.ts, test/final.test.ts
fixes #517
⚠️ this PR has one failing test, I haven't "fixed" it or change it because I'd like to discuss it first.
In this PR I make changes to the `getDoneEvents` algorithm which I believe fixes few things (according to the SCXML spec). The previous version was traversing the whole tree looking for freshly done states (based on states which we enter) - and it was generating done events for each such state, which means:
- it was generating it for leaf final nodes (it's always "done" after all)
- it was generating it for the top level node (machine) itself
- it was all done in one pass, so when we entered a really nested final node synchronously we had ended up with many done events generates
Looking at the spec - [`<final>`](https://www.w3.org/TR/scxml/#final) and  [enterStates …
=> Invoke data expressions on nested final nodes

docs/guides/guards.md
=> Fix initial context in example doorMachine in the docs

docs/packages/xstate-react/index.md
=> Fix typo in xstate-react docs

test/interpreter.test.ts
The previous version of this test has managed to fail on my machine during development, because it was time-based and `.unsubscribe` call scheduled in setTimeout has been called too late to pass the assertion.
=> Rewrite interpreter's test - 'should be unsubscribable' - as it was flaky

.github/workflows/nodejs.yml
Should lead to more granular outputs. Especially helpful in case if one of those steps fails
=> Split install, build, test action into separate steps

packages/xstate-react/test/types.test.tsx, src/interpreter.ts, test/actor.test.ts
=> Make spawn return Interpreter if called with a machine

src/interpreter.ts
I'm not sure how to write a test for this which would use just public APIs as there is no example in tests and docs showcasing how `actor.subscribe` should be used. Should the actor ref just be grabbed from the context?
=> Fixed callback actors subscribers being subscribed to events forwarded to that actor instead of events emitted by that actor

packages/core/src/StateNode.ts, packages/core/src/interpreter.ts
=> Avoid recreating States in .transition when possible

docs/guides/installation.md
unpkg CDN dist link in docs is broken, added extra slash to fix it
=> docs(core): Fix broken unpkg CDN dist link

packages/xstate-test/package.json, packages/xstate-test/src/index.ts, packages/xstate-test/src/slimChalk.browser.ts, packages/xstate-test/src/slimChalk.ts
fixes https://github.com/davidkpiano/xstate/issues/725 , still need to test this manually with webpack, but in general I've been using this technique with success in the past
=> Make @xstate/test browser-compatible leveraging package.json#browser

packages/core/src/interpreter.ts
=> Remove warning about reading an initialState of a service (it's pure so it's safe)

docs/tutorials/reddit.md
- make `useMemo` return the machine
- make `useMemo` depend on `name`
- change `data-machine` to get id from `subredditMachine`
=> docs: make `useMemo` work in reddit tutorial

docs/guides/actors.md
Reverts davidkpiano/xstate#746
=> Revert "docs : fix example in actors.md"

packages/core/src/index.ts
=> Expose Actor

packages/xstate-react/src/index.ts
=> fix(@xstate/react) keep services up to date

docs/about/showcase.md
Add protocol prefixes to these links.
They're being interpreted as relative links right now 👋
=> Fix Kong showcase links

packages/core/src/interpreter.ts
=> Wrap reading service's initialState in service scope

docs/.vuepress/theme/WORKAROUND.md, docs/.vuepress/theme/components/AlgoliaSearchBox.vue, docs/.vuepress/theme/index.js
See `docs/.vuepress/theme/WORKAROUND.md` for workaround details
Fixes #744
=> Use workaround to fix #744 -- documentation search

packages/core/src/index.ts, packages/core/test/actions.test.ts
* exports the `forwardTo` action in `index.ts`
* updates `actions.test.ts` to import `forwardTo` from `src/index` to verify this change
=> fix(core): export forwardTo action in index.ts

packages/core/src/interpreter.ts, packages/core/src/utils.ts, packages/core/test/interpreter.test.ts
=> fix(rx_compat): Fix compatibility with RxJS interop Symbol.observable

.changeset/dry-bears-appear.md, .changeset/slimy-spoons-marry.md, packages/core/src/interpreter.ts, packages/core/test/actor.test.ts, packages/core/test/invoke.test.ts
=> Fix batching behaviors - forwarding before processing & make it possible to spawn actors when processing a batch

docs/guides/context.md
Seems to be an unnecessary character?
=> docs: Update context.md

packages/xstate-react/src/index.ts
Was it needed? It doesn't play "nicely" with SSR - React warns about using this hook on the server-side.
Fixes #894
=> Revert using useLayoutEffect in @xstate/react

.changeset/flat-avocados-beam.md, packages/xstate-fsm/src/index.ts, packages/xstate-react/src/fsm.ts, packages/xstate-react/test/useMachine-fsm.test.tsx, packages/xstate-react/test/useService-fsm.test.tsx
=> Implement useService for @xstate/fsm

docs/tutorials/reddit.md
Seems the order is wrong here?
=> docs: update reddit.md

packages/xstate-vue/src/xstate-machine.ts
To follow up on the 
https://github.com/davidkpiano/xstate/pull/864 
https://github.com/davidkpiano/xstate/pull/874
Here is a clean PR with removed watchers
=> Vue Package xstate-machine renderless component

.changeset/big-jeans-wait.md, packages/xstate-fsm/src/index.ts, packages/xstate-fsm/src/types.ts, packages/xstate-fsm/test/fsm.test.ts
=> fix(@xstate/fsm): Execute initial actions

.changeset/mighty-coats-beam.md, packages/xstate-fsm/README.md, packages/xstate-fsm/src/index.ts, packages/xstate-fsm/src/types.ts, packages/xstate-fsm/test/fsm.test.ts, packages/xstate-react/README.md, packages/xstate-react/src/fsm.ts, packages/xstate-react/test/useMachine-fsm.test.tsx, packages/xstate-vue/src/fsm.ts
=> Allow @xstate/fsm to accept actions bag

.changeset/nice-cobras-suffer.md, packages/core/src/interpreter.ts, packages/core/src/registry.ts
=> Fixed memory leak in internal actor registry

packages/xstate-react/README.md, packages/xstate-react/src/fsm.ts, packages/xstate-react/src/index.ts, packages/xstate-vue/README.md, packages/xstate-vue/package.json, packages/xstate-vue/src/fsm.ts, packages/xstate-vue/src/index.ts, packages/xstate-vue/test/UseFSM.vue, packages/xstate-vue/test/UseMachine.vue, packages/xstate-vue/test/UseService.vue
=> Align implementation of @xstate/vue more closely to what is being implemented for @xstate/react

packages/xstate-viz/example/package.json, packages/xstate-viz/src/index.tsx
This still doesnt really build correctly (there are runtime errors), but at least parcel can actually build this example now.
=> Small cleanup of build-related stuff in xstate-viz

packages/core/test/history.test.ts
My reasoning [here](https://github.com/davidkpiano/xstate/pull/987#discussion_r377970348) was almost correct, **but** I've missed the fact that the parent (`second`) of the history state was actually never exited thus the exited configuration (`second.other`) was never actually supposed to be saved in the `historyValue`.
This is somewhat a weird case - because we are already in the supposedly saveable part of the state and we are able to target the default state configuration by targeting the history state, even though we were already in that subtree (so one could think that we should already enter stored state configuration and not the default one).
I believe though that the reasoning here is OK - this is how SCXML algos deal with this situation.
=> Introduce a correct test for an internal transition targeting history state

docs/guides/communication.md
This is a miner patch I found it while reading the documentation. You can try it on the visualizer:)
=> Fix error inside of code blocks in doc

.changeset/violet-trainers-shop.md, packages/core/src/SimulatedClock.ts, packages/core/src/index.ts, packages/core/src/interpreter.ts, packages/core/src/invoke.ts, packages/core/src/types.ts, packages/core/test/interpreter.test.ts, packages/core/test/scxml.test.ts, packages/xstate-scxml/test/scxml.test.ts
Reverts davidkpiano/xstate#1037
=> Revert "Remove clock option"

packages/xstate-react/src/fsm.ts
=> Infer Typestate in useMachine based on passed-in machine

docs/guides/communication.md
=> docs - get respond from actions

.changeset/large-bats-explode.md, packages/core/src/interpreter.ts
related to https://github.com/davidkpiano/xstate/issues/996
cc @semopz
=> Cleanup internal structures upon receiving termination events from spawned actors

docs/.vuepress/config.js, docs/recipes/ember.md, docs/recipes/vue.md
* [Rendered](https://github.com/davidkpiano/xstate/blob/b70ee370d8289cc6042669cec0a79cd1495be1f3/docs/recipes/ember.md)
* [Demo](https://canary.ember-twiddle.com/e0e44d73f7f48ba232daec9c70ee20b4)
=> Add Ember.js recipe to docs

docs/packages/xstate-react/index.md
=> [Docs] Correct variable name in xstate-react example

docs/examples/todomvc.md
Codepen sandbox seems to be broken.
I've replaced the sandbox
=> fix: xstate todomvc vue demo

packages/core/test/actions.test.ts
=> Add test for accessing stateGuard.state in a conditional expression of the choose action creator

docs/guides/guards.md
=> Fix metaGuard state mistake in docs

docs/guides/actors.md
Closes #1151.
Let me know if I should add a more elaborate example, or if it's enough to document in the [quick reference](https://xstate.js.org/docs/guides/actors.html#quick-reference).
=> [Docs] Add quick reference example of send expression for send and sendParent

docs/guides/transitions.md
=> Remove full path ID target from internal transitions docs

.changeset/wicked-ducks-mate.md, docs/guides/final.md, packages/core/src/StateNode.ts
=> Add warning + docs for .onDone in root nodes.

docs/packages/xstate-test/index.md
The article has helped me so much to understand the concept behind `@xstate/test`.
=> Add link to model-based testing article

packages/core/test/actions.test.ts
No bug report, just more tests.
=> Add tests to validate choose actions work with the config option

packages/xstate-fsm/src/index.ts
I think this error message can be useful, I lost ~30 minutes trying to figure out why my SM can't did a transition.
What do you think about?
=> add: Error message when a nested state is set

docs/recipes/svelte.md
Please criticize! 
I want to make sure it makes sense and is also valid. 
(It works with this simple example on my machine.. I'll be incorporating this into a bigger project soon.)
=> Svelte usage recipe

docs/guides/communication.md
👋 
Re: https://github.com/davidkpiano/xstate/issues/988#issuecomment-583855715
Just wanted to make this a bit more obvious, even though it can be inferred.
=> Add note about using `async` with callback service

README.md, docs/README.md, docs/about/concepts.md, docs/about/goals.md, docs/guides/faqs.md, docs/guides/machines.md, docs/packages/core/index.md, packages/core/README.md
Link to a copy of the David Harel paper with a complete version of Fig. 31. In the current link, Fig. 31. is chopped off and only a 1/3rd of it is visible.
=> Link to David Harel Paper Fix

ISSUE_TEMPLATE.md
* Make it easier, and more likely, that people will confirm if the new feature idea is already on the roadmap.
Possibly add the roadmap to the README, too?
=> Update ISSUE_TEMPLATE.md with the Roadmap

packages/xstate-test/README.md
=> Fix inconsistent options documentation

docs/recipes/ember.md
Very sorry for this @davidkpiano but there was a small typo in the update for the ember docs. :/
=> Fix typo Ember.js recipe

docs/guides/states.md
=> Update documenation for restoring machine state

packages/xstate-react/README.md
This is just a minor fix to the react documentation.
=> Replace useService with useActor under Migration

README.md
Just found another one to update.
=> fix code in readme example

docs/guides/transitions.md, docs/packages/xstate-react/index.md, docs/packages/xstate-test/index.md
=> [docs] Add "always" to eventless header

docs/guides/communication.md
Run `yarn docs:dev` and open `http://0.0.0.0:8080/docs/guides/communication.html#the-invoke-property` will show a blank page:
=> add missing end tag

README.md, packages/xstate-inspect/jest.config.js, packages/xstate-inspect/package.json, packages/xstate-inspect/src/index.ts, packages/xstate-inspect/src/server.ts, packages/xstate-inspect/tsconfig.json
This PR adds `@xstate/inspect` to `master` (previously on the `viz` branch).
=> Add @xstate/inspect

package.json, packages/xstate-inspect/package.json, packages/xstate-inspect/rollup.config.js, packages/xstate-inspect/tsconfig.json, yarn.lock
This should fix https://github.com/davidkpiano/xstate/issues/1583
=> Fixed @xstate/inspect build issues

.changeset/thin-papayas-wait.md
This should trigger it to be automatically released. Addresses #1583
=> [@xstate/inspect] Add changeset

docs/about/concepts.md
Fixed a typo from the concepts documentation.
=> Fixed typo from concepts docs

docs/guides/transitions.md
=> Fix anchor link for eventless-always-transitions

.changeset/late-sloths-collect.md, package.json, packages/xstate-react/package.json, yarn.lock
fixes https://github.com/davidkpiano/xstate/issues/1635
=> Allow React 17 in the specified peer dependency range of `@xstate/react`

.changeset/sour-carrots-drum.md, packages/core/src/interpreter.ts, packages/core/test/actions.test.ts
fixes https://github.com/davidkpiano/xstate/issues/1653
=> Call exit handlers when service gets stopped

.changeset/purple-taxis-burn.md, packages/xstate-fsm/src/index.ts, packages/xstate-fsm/test/fsm.test.ts
=> Fixed an issue with initial `assign` actions not being resolved

docs/recipes/svelte.md
Add import statement: import replace from "@rollup/plugin-replace"; to documentation
=> Update description in svelte.md

.changeset/short-poets-sort.md, packages/core/src/interpreter.ts, packages/core/test/event.test.ts
fixes the issue reported here: https://github.com/davidkpiano/xstate/discussions/1730
=> Fixed an issue with events received from callback actors not having the appropriate `_event.origin` set

packages/xstate-svelte/README.md
I've created a readme for `@xstate/svelte` based on the other integrations. Just a note also to say that there isn't a rollup build step yet so that will need to be added before it can be shipped.
=> Svelte readme

docs/about/resources.md
Github - XState with React and Angular in Nx Workspace
=> docs: add new resource

docs/packages/xstate-react/index.md
=> docs: use correct link

docs/packages/xstate-vue/index.md
First of all, thank you for this great library.
I saw there were some pieces missing in the Vue section. I'm submitting one possible implementation of the Machines configuration section, following the same example seen in the react package: https://xstate.js.org/docs/packages/xstate-react/#configuring-machines
I've used Vue 3 syntax (also available as a [standalone plugin](https://github.com/vuejs/composition-api) for Vue 2).
=> Proposed "Configuring Machines" in @xstate/vue

packages/core/test/invoke.test.ts
When working on https://github.com/davidkpiano/xstate/pull/1986 I had a feeling that this might not work - I was wrong, it works 😜
Some calls to `createActorRefFromInvokeAction` are wasteful - the first one would indeed result in this bug but the outcome of the first one is pretty much discarded and when the second one kicks in it already operates on all actions from a macrostep and thus it works. From what I recall I've improved the situation around those wasteful calls in https://github.com/davidkpiano/xstate/pull/1986 so hopefully, this won't be when it lands.
It seems like a nice test nevertheless, so I've wrapped this into a proper PR.
=> Add a test for stopping invoked actors when multiple subsequent microsteps are involved

packages/xstate-react/test/useMachine.test.tsx
=> Add failing tests for @xstate/react surprising behaviors

docs/about/resources.md
Hi,
This PR fixes the indentation in resources.md of the link to [CodeSandbox - XState Login & Sign Up Forms](https://codesandbox.io/s/xstate-login-sign-up-forms-yzzoc) (thank you for having included this) and moves it alongside the other resource which is related to Forms.
Thanks,
Jamie
=> Indentation fix in resources.md

docs/.vuepress/config.js, docs/guides/models.md
This PR adds documentation for `createModel()`.
=> [docs] Add models.md

package.json, packages/core/package.json, packages/xstate-viz/package.json, yarn.lock
This should fix the problem that has manifested here: https://github.com/davidkpiano/xstate/runs/2600705137
=> Fixed build of the core by enforcing compatible tslib version

README.md, docs/about/resources.md
This PR adds the [XState Catalogue](https://xstate-catalogue.com/) to the README and the `resources.md` page.
=> [docs] Add XState Catalogue

.changeset/nasty-mirrors-hope.md, docs/packages/xstate-vue/index.md, packages/xstate-vue/README.md, packages/xstate-vue/src/index.ts, packages/xstate-vue/src/useSelector.ts, packages/xstate-vue/test/UseMachine-no-extra-options.vue, packages/xstate-vue/test/UseMachine.vue, packages/xstate-vue/test/UseSelector.vue, packages/xstate-vue/test/UseSelectorCustomFn.vue, packages/xstate-vue/test/useMachine.test.ts, packages/xstate-vue/test/useSelector.test.ts, packages/xstate-vue/test/useService.test.ts, tsconfig.monorepo.json
This PR adds `useSelector` hook to `@xstate/vue`.
Added tests & docs 💖
=> [@xstate/vue] Add useSelector composable

docs/examples/todomvc.md
Showcase new version from xstate Github repo example that uses Vue 3
fixes #2249
=> [docs] Update todmvc Vue Codesandbox embed

docs/guides/actors.md
=> [docs] Update actors.md

.changeset/fifty-rocks-protect.md, packages/xstate-vue/src/index.ts, packages/xstate-vue/src/useSpawn.ts, packages/xstate-vue/test/UseSpawn.vue, packages/xstate-vue/test/useSpawn.test.ts
This brings the latest hook to Vue :)
=> [@xstate/vue] New `useSpawn` composable

.github/ISSUE_TEMPLATE/bug_report.yml
This PR adds an issue form for bug reports.
=> Add bug_report.yml

docs/guides/models.md
This PR discourages use of narrowed model.assign actions in machine options
=> [docs] Update `models.md`

docs/guides/actions.md
=> [docs] Fix send action in actions.md

docs/recipes/ember.md
Shameless self-promotion :upside_down_face:
=> Add entry about ember-statechart-component

docs/recipes/react.md
Minor update to fix a sentence that doesn't quite make sense!
=> Spelling update

packages/core/test/actor.test.ts
Based on this discussion: https://discord.com/channels/795785288994652170/799416943324823592/869735082640957501
Just verifying the behavior, passes in the tests
=> [core] Add passing test for lazy spawning machines in initial context

.changeset/quiet-islands-sit.md, packages/core/src/types.ts
=> Add utility-type EmittedFrom<T> that extracts Emitted type from any type which can emit data

docs/guides/context.md
interpreted machine has to be started
=> fixed interpret(counterMachine).send({ type: 'INC_TWICE' });

examples/react-tic-tac-toe/src/ticTacToe.machine.ts, examples/todo-mvc-react/src/App.jsx, examples/todo-mvc-react/src/todo.machine.ts, examples/todo-mvc-svelte/src/todo.machine.ts, examples/todo-mvc-svelte/src/todos.machine.ts, examples/todo-mvc-vue/src/todoItem.machine.ts, examples/todo-mvc-vue/src/todos.machine.ts
`react-tic-tac-toe/src/ticTacToe.machine.ts` still has two type errors.
=> Remove unwanted imports, other tiny fixes

.changeset/fast-bees-applaud.md, .changeset/proud-swans-lie.md, packages/core/src/utils.ts, packages/xstate-react/src/useInterpret.ts, packages/xstate-react/test/useMachine.test.tsx
fixes #2586 (a regression caused by #2241)
i will add a changeset and tests in a few hours
=> Fixed an issue with updating options in React's effect

docs/about/tutorials.md
Kyle's course is great and free to view for the public so it makes sense to include it in the list!
=> Added Kyle Shevlin's free egghead course in video section

.changeset/young-spoons-drop.md, packages/core/src/interpreter.ts, packages/core/src/types.ts, packages/core/test/invoke.test.ts
This PR adds `meta` data to `invoke: { ... }`
=> [core] Invoke meta data

docs/guides/communication.md
=> Code syntax error

docs/about/resources.md
Updated some more resources from the discord channel
=> added more resources from discord

docs/.vuepress/theme/components/AlgoliaSearchBox.vue
=> fix: docs AlgoliaSearchBox.vue "dddd" text

packages/xstate-vue/README.md
=> [docs] Fix link to Vue recipe

.changeset/flat-clouds-greet.md
=> [v5] Fix changeset: `not(stateIn())`

docs/zh/README.md
@lecepin
Hi! First of all, thanks much for your effort to bring us excellent Chinese documentation.
I read the xstate's documentation and tried to translate it into Chinese; since you've built a solid foundation, all I can do is polish your work and make it better.
This PR is the first piece of work that needs your review to ensure its usefulness. For convenience, I will use our native language to continue the conversation.
=> revise the chinese translations - README.md

.changeset/rude-starfishes-invite.md
This PR fixes a minor formatting issue in the `config.schema` changeset
=> Reformat `config.schema` changeset

examples/react-tic-tac-toe/src/ticTacToe.machine.ts
The previous version was unsound and we should avoid this kind of code from spreading and being recommended as best practice.
This also poses an important challenge - how do we incorporate typegen stuff into examples etc? There are obviously environments that just are not customizable enough for us to plug the typegen into them. What are those environments though, apart from online code editors like CodeSandbox? cc @mattpocock
=> Tweak the tic-tax-toe example to avoid unsound code from spreading

.changeset/good-queens-cross.md, .changeset/wet-insects-share.md, packages/core/src/types.ts, packages/core/test/typeHelpers.test.ts
fixes https://github.com/statelyai/xstate/issues/3103
=> Fixed `ContextFrom` and `EventFrom` types

packages/core/src/types.ts, packages/core/test/typeHelpers.test.ts
in relation to findings from https://github.com/statelyai/xstate/issues/2727#issuecomment-1057804451
=> Add `EventFrom` test for matching interpreters

.changeset/friendly-boxes-grow.md, packages/core/src/types.ts, packages/core/test/types.test.ts
fixes https://github.com/statelyai/xstate/issues/3128
=> Limit inference sites for `TEvent`

.changeset/bright-humans-admire.md, packages/core/src/StateNode.ts, packages/core/test/guards.test.ts
fixes https://github.com/statelyai/xstate/issues/3163
=> Fixed an issue with `state.tags` not having correct values when resolving micro transitions

docs/packages/xstate-vue/index.md
resolves https://github.com/statelyai/xstate/issues/3169
Updates the description and example code for `useActor` in [@xstate/vue](https://xstate.js.org/docs/packages/xstate-vue/)
=> Xstate vue  update use actor documentation

.changeset/stupid-plums-smile.md, packages/core/src/types.ts, packages/core/test/typeHelpers.test.ts
Just a helper type that was requested~ at least twice on Discord
=> Added a `StateValueFrom` helper that can be used to extract valid state values from a machine

packages/core/src/types.ts
Still looking into fixing the rest
=> Fix part of the current type errors on the `next` branch

packages/xstate-graph/src/graph.ts, packages/xstate-graph/test/__snapshots__/graph.test.ts.snap, packages/xstate-graph/test/graph.test.ts, packages/xstate-test/test/dieHard.test.ts
This will be replaced in the future by transition coverage in path generation
=> [@xstate/graph] Remove actions from serialized state

packages/xstate-test/src/TestModel.ts, packages/xstate-test/src/machine.ts, packages/xstate-test/test/dieHard.test.ts, packages/xstate-test/test/paths.test.ts
=> Consider all cases in path generation

docs/packages/xstate-immer/index.md
Fixed dead link to the introduction page of immer.
=> Fixed a dead link

packages/xstate-graph/src/graph.ts, packages/xstate-graph/src/types.ts, packages/xstate-test/src/machine.ts, packages/xstate-test/src/types.ts
=> `@xstate/graph` - Consider `prevState` for state serialization

docs/guides/context.md
This PR adds a warning about pure assignments to the docs.
=> Add pure assignment warning

.changeset/strange-bottles-punch.md, packages/core/src/interpreter.ts
fixes https://github.com/statelyai/xstate/issues/3519
I'm not super sure that it's worth fixing this but 🤷‍♂️
=> Fixed a runtime error when sending an empty array of events

docs/.vuepress/styles/index.styl, docs/README.md
=> Use light mode image on docs

docs/fr/guides/context.md, docs/guides/context.md
Changes for the [issue](https://github.com/statelyai/xstate/issues/2860#issuecomment-1278835661)
=> Add lazy initialization in the context guides

packages/core/test/actions.test.ts
When reviewing https://github.com/statelyai/xstate/pull/3623 I've found the manual `actual` tracking for this particular use case to be quite repetitive.
The repetition itself wasn't that bad **but** this helper will also automatically guard us against regressing on stuff that we sometimes just don't assert. The problem fixed by #3623 was related to us incorrectly calling some entry actions - some related tests were focused purely on the *expected* results but not as much on the *accidental* results. The PR has introduced a test in which the fully correct behavior could be verified but some of the expectations looked redundant. So I've figured out that by introducing such a helper:
- we won't remove those "redundant" entry/exit logs
- we'll add similar safe-guards to all the tests that …
=> Add a test util for tracking entry/exit actions in tests

.gitignore
This PR changes gitignore to ignore settings from JetBrains IDE's. I like to jump between editors, and it's nice that git ignores the specific setting files.
=> Ignore files from JetBrains IDE's

docs/visualizer/README.md
Fixing for broken live updating snapshot images
====================================
=> [Documentation] Update broken live updating snapshot images

docs/fr/packages/xstate-inspect/index.md, docs/packages/xstate-inspect/index.md, docs/zh/packages/xstate-inspect/index.md
This PR removes buttondown links that were causing security notices in Chrome.
=> Remove outdated images

README.md
=> Add @xstate/solid to packages list in README

.changeset/odd-dolls-drum.md, packages/xstate-react/src/useActor.ts, packages/xstate-react/src/useMachine.ts, packages/xstate-react/src/utils.ts, packages/xstate-react/test/useActor.test.tsx
fixes https://github.com/statelyai/xstate/issues/3798
=> Work around over-eager warnings coming from uSES

.changeset/silent-tips-occur.md, packages/core/src/interpreter.ts
=> Fixed an issue with not clearing registered interpreters when their machines reached final states

packages/xstate-react/test/createActorContext.test.tsx
This PR fixes the issue mentioned by @Andarist at https://github.com/statelyai/xstate/pull/3804#discussion_r1095173797
=> Fix code issues in createActorContext test

.changeset/twenty-feet-wink.md, packages/xstate-solid/src/deriveServiceState.ts, packages/xstate-solid/test/useMachine.test.tsx
Explicitly add nextEvents to state in deriveServiceState to overcome issue with custom get defined by State
Add test for state.nextEvents
Fixes #3809
=> [xstate/solid] Fix state.nextEvents being undefined and not updating

docs/guides/models.md
closes https://github.com/statelyai/xstate/issues/2855
=> Remove the note from the docs about model-based actions being correctly inferred within the implementations argument

packages/xstate-svelte/package.json, packages/xstate-svelte/test/tsconfig.json
While investigating something else I noticed that this might be configured slightly incorrectly
=> Scope `svelte-check` properly and make it use the correct `tsconfig.json`

.changeset/stale-plants-design.md, packages/core/src/actions.ts, packages/core/src/types.ts, packages/core/test/actionCreators.test.ts, packages/core/test/types.test.ts
fixes https://github.com/statelyai/xstate/issues/3854
fixes https://github.com/statelyai/xstate/issues/3845
=> Fixed event type narrowing in some of the builtin actions

.changeset/quick-ads-compete.md, packages/xstate-solid/src/createImmutable.ts, packages/xstate-solid/test/useActor.test.tsx
Add test to cover affected array updates
Fixes #3853
=> [xstate/solid] Fix array deletions/additions causing duplicate entries

.changeset/tough-windows-applaud.md, packages/core/src/interpreter.ts, packages/core/src/typegenTypes.ts
supersedes https://github.com/statelyai/xstate/pull/3955
=> Improve missing implementations error by mentioning missing names

docs/recipes/vue.md
Added context on XState usage depending on the version of Vue.
=> Update Vue 2 recipe

packages/core/src/State.ts, packages/core/src/StateMachine.ts, packages/core/src/stateUtils.ts, packages/core/src/types.ts, packages/core/test/actionCreators.test.ts
Forgot to do this in https://github.com/statelyai/xstate/pull/4063
=> Remove `StateConfig['transitions']`

.changeset/nervous-eggs-pretend.md, packages/core/src/index.ts
fixes https://github.com/statelyai/xstate/issues/4158
=> Export `cancel` action from the core's main entrypoint

docs/about/resources.md
Hi, I was going through articles the other day and I saw that maybe it could be better to explicitly state that my article is about handling the form in the context of React Native app :) 
I also updated my twitter handle
Thanks for your work and have a nice day!
=> docs: update link in `about -> resources -> articles`

.changeset/curvy-seahorses-obey.md, packages/core/src/StateNode.ts, packages/core/src/actions/choose.ts, packages/core/src/guards.ts, packages/core/src/stateUtils.ts, packages/core/src/types.ts, packages/core/test/actions.test.ts, packages/core/test/guards.test.ts, packages/core/test/types.test.ts
fixes https://github.com/statelyai/xstate/issues/4003
=> Refactor composite guards

.changeset/light-points-grin.md, packages/core/src/actions/pure.ts, packages/core/test/types.test.ts
fixes https://discord.com/channels/795785288994652170/1144738951165386934/1144738951165386934
=> Allow the types to flow from `pure` to `raise`

.changeset/tricky-clouds-clap.md, packages/core/src/Machine.ts, packages/core/src/StateMachine.ts, packages/core/src/StateNode.ts, packages/core/src/actions/choose.ts, packages/core/src/actions/pure.ts, packages/core/src/actions/raise.ts, packages/core/src/actions/send.ts, packages/core/src/scxml.ts, packages/core/src/stateUtils.ts, packages/core/src/typegenTypes.ts, packages/core/src/types.ts, packages/core/test/types.test.ts, packages/xstate-react/src/createActorContext.ts, packages/xstate-react/src/useActorRef.ts, packages/xstate-solid/src/types.ts, packages/xstate-svelte/src/useMachine.ts, packages/xstate-test/src/types.ts, packages/xstate-vue/src/useInterpret.ts, packages/xstate-vue/src/useMachine.ts
=> [v5] Delay types

docs/packages/xstate-vue/index.md
This PR updates the Vue docs to use [`<script setup>`](https://vuejs.org/api/sfc-script-setup.html#script-setup) as it is the recommended syntax if using both SFCs and Composition API.
=> docs(vue): migrate examples to script setup

packages/core/test/invoke.test.ts
pulled out from https://github.com/statelyai/xstate/pull/2935/files#r781981212
=> Rewrite one of the `invoke.onError` tests

packages/core/src/StateNode.ts
fixes https://github.com/statelyai/xstate/issues/4254
=> Fixed a typo in internal `toSerializableAction` util

.changeset/old-bulldogs-invent.md, packages/core/src/interpreter.ts, packages/core/src/types.ts, packages/core/test/interpreter.test.ts
I doubt this was a popular option.
=> Remove `deferEvents` option

examples/mongodb-persisted-state/README.md
adds a readme to get started with the mongodb example
=> add readme

.changeset/popular-chefs-camp.md, packages/core/src/StateMachine.ts, packages/core/test/rehydration.test.ts
fixes https://github.com/statelyai/xstate/issues/4328
=> Fix a parent reference on rehydrated children

.changeset/metal-mugs-learn.md, packages/core/src/StateMachine.ts, packages/core/test/actorLogic.test.ts
This PR fixes state machine logic so it can be composable.
=> [v5] Composable logic

.changeset/moody-needles-melt.md, packages/core/src/stateUtils.ts, packages/core/test/actions.test.ts
initially found here: https://github.com/statelyai/xstate/pull/4234/files#r1316044290
=> Fixed an issue with actions of initial transitions being called too many times

.changeset/olive-suns-begin.md, packages/core/src/StateMachine.ts, packages/core/src/stateUtils.ts, packages/core/test/final.test.ts
closes https://github.com/statelyai/xstate/issues/2349
=> Generate `xstate.done.state.*` events recursively for nested parallel states

.changeset/twenty-hornets-push.md, packages/core/src/stateUtils.ts, packages/core/test/actions.test.ts
fixes https://github.com/statelyai/xstate/issues/4167
=> Fixed an issue with exit actions being called twice when machine reached its final state

packages/core/src/actors/callback.ts
Includes `fromCallback` and `InvokeCallback`
Based on:
- https://stately.ai/docs/actors#callback-actors
- https://stately.ai/blog/announcing-xstate-v5-beta#actor-first-approach-for-any-logic
=> API Docs: fromCallback

.changeset/chatty-beans-mate.md, packages/core/src/stateUtils.ts, packages/core/test/actions.test.ts, packages/core/test/parallel.test.ts
fixes https://github.com/statelyai/xstate/issues/4360
=> Fixed an issue with parallel transition sources not being reentered correctly

packages/core/src/interpreter.ts
Add docs for `system` and `getSnapshot`.
Mark `delaySend` and `cancel` internal.
Add a brief description for `Actor`.
=> API Docs: Actor

packages/core/test/parallel.test.ts
tests inspired~ by https://github.com/statelyai/xstate/issues/2401
=> Add extra test cases for targetless transitions combined with parallel states

.changeset/friendly-jars-joke.md, packages/core/src/State.ts, packages/core/src/StateMachine.ts, packages/core/src/actions/spawn.ts, packages/core/src/interpreter.ts, packages/core/src/spawn.ts, packages/core/src/types.ts, packages/core/test/rehydration.test.ts, packages/xstate-react/test/useActor.test.tsx
fixes https://discord.com/channels/795785288994652170/1176357070547730462/1176357070547730462
=> Fixed an issue with `onSnapshot` not working after rehydration

.changeset/deep-actor-rehydration.md, packages/core/src/StateMachine.ts, packages/core/test/rehydration.test.ts
fixes https://github.com/statelyai/xstate/issues/4486
=> Fixed an issue with actors deep in the tree failing to rehydrate

.changeset/large-comics-vanish.md, packages/core/src/actors/callback.ts, packages/core/src/actors/index.ts
fixes https://github.com/statelyai/xstate/discussions/4512
=> Export all TS snapshot types

.changeset/shy-bugs-pump.md, packages/core/src/actors/promise.ts, packages/core/src/setup.ts, packages/core/src/types.ts, packages/core/test/actor.test.ts, packages/core/test/invoke.test.ts, packages/core/test/setup.types.test.ts
fixes https://github.com/statelyai/xstate/issues/4550
=> Fixed defining `actors` with `input` within `setup`

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, templates/react-ts/.codesandbox/template.json, templates/react-ts/README.md, templates/vanilla-ts/.codesandbox/template.json, templates/vanilla-ts/README.md, templates/vue-ts/.codesandbox/template.json
Test the updated README: https://github.com/statelyai/xstate/blob/93c6376078cb69e120157c7bd171a2baa5154eef/README.md
=> Add template data for StackBlitz + CodeSandbox

.changeset/silent-dragons-jog.md, packages/xstate-vue/src/useActor.ts
=> Fix useActor send types for ActorLogic

examples/express-workflow/index.ts, examples/express-workflow/package.json, examples/express-workflow/pnpm-lock.yaml
Just keeping up with the new updates for V5
=> format with prettier. update getPersistedSnapshot() function call

examples/7guis-counter-react/src/counter.machine.ts, examples/counter/src/counterMachine.ts, examples/friends-list-react/src/friend.machine.ts, examples/snake-react/src/snakeMachine.ts
This pull request was created from this [Stately Studio project.](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2)
- [examples/snake-react/src/snakeMachine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=d846c9dd-a54e-4354-a974-27bfab3a8270)
- [examples/friends-list-react/src/friend.machine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=27e3b790-e892-4516-8ce7-7a602ebdc507)
- [examples/7guis-counter-react/src/counter.machine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=d0a1833b-3f3c-479a-930b-24c22cf5ae84)
- [examples/counter/src/counterMachine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=5314b3 …
=> Add Pause state

examples/snake-react/src/snakeMachine.ts
This pull request was created from this [Stately Studio project.](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2)
- [examples/snake-react/src/snakeMachine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=d846c9dd-a54e-4354-a974-27bfab3a8270)
- [examples/friends-list-react/src/friend.machine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=27e3b790-e892-4516-8ce7-7a602ebdc507)
- [examples/7guis-counter-react/src/counter.machine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=d0a1833b-3f3c-479a-930b-24c22cf5ae84)
- [examples/counter/src/counterMachine.ts](http://localhost:3000/registry/editor/1cfa7d95-5db3-4051-a2fc-c33abdb1a5e2?machineId=5314b3 …
=> Remove pause state

examples/friends-list-react/src/friends.machine.ts, examples/stopwatch/src/stopwatchMachine.ts
This pull request was created from this [Stately Studio project.](http://localhost:3000/registry/editor/bbca83ae-bfff-4488-9542-7f5743f6e08c)
- [examples/stopwatch/src/stopwatchMachine.ts](http://localhost:3000/registry/editor/bbca83ae-bfff-4488-9542-7f5743f6e08c?machineId=de8ac308-32fc-4201-b621-d85b45ccd6a9)
- [examples/friends-list-react/src/friends.machine.ts](http://localhost:3000/registry/editor/bbca83ae-bfff-4488-9542-7f5743f6e08c?machineId=7df97cbb-4cf5-4ee9-b9e8-1d6405ec2a6a)
=> PR from version view

examples/snake-react/src/snakeMachine.ts, examples/timer/src/timerMachine.ts
This pull request was created from this [Stately Studio project.](http://localhost:3000/registry/editor/93e4c37f-2295-44f4-9d2b-b5f9f70f9a4f)
- [examples/timer/src/timerMachine.ts](http://localhost:3000/registry/editor/93e4c37f-2295-44f4-9d2b-b5f9f70f9a4f?machineId=729705e1-6a5b-4749-8938-41cc68bbc943)
- [examples/snake-react/src/snakeMachine.ts](http://localhost:3000/registry/editor/93e4c37f-2295-44f4-9d2b-b5f9f70f9a4f?machineId=c133af8c-35d4-418a-947d-bc5c1e81e326)
=> Improve layout of Snake

examples/snake-react/src/snakeMachine.ts, examples/toggle/src/toggleMachine.ts, newMachines/not-stopwatch.ts
This pull request was created from this [Stately Studio project.](http://localhost:3000/registry/editor/f84469b2-524c-4fa3-9341-e3242b2cbfeb)
- [newMachines/not-stopwatch.ts](http://localhost:3000/registry/editor/f84469b2-524c-4fa3-9341-e3242b2cbfeb?machineId=939d8c82-6f71-4280-b593-abbe32f98d83)
- [examples/toggle/src/toggleMachine.ts](http://localhost:3000/registry/editor/f84469b2-524c-4fa3-9341-e3242b2cbfeb?machineId=db17f432-f8a3-4bbe-8d9b-2c27a5cd1ca8)
- [examples/snake-react/src/snakeMachine.ts](http://localhost:3000/registry/editor/f84469b2-524c-4fa3-9341-e3242b2cbfeb?machineId=d407ed71-e3fa-4aec-b5cb-c574c7db1671)
=> Add a Paused state

examples/workflow-send-cloudevent/main.ts
This pull request was created from this [Stately Studio project.](https://registry-ev3alaq0g-statelyai.vercel.app/registry/editor/33949758-65cb-4d92-b2af-bfa562d9726f)
- [examples/workflow-send-cloudevent/main.ts](https://registry-ev3alaq0g-statelyai.vercel.app/registry/editor/33949758-65cb-4d92-b2af-bfa562d9726f?machineId=ae05f86c-d950-46f3-b9b0-947e6b11f5ce)
=> testing layout string

examples/workflow-send-cloudevent/main.ts, src/stately-studio/testing-newly-added-machine.ts
This pull request was created from this [Stately Studio project.](https://registry-ev3alaq0g-statelyai.vercel.app/registry/editor/e20c94ff-3b45-4a91-985f-a4749492a178)
- [src/stately-studio/testing-newly-added-machine.ts](https://registry-ev3alaq0g-statelyai.vercel.app/registry/editor/e20c94ff-3b45-4a91-985f-a4749492a178?machineId=220c9939-5e68-41f4-8cd4-ff83c53dd4fd)
- [examples/workflow-send-cloudevent/main.ts](https://registry-ev3alaq0g-statelyai.vercel.app/registry/editor/e20c94ff-3b45-4a91-985f-a4749492a178?machineId=c1f12b87-a2b8-42dc-910b-8bc71d45ea26)
Custom description here
=> added new machine (starter)

packages/xstate-react/README.md
See: https://github.com/statelyai/xstate/pull/4656#discussion_r1444050609
=> Remove xstate-react CDN install in README.md

.changeset/hot-ties-call.md, packages/core/src/typegenTypes.ts
fixes https://github.com/statelyai/xstate/issues/4664
=> Fixed compatibility with older versions of integration packages

CONTRIBUTING.md, examples/readme.md
As recently discussed in Discord: https://discord.com/channels/795785288994652170/1200021503002017872. 
Would have saved a newbie a thread.
=> Add-contributing-guidance

CONTRIBUTING.md
=> fix link formatting

.changeset/clean-brooms-yell.md, packages/core/src/index.ts, packages/core/test/deterministic.test.ts, packages/core/test/getNextSnapshot.test.ts, packages/core/test/id.test.ts
You can now import `getInitialSnapshot(…)` from `xstate` directly:
```ts
import { getInitialSnapshot } from 'xstate';
```
=> Expose getInitialSnapshot

examples/7guis-1-counter-vue/.gitignore, examples/7guis-1-counter-vue/.vscode/extensions.json, examples/7guis-1-counter-vue/README.md, examples/7guis-1-counter-vue/index.html, examples/7guis-1-counter-vue/package.json, examples/7guis-1-counter-vue/pnpm-lock.yaml, examples/7guis-1-counter-vue/src/App.vue, examples/7guis-1-counter-vue/src/Counter.vue, examples/7guis-1-counter-vue/src/components/HelloWorld.vue, examples/7guis-1-counter-vue/src/counterMachine.ts, examples/7guis-1-counter-vue/src/main.ts, examples/7guis-1-counter-vue/src/style.css, examples/7guis-1-counter-vue/src/vite-env.d.ts, examples/7guis-1-counter-vue/tsconfig.json, examples/7guis-1-counter-vue/tsconfig.node.json, examples/7guis-1-counter-vue/vite.config.ts
Adds an example app for Vue: 1st task of the 7 GUIs.
=> Add-example--vue-7guis-1

.changeset/odd-falcons-play.md, packages/core/src/actions.ts
fixes https://github.com/statelyai/xstate/issues/4779
=> Add missing `emit` export

.changeset/eighty-bugs-shop.md, packages/xstate-store/src/index.ts
This PR exports types for `@xstate/store`.
=> [@xstate/store] Export types

templates/react-ts/src/feedbackMachine.ts, templates/svelte-ts/src/feedbackMachine.ts, templates/vanilla-ts/src/feedbackMachine.ts, templates/vue-ts/src/feedbackMachine.ts
This PR fixes the templates so that the feedback is reset.
=> [templates] Reset prompt when restarting in templates

babel.config.js
I don't think this is needed any longer
=> Remove `stripSymbolObservableMethodPlugin`

.changeset/thirty-spoons-provide.md, packages/core/src/types.ts, packages/core/test/setup.types.test.ts
=> [core] Fix `EventFrom` and `ContextFrom`

packages/xstate-store/src/store.ts, packages/xstate-store/src/types.ts
=> [@xstate/store] Fix store inspection issues

.github/actions/ci-checks/action.yml, .knip.jsonc, packages/core/src/State.ts, packages/xstate-store/src/store.ts
=> add knip to ci-checks

.github/workflows/docs.yml
follow up to https://github.com/statelyai/xstate/pull/4987
=> Fix `docs` workflow

.changeset/rude-eyes-cheer.md, packages/xstate-store/src/store.ts
fixes https://github.com/statelyai/xstate/issues/5135
=> Fixed an accidental used reference of `xstate` types

.changeset/lazy-dolphins-sort.md, packages/xstate-store/src/store.ts, packages/xstate-store/test/store.test.ts
=> [@xstate/store] Fix emitted event type being overridden

packages/core/test/actorLogic.test.ts, packages/xstate-react/package.json, packages/xstate-react/test/createActorContext.test.tsx, packages/xstate-react/test/useActorRef.test.tsx, packages/xstate-store/package.json, packages/xstate-store/src/react.ts, pnpm-lock.yaml
Doing this cleanup since React 19 is out
=> [xstate/react] [xstate/store] Update React dependencies

.changeset/heavy-sloths-tell.md, packages/xstate-store/src/alien.ts, packages/xstate-store/src/atom.ts
Just doing some things to reduce the overall bundle size.
=> [@xstate/store] Minifying atom implementation

.changeset/rude-keys-grab.md, packages/core/src/StateMachine.ts, packages/core/test/history.test.ts
follow up to https://github.com/statelyai/xstate/pull/5269
=> Tweak history value persistence and restoration

.changeset/nine-starfishes-hunt.md, packages/xstate-store/src/atom.ts, packages/xstate-store/src/types.ts, packages/xstate-store/test/atom.test.ts
Added async atoms:
```ts
const atom = createAsyncAtom(async () => {
const response = await fetch(`/api/something`);
return response.json();
});
atom.subscribe((state) => {
// Status can be 'pending', 'fulfilled', or 'rejected'
if (state.status === 'fulfilled') {
console.log(state.data);
}
});
```
=> [@xstate/store] Async atoms

.changeset/witty-dryers-listen.md, packages/xstate-store/src/index.ts
fixing https://github.com/statelyai/xstate/issues/5281
=> fix: async atom export

.changeset/eleven-bulldogs-greet.md, packages/xstate-store/src/alien.ts, packages/xstate-store/src/atom.ts, packages/xstate-store/src/types.ts
Synchronize the alien-signals algorithm to 2.0.4, the tests are all passed, but I suggest you still need to check whether the current behavior is as expected.
=> refactor: alien-signals 2.0.4

docs/fr/packages/xstate-test/index.md, examples/mongodb-credit-check-api/README.md, examples/mongodb-credit-check-api/index.ts, examples/readme.md, examples/trivia-game-example/src/components/game/Clue.tsx, examples/workflow-media-scanner/README.md, packages/core/src/Mailbox.ts, packages/core/src/setup.ts, packages/core/src/stateUtils.ts, packages/core/test/history.test.ts, packages/core/test/invoke.test.ts, packages/core/test/scxml.test.ts, packages/xstate-react/src/stopRootWithRehydration.ts, packages/xstate-store/src/store.ts
=> refactor: fix typos

packages/core/src/index.ts, packages/core/src/inspection.ts
Same deal as https://github.com/statelyai/xstate/pull/5315
=> [core] Export `InspectedMicrostepEvent`

examples/tiles/vite.config.ts, templates/svelte-ts/vite.config.ts, templates/vue-ts/vite.config.ts
Update Vite configuration in examples and templates to allow all server hosts. Fixes #5348
=> CodeSandbox templates host fix

.changeset/lazy-rabbits-complain.md, packages/xstate-store/src/alien.ts
Synchronize the alien-signals algorithm to 2.0.7.
This is primarily to fix the severe performance degradation discovered in `vuejs/core`: https://github.com/vuejs/core/pull/13654
=> refactor: alien-signals 2.0.7

packages/xstate-store/test/store.test.ts
=> refactor: remove unused import in test
