statelyai/xstate

- src/index.ts
- test/dfa.ts
Thanks for the great library. This has been immensely helpful for what I'm working on right now.
The only pain point I've had in about a week of using this is that when transitioning to a state that is not defined:
``` javascript
states: {
a: {
on: {
continue: 'b'
}
// 'b' should be declared here but I forgot
}
```
the error logged seems completely unrelated to the actual problem at first glance.
When I read "cannot read property 'initial'", I thought my chart provided to the `Machine()` function was invalid somehow. This was confusing because I transitioned to 3 other states before seeing this error and spent 2 hours thinking I was crazy and the stacktrace was utterly useless.
Anyway, I hope this is a good start to the solution so others don't run into this problem.
> Throw a more helpful error when transitioning to an undefined state

- src/graph.ts
- src/index.ts
- test/examples/6.17.test.ts
- test/graph.test.ts
The `getShortestPaths` method is currently failing when a condition is present because the `cond` function is called with `undefined`. 
This PR fixes the issue, the relevant changes are in https://github.com/davidkpiano/xstate/commit/52fb0e236f8795e222d99f624e9cd56b4912b783.
> getShortestPaths + condition

- src/graph.ts
- src/index.ts
- test/examples/6.17.test.ts
- test/matches-state.test.ts
- test/parallel.test.ts
- test/utils.ts
The `extendedState` isn't pass when we call the transition on the parent.
> Fix extended state on transition

- test/machine.test.ts
When a machine declares event handlers at the top level, they seem to
be ignored altogether.
> Top level events aren't handled, exposes bug #71

- src/StateNode.ts
- test/history.test.ts
- test/machine.test.ts
History is shallow by default (as exposed by this test) and supports deep histories with specific depths using `$history.$history.$history` syntax.   This PR adds tests to verify this behaviour.
This test also checks if a state in question _has_ substates, and ignores `$history` elements if they are present.  If you happen to hit on a $history.$history state where the first level doesn't have any substate (but e.g. another possible $history has substates) then it would previously throw 
```
Error: Cannot read '$history' from state 'history.on.second.A': missing 'initial' 
```
> Verify and harden deep history

- test/deep.test.ts
This test case has a machine with four nested levels, A, B, C, D, which happens to be the initial state.  A has two sibling states DONE and FAIL, and the nodes A, B, C and D all react to A_EVENT, B_EVENT and so on.
Currently the test only checks that the right exit handlers are called, and exposes problems with handling deeply nested states.
> Added some tests that expose problems with deeply nested states

- src/StateNode.ts
- src/types.ts
- test/multiple.test.ts
For your consideration.  Due to indentation issues you should diff this while ignoring whitespace.
> Support multiple targets

- test/actions.test.ts
transitioning to #foo.bar.baz and to baz should yield the same
results.  This test exposes that it doesn't: It actually enters the
states that it's already in.
> Added a pending test for transitioning to a # state

- docs/api/config.md
- docs/guides/guards.md
This PR updates the documentation to show that you can pass an ordered array of state transition mappings to support transitioning to different states from a single event based on external state.
Based on a quick discussion with @davidkpiano at https://github.com/davidkpiano/xstate/issues/88#issuecomment-380880232
> Add documentation for the array of state transitions mappings

- docs/api/actions.md
The onExit indicates that they run when entering a state instead of when leaving a state.
> Fix typo describing the purpose of onExit actions

- test/actions.test.ts
> Add test to ensure invalid transitions don't recall previous actions.

- test/transient.test.ts
When to regions react to the same state, the 'in' conditions need to
be executed against the correct microstep intermediate states.  This
test verifies that this is the case.
> Verify that microsteps are executed at the same time

- src/StateNode.ts
- src/types.ts
- test/guards.test.ts
When a transition occurs, and you want to check e.g. if you're in
states X and Y at the same time, and only perform e.g. an automatic
transition when you're in that state, you need to access the states
that are happening as part of a microstep.
The guard function now support a third argument, namely the "interim
state" so to speak, which is a StateValue suitable for using with
matchesState in order to check if you're "in" various states.
> Guards can now access the interim states

- test/activities.test.ts
If you have an activity in a state, but the state has an automatic
transition to another state, but the guard fails, the activity is
forgotten; the 'activities' no longer indicates the activity as it
should.
> Exposed but with activities and automatic transitions

- src/State.ts
- test/activities.test.ts
Fixes #114.
State.inert didn't copy over any activites from the old state.
This is not the best way to deal with activities; ideally it should go through the current configuration of states and build up a correct view of all of the running activities based on which states are active, instead of relying on input like this.
But it gets the job done for normal use cases, no need to protect people from shooting themselves in the foot, eh?  Jolly good!
> Fixes #114

- src/StateNode.ts
- test/activities.test.ts
Fixes #131.
StateNode should handle the exit states first before the entry states to determine activities.
Also added two tests:
(1) testing that same activities are maintained during a normal transition
(2) testing that same activities are maintained during a self transition
Btw, 2 tests are failing but that's because of commit f93cb57 which added tests that are meant to fail.
> Fixing #131: Transition to self wrongly stops activity

- docs/api/actions.md
When I run this sample code on the `actions` doc:
```js
const { Machine } = require('xstate');
// example of a named function action
function showLoader(extState, event) {
// ...
}
const fetchMachine = Machine({
initial: 'idle',
states: {
idle: {
on: {
FETCH: {
pending: {
// transition actions
actions: ['warmCache', showLoader]
}
}
},
// onExit actions
onExit: ['preloadViews']
},
pending: {
// onEntry actions
onEntry: ['fetchData']
}
}
});
console.log(fetchMachine.transition(fetchMachine.initialState, 'FETCH'));
```
I got:
> [docs:actions] add missing showLoader to result actions

- src/StateNode.ts
- src/graph.ts
- src/utils.ts
Additionally `flatten` could be shortened to:
```js
export const flatten = <T>(array: T[][]): T[] => {
return [].concat(...array);
};
```
but while this has the same functionality TypeScript yells at me with:
```
src/utils.ts:196:20 - error TS2345: Argument of type 'T[]' is not assignable to parameter of type 'ConcatArray<never>'.
Types of property 'slice' are incompatible.
Type '(start?: number | undefined, end?: number | undefined) => T[]' is not assignable to type '(start?: number | undefined, end?: number | undefined) => never[]'.
Type 'T[]' is not assignable to type 'never[]'.
Type 'T' is not assignable to type 'never'.
196   return [].concat(...array);
~~~~~~~~
```
And I have no idea what's the problem.
> Fixed function naming - implemented flatMap is actually just flatten

- docs-src/package.json
Instead of manually moving the docs folder over on build, hook in through npm scripts.
> Delete build folder and recreate on build command

- src/Machine.ts
- src/actions.ts
- src/interpreter.ts
- src/types.ts
This avoids the name collision with the `Machine` function and removes the need
to alias the interface in places where both are imported.
> Rename Machine interface to StateMachine

- package.json
Fixes #241 
Corrects the mismatch in the publication setting found in `package.json` to match those previously deployed at the intersection of the `.gitignore` and `.npmignore` files.
> Return `/es` built assets to the publication

- src/StateNode.ts
- test/interpreter.test.ts
Fix cryptic message when initial state is invalid:
> fix(interpretor) add better error message for invalid init state

- src/StateNode.ts
- test/invoke.test.ts
This PR fixes a behaviour I bumped into. According [to docs](https://github.com/davidkpiano/xstate/blob/951f7fba4bdd1bc5775023b3c7886095f41a8191/docs/guides/communication.md#testing) and the comment in the `withConfig` function it should be possible to pass the services to the state machine using the `withConfig` function.
I am not sure if I've chosen the right test file to put my test into. The `machine.test.ts` was my first choice but I would have to add a lot of code there to set up the test objects properly. I've chosen to put in `invoke.test.ts` instead as most of the setup is already done there.
P.S. Thank a lot for this awesome project. I am following it for a while and I would like to finally use it for a production app. I've learned a ton from it!
> Fix passing of services using withConfig

- docs/guides/start.md
The links in Getting Started are broken - there was an extra `/guides` in the URL
> Fix links in "Getting Started" Readme

- docs/guides/transitions.md
Just fixing a broken link. I copied the convention from other pages here in the docs where you links to an internal page using `./pagename.md`
> Fix link to Guards page at bottom

- docs/guides/typescript.md
Typescript compilation error: Using the example from https://xstate.js.org/docs/guides/typescript.html#using-typescript with typescript 3.2.4I get an error in `/node_modules/xstate/lib/types.d.ts` line 134 
```
Type error: Type 'string | number' does not satisfy the constraint 'string'.
Type 'number' is not assignable to type 'string'.  TS2344
132 |     delay: number;
133 | }
> 134 | export declare type DelayedTransitions<TContext, TEvent extends EventObject> = Record<string | number, string | TransitionConfig<TContext, TEvent> | Array<TransitionConfig<TContext, TEvent>>> | Array<TransitionConfig<TContext, TEvent> & {
|                                                                                       ^
135 |     delay: number;
136 | }>;
137 | export declare type StateTypes = 'atomic' …
```
> add note about not using keyofStringsOnly

- src/interpreter.ts
In the current state (unintended pun), the `onTransition` method in the default interpreter gives a `StateListener` type which is defined like this:
```Typescript
export declare type StateListener<TContext, TEvent extends EventObject> = (state: State<TContext>, event: OmniEventObject<TEvent>) => void;
```
As you can see, the `state` type is `State<TContext>` which equals to `State<TContext, EventObject>`. We can set it to `State<TContext, TEvent>` to give a more strict type.
> Improve the typing of StateListener

- docs/recipes/react.md
Function components aren't always functional in the FP sense. React also [refers to them](https://reactjs.org/docs/components-and-props.html#function-and-class-components) as function components.
> Properly refer to function components in React

- docs/recipes/react.md
Helps when you try to send 'GOAT_LOAD_REQUEST' multiple times and get lots of state updates, but in reality state have not changed.
> update react recipe

- docs/guides/activities.md
To end up in the `green` state you need to dispatch `TIMER` and not `PED_STOP` again.
> Activities Guide: fix wrong event

- test/invoke.test.ts
I'm not sure I wrote the tests correctly, but I tried. 😅
Promise factory invocations are not working for build `v4.3.1`.
```
No service found for invocation 'promise.parent.pending:invocation[0]' in machine 'promise'. 
```
You can reproduce by visiting https://codesandbox.io/s/w0zqnkz5jl (check CodeSandbox console)
Only the npm build is failing, so I believe it was fixed in the master branch. The tests I wrote for that issue are passing.
---
Seems like `v4.2.4` broke `event.data` for `invoke.onDone.actions` (custom actions only): https://codesandbox.io/s/o46qov4mx9 (check CodeSandbox console).
I believe https://github.com/davidkpiano/xstate/commit/9674b614be342fde84680f8bcd668d74ca9eaef8 broke it because it was working in `v4.2.3`: https://codesandbox.io/s/3v418p65vp (check CodeSandbox …
> Test case for #364

- src/StateNode.ts
- test/invoke.test.ts
Fixes #367 
This adds test cases for the two failing examples in #367 and also adds a variation of the fix I suggested. After more staring at `StateNode.ts` I think the original object being spread there might've been a copy-paste error, I can't come up with a reason why you'd want to set `machine.options.services` to the node or parent's `options.services`. If that's wrong and that is desired behavior it's easy to add that line back.
All tests new & old are passing for me locally with the change to `StateNode.ts` though, so if it is necessary it probably needs a test for that behavior 😃
> fix: support multiple simultaneous services

- rollup.config.js
- src/StateNode.ts
Regarding - https://twitter.com/DavidKPiano/status/1098437300550336512 😉 
When performing env checks you should never reference `process` directly - replacing plugins are only concerned with replacing `process.env.NODE_ENV` lookup. Referencing `process` causes i.e. webpack to include a polyfill for this object.
Because of that developer-friendly warning which were meant to be removed in production bundles stayed in the bundles.
This has no dramatic effect but it allow bundlers to remove those unwanted strings in production, the UMD bundle went from 10.87 KB to 10.54 KB 
In general I don't recommend storing env check result in a variable (inline check is easier for minifiers to remove), and I strongly would advise against exporting it from a file - especially given a fact that you don't …
> Fixup env checks

- docs/recipes/react.md
Fixes #375 
The compiler error was due to React's [rules](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L793) on `useEffect` cleanup function return values. Easy fix to just remove the arrow function.
```typescript
// NOTE: callbacks are _only_ allowed to return either void, or a destructor.
// The destructor is itself only allowed to return void.
type EffectCallback = () => (void | (() => void | undefined));
```
> Fix return type of example hook

- docs/guides/states.md
In [#316](https://github.com/davidkpiano/xstate/issues/316) it was identified a problem with the rehydration of `State`s. The fix is already implemented with `machine.resolveState(...)` so I modified the documentation reflecting this changes.
> (docs) added the recommended way to restore states with machine.resolveState()

- src/interpreter.ts
- src/types.ts
- src/utils.ts
- test/invoke.test.ts
* Added `isPromiseLike()` type guard to `utils`.
* Changed invoke/service type requirement from `Promise` to `PromiseLike`.
* Used `Promise.resolve()` to adopt untrusted thenables into trusted Promises.
Related: #412
> Tweaked Promise support in interpreter to accept any thenable (aka PromiseLike)

- test/invoke.test.ts
Previously, the simulated thenable would return a real Promise when `then()` was invoked. Now, `then()` returns a simulated thenable (and any subsequent `then()` will as well).
> Improved simulated thenable in invoke test suite.

- docs/guides/typescript.md
> Ensure that your tsconfig file ~~can~~ does not include `"keyofStringsOnly": true,`.
Removed the word "can"
> Typo at line 96 in Using TypeScript documentation

- src/index.ts
It's not exported, so can't be used in TS code. interpret() : Interpreter, the function is exported though, and I was kind of under the impression that this would be a tsc compile error, but I guess not.
> Update index.ts, export Interpreter class

- src/State.ts
- test/state.test.ts
Currently, since the `matches` and `toStrings` methods are added to the prototype of State, the context of `this` will be lost in case of reassignment or object destructing.
```js
const { matches } = machineState;
console.log(matches('some_state'));
```
> Fix State instance loosing it's context

- docs/guides/communication.md
Enhancing the docs by referencing send action creators from the actions page inside ping pong example in the invoking service page.
> Adds reference to send action creator in invoked services docs

- test/actions.test.ts
While reading SCXML spec I've found out that this is supposed to work, I then got curious if xstate implements it - and it does 😉 There was no test to cover this, so I've added one.
> Add test for onEntry defined on parallel state

- docs/guides/states.md
In the states guide, the Persisting State example references a restoredStateDef variable which is not defined.
restoredStateDef used to be the result of parsing the persisted state definition but in #393 the example was updated to use State.create and the resolveState call remained referencing the old declaration. This PR fixes the inconsistency.
Something to consider is that now `restoredState` and `resolvedState` are very similar variable names and this might be a little bit confusing. Making restoredState more verbose (restoredStateDef or restoredStateDefinition) to emphasise it is the state *definition*, not the resolved state, could make it clearer IMO.
> Fix typo in docs

- docs/packages/xstate-react/index.md
- packages/xstate-react/README.md
I'm assuming that `useConfig` does not exist, as I couldn't find any usages of it throughout the codebase. So I've updated the docs to describe `withConfig` instead.
> `useConfig` -> `withConfig` in docs

- src/types.ts
After being using heavily for the last months this project, this particular type has been particulary annoying as when you're defining the initialization the service call typing gets lost.
This modification allows to keep the possibility of using the type expansively, but does set a default type that makes more sense than `any`. 
I hope you find this improvement useful.
**ATTENTION:** For this change I had to change the order of the generics, which can lead to breaking changes on the types if this is merged.
> InvokeCreator: Improving types

- README.md
* `-S` is no longer needed; `npm install` adds to `package.json` by default now.
* `npm install` is more readable/newbie friendly than `npm i`
* README is shorter and more approachable with redundant install instructions removed
> simplify the install instructions

- docs/guides/communication.md
- src/interpreter.ts
- src/types.ts
- test/actor.test.ts
- test/invoke.test.ts
closes #494 
Not sure how you feel about changing public `forward` option to `autoForward`. I thought it might be a good change because:
- it aligns with SCXML
- it also aligns to what it was converted to under the hood [here](https://github.com/davidkpiano/xstate/blob/167fd5b37fe320f3101b09ac917810bc79c3c475/src/interpreter.ts#L715)
I can easily revert this back and just make `forward` supported in both APIs.
> Support autoForward option in spawned actors

- packages/xstate-graph/package-lock.json
- test/types.test.ts
I thought there was a `TypeError` with parallel machines. I tried to replicate the issue by writing two simple tests and was very surprised to see them pass. I then figured that my implementation was off and xstate types fully worked 🎉. I simply forgot to define `states` on the `StateSchema` on one of my machines. 😁 	
I'm not sure how extensive you want to have TypeScript tests but I figured having two more tests can't hurt.
> chore: add two TypeScript tests for parallel machines

- test/utils.ts
It fails when run `npm install`:
```
test/utils.ts:3:30 - error TS2307: Cannot find module '../lib'.
3 import { matchesState } from '../lib';
~~~~~~~~
```
> test: fix build failure

- docs/guides/delays.md
When reading delay docs it seems like Notes section is missing some text.
> Delay docs: remove unnecessary Notes section

- src/interpreter.ts
fixes #521
MachineActor~ has to be typed as `Actor<State<Context>>` instead of `Actor<Context>`
cc @mikaelkaron
> Fix spawn return type for Machines

- src/State.ts
- src/types.ts
- test/state.test.ts
fixes #511 
Not sure if we can do this in this major though. Was `.inert` getter part of the public API?
> Workaround for broken TS getters (important for spreading State)

- packages/xstate-react/CHANGELOG.md
- packages/xstate-react/README.md
options avilability as of version `0.7.0`
Prior Issue: https://github.com/davidkpiano/xstate/issues/558#issuecomment-513241388
> Docs: `xstate/react`: Added clarification on `useMachine` Machine Config

- packages/xstate-immer/src/index.ts
Even though the @xstate/immer package is not released it has failed to compile after recent refactors.
> Remove OmniEventObject usage from @xstate/immer

- packages/xstate-graph/src/graph.ts
This got broken after recent refactors as `toEventObject` has changed its location.
> Fix import path for toEventObject in @xstate/graph

- packages/xstate-graph/src/graph.ts
After investigating the issue more thoroughly I've realized that runtime code was OK - the issue was only about typings. Once I've fixed `transitions` to be typed correctly (by assigning it to a declared variable, as a lookup to the `node.definition.on` results in `any`) the issue with the compilation is fixed.
> Fixed @xstate/graph compilation

- src/interpreter.ts
When an initial state is not passed to `service.start()`, `machine.initialState` is used, which is filled in with a lot of details, particularly a copy of the default `machine.context`.
When an initial state is passed as a `State` object, it is loaded directly, and it is assume that this comes with the desired `.context` value filled in.
But when an initial state is passed as a named state, like `interpret(machine).start("COMMENT_FORM")`, the resulting state has `.context === undefined` because nothing ever sets it. `State.from()`, which handles loading a string state to a full state object, already had an option to attach a context, but it was not used in this case.
Found during https://github.com/davidkpiano/xstate/issues/432
> Preserve default context on start from named state

- src/StateNode.ts
- src/types.ts
Context on StateTransition was only used when initializing with existing/persisted state, this is a special case and thus making it a separate argument for private `resolveTransition` makes IMHO more sense. It's less misleading - previous version led me to believe for a moment that maybe context can be somehow associated with transitions.
> Remove optional context property from StateTransition type

- src/StateNode.ts
- src/stateUtils.ts
- test/after.test.ts
- test/interpreter.test.ts
I believe this had to have more severe consequences than the use case I've fixed in the added test, but don't have enough expertise yet to think of other failing tests I could add quickly.
Maybe you could point me in the right direction? If not I'll probably dig into this at a later point in time.
> Fixed issue with _init not covering nested nodes

- src/interpreter.ts
- src/scheduler.ts
Events might get scheduled (internally by send or externally) when interpreter is initialized and interpreter might reach a final state WHILE processing the event queue.
I think we should just drop unprocessed jobs in such case, otherwise we try to process them when interpreter is in uninitialized state and it starts to warn about it a user.
> Clear scheduled jobs on .stop() call

- src/scxml.ts
followup to #604 , while ofc we can convert `event` to be an `eventexpr` I've thought that it's better to be more precise while converting and thus we should stick to a simple form of `event` when possible
> Refactor event conversion to be more faithful

- docs/guides/communication.md
Add clarifying language about what happens with invoke when the state is changed in the parent machine.
See: https://github.com/davidkpiano/xstate/issues/268#issuecomment-520243978
> Clarify behavior of invoke when machine state changes

- package-lock.json
- packages/xstate-immer/src/index.ts
- src/StateNode.ts
- src/types.ts
- test/assign.test.ts
Seems like support for this can be dropped since https://github.com/davidkpiano/xstate/commit/4c47c510abaa100c49d827fc5589a0804617184a got merged in.
I don't believe this is a breaking change, because it looks like it was only introduced to support `@xstate/immer` but that has not been released yet and its implementation has changed and is no longer using that option. It was also not documented, so it shouldn't break anybody.
> Remove custom updater support

- src/StateNode.ts
- src/actions.ts
- src/types.ts
- test/after.test.ts
Regarding - https://github.com/davidkpiano/xstate/pull/647#discussion_r320881094
I'm not the biggest fan of spreading those things onto existing options, but this technique is used at other places, so the same should be done here.
It has worked with that "bug" because function delay got passed down and later resolveSend knew how to deal with a simple function as it has to deal with them for "regular" send actions with delay as function expression. It has never been found in machine.options as it was never added to it.
> Cleanup where created delayRef gets inserted

- src/StateNode.ts
- src/scxml.ts
- test/actions.test.ts
- test/scxml.test.ts
fixes #679 - this actually was a regression, the issue has popped up in 4.7 (wasn't there in 4.6)
According to SCXML (and enabled test):
> [Definition: The exit set of a transition in configuration C is the set of states that are exited when the transition is taken when the state machine is in C. If the transition does not contain a 'target', its exit set is empty.
> Fix issue with targetless delayed transition reentering current state

- docs/guides/statenodes.md
I had difficulties to digest the paragraph about nested state nodes.
`Substate` is hard to understand for non native english speakers and can be easily misread as `substrate` or the like. `Sub-` as prefix should be easier to read.
Recursion means basically `running back` from its latin meaning. 
This has nothing to do with recursion. It's just a hierachical tree-like structure.
Maybe stating this as `nested state nodes` would also be fine or describing it as a `tree-like structure`.
> Revises description of sub-state node definition

- src/StateNode.ts
- src/scxml.ts
- src/types.ts
- src/utils.ts
- test/deterministic.test.ts
- test/eventDescriptors.test.ts
- test/scxml.test.ts
- test/transient.test.ts
Motivation:
In SCXML document order matters, so i.e.
```
<transition target="pass" event="*"/>
<transition target="fail" event="foo"/>
```
and
```
<transition target="fail" event="foo"/>
<transition target="pass" event="*"/>
```
are **not** equivalent. When sending `foo` event it has to be matched according to that document order.
TODO:
> Support array transition configs

- packages/xstate-fsm/package.json
Allows @xstate/fsm to work with [Pika Web](https://github.com/pikapkg/web) out of the box :D Thanks for the awesome library!
> @xstate/fsm: add types to package.json

- packages/core/package.json
- packages/xstate-fsm/package.json
- packages/xstate-graph/package.json
- packages/xstate-immer/package.json
- packages/xstate-react/package.json
- packages/xstate-scxml/package.json
- packages/xstate-test/package.json
fixes #707
I might revamp build system later to unify (and verify) it across all packages - it's somewhere on my todo list, but not with the highest priority 😉
> Filter out source maps from published files

- packages/xstate-react/src/index.ts
`.initialState` is a getter which fires some work/computations and might cause `assign` actions to be executed (when being part of entry content) which comes really confusing while inspecting what gets executed etc.
> Read initialState when initializing state lazily

- packages/core/src/interpreter.ts
Temporary fix for https://github.com/davidkpiano/xstate/issues/709 that has the quality of:
- adding zero new lines of code
- ~~makes the extension browser adoptable by all XState users without having to use the latest version.~~
> XState DevTools integration: passing the machine config for visualization

- packages/xstate-fsm/package.json
- packages/xstate-fsm/rollup.config.js
Provide rollup-compatible naked esm es5 @xstate/fsm build (like [this](https://github.com/davidkpiano/xstate/commit/c1f094d1695c62ddd0135442c478a9c4006ffb89) commit for core Xstate)
> Provide rollup-compatible esm bundle version for @xstate/fsm

- docs/guides/actors.md
Hello,
It is a small fix to an example in the guide for `Actors` . It seems that the service `todoMachine`should be spawned in a function
> docs : fix example in actors.md

- .github/workflows/nodejs.yml
This is already handled by `actions/setup-node`
> Remove explicit yarn installation on CI

- packages/xstate-react/src/index.ts
- packages/xstate-react/test/useMachine.test.tsx
Prior to this change, if the `immediate: true` option was supplied for `useMachine()` and the service had a transient transition in its initial state, the `onTransition()` handler’s reference to `setCurrent` was `undefined` because `useState()` had not yet been executed to populate it, resulting in a "setCurrent is not a function" runtime error on `service.start()`.
I propose resolving this by splitting up the service creation logic such that the `onTransition()` handler is not added until after `useState()` has been executed and `setCurrent` is defined.
See: #755
> Proposed fix for #755 "setCurrent is not a function"

- packages/xstate-fsm/README.md
The `interpret` function is missing in this import. Used when creating the service.
> Adds missing import for example

- packages/core/src/actions.ts
Should be `to` but is `target` in the doc string.
> Use correct property name for send action options

- packages/xstate-analytics/package.json
- packages/xstate-react/package.json
- yarn.lock
We should always reference our local versions. Gonna add build checks for this in the future, but for now just fixing this.
> chore(deps): Fix packages referencing external versions of monorepoed packages

- packages/xstate-react/README.md
Fix the example in Readme to use the 'getItem' for localstorage when getting the persisted state
> Fix localstorage get to getItem in readme

- tsconfig.base.json
- yarn.lock
fixes https://github.com/davidkpiano/xstate/issues/790
We still want to generate declaration maps - but when we upgrade to TS@3.7 that will probably go away as well.
> fix(build): Stop generating source maps

- packages/core/src/interpreter.ts
`spawn` doesn't support event types being set for the resulting interpreter, so you cannot enforce event types when assigned to context. This PR allows events to be defined or inferred from the machine passed to `spawn`.
> (TS) Support event types for spawn

- packages/core/src/interpreter.ts
- packages/core/test/interpreter.test.ts
if any call to `send()` made `state.changed` true, then all calls afterwards would also be true even if the state didn't actually change.
a codepen example of the existing bug can be found [here](https://codepen.io/afrehner/pen/oNNaQJm) (open the console)
> fixing batch calls for interpreter state machines

- packages/xstate-fsm/src/index.ts
These two objects are the same, so I thought it might be useful to DRY them up into a single object and return that instead. Unsure of its impact on the bundle size.
> DRYs up transition failure into a single object

- packages/xstate-fsm/src/index.ts
In the case where a transition exists with no defined `target` (such as a transition with only actions), then we eventually set that value to `value`, which is the `value` from the state passed into `transition`. We can avoid this with default assignment of `target` to `value` if it's `undefined`.
This handles setting the `nextStateConfig` correctly, and removes the need for the `nextValue` variable.
> Sets default value for target

- docs/guides/communication.md
The [Promise Rejection](https://xstate.js.org/docs/guides/communication.html#invoking-promises) docs have a typo in the `onError` function:
```javascript
onError: {
target: 'failure',
actions: assign({
errorMessage: (context, event) => {
// event is:
// { type: 'error.execution', data: 'No query specified' }
return event.data.message;
}
})
```
The `.message` accessor is not correct. The error string, as specified a few lines above that in English, is the `data` object itself. This PR replaces the last line line of the function with this:
```javascript
return event.data;
```
> docs: remove .message accessor from promise rejection docs

- packages/xstate-react/src/useActor.ts
for some unknown reason, react-native doesn't like passing setCurrent directly to subscribe. This PR propose to add an extra anonymous function to prevent the warning.
> Fix Warning issue related to useActor

- docs/guides/states.md
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/types.ts
- packages/core/test/state.test.ts
- packages/core/test/transient.test.ts
- packages/xstate-graph/test/__snapshots__/graph.test.ts.snap
This PR does 3 things:
- Detects when a machine is "done" internally (`isDone`) and prevents any events from being raised once it is done (according to SCXML spec)
- Raises a null event for a transient transition if the root machine has a transient transition (see #754)
- Test added for this
- Adds `state.done` (enabled from first point) + tests + docs (#328)
> fix(core): raise null events on root object, but only if machine is not "done". Fixes #754

- packages/xstate-react/src/index.ts
relates to https://github.com/davidkpiano/xstate/issues/838
I had no chance to test this properly, it's nearly 1 AM at my place and I have 3% of my battery left 😅 
The idea is to read this lazily in state's initializer and use the computed value from that created state instead of the closure variable which gets recreated each render. Hooks ESLint rule would yell at us here, but we know what we are doing, so 🤷‍♂
> perf(@xstate/react): Avoid excessive .initialState reads in useMachine

- package.json
- packages/core/package.json
- packages/xstate-analytics/package.json
- packages/xstate-fsm/package.json
- packages/xstate-graph/package.json
- packages/xstate-immer/package.json
- packages/xstate-react/package.json
- packages/xstate-scxml/package.json
- packages/xstate-test/package.json
- packages/xstate-viz/example/package.json
- yarn.lock
This unifies dependencies used across the monorepo - we should always strive to have a single version of a particular direct dependency.
Additionally, this introduces a `manypkg check` as postinstall script which is going to validate this from now on.
> chore: Fix duplicated deps, incorrect dep ranges and introduce manypkg check

- packages/core/src/interpreter.ts
Minor optimization. I believe we should remove the possibility of doing this in v5 though - it's better to have explicit methods for both scenarios (send & batch) rather than send also handling both cases.
> refactor: Move batch-check to the top of Interpreter.prototype.send

- packages/core/src/utils.ts
After spending a long time figuring out why my `assign` actions weren't triggered, I thought this warning might be helpful.
> Add warning when attempting to update an undefined context

- docs/packages/xstate-graph/index.md
- packages/xstate-graph/README.md
I changed `json` to `json5` for better syntax highlighting.
> docs: change `json` to `json5`

- docs/guides/actors.md
- docs/guides/communication.md
- packages/core/src/types.ts
- packages/core/test/invoke.test.ts
Just a tiny error: Actor doc refers to callback actor's  2nd argument as `onReceive`, but it is `onEvent` in the linked entry about invoking callback ([link](https://xstate.js.org/docs/guides/communication.html#invoking-callbacks))
> fix(docs): use `onReceive` consistently as callback handler's 2nd argument

- .changeset/rare-pillows-fold.md
- packages/core/src/interpreter.ts
- packages/core/test/interpreter.test.ts
This PR caches `initialState` in the service instead of in the machine (which was problematic but an initial "solution").
> fix(core): cache initial state in interpreter instance. Fixes #838

- .changeset/silent-donkeys-relate.md
- packages/core/src/StateNode.ts
- packages/core/test/after.test.ts
regression caused by #647 
fixes #886
> Fixed issue with delayed transitions scheduling a delayed event for each transition defined for a single delay

- .changeset/moody-buttons-double.md
- packages/xstate-test/src/index.ts
- packages/xstate-test/test/index.test.ts
7f7672e8a67451b7e0c3c4285dd8061decb385e8 introduced a bug where without
a `meta.description`, the test description text is
`reaches state: "undefined"`.
This is because even if `meta.description` is `undefined`,
`"${description}"` becoming `"undefined"` is truthy and the code after
`||` can never be reached.
Also double quoting with `JSON.stringify` was fixed.
See https://github.com/davidkpiano/xstate/commit/7f7672e8a67451b7e0c3c4285dd8061decb385e8#diff-8e162acfb6f0732195f10a5f0592fdb3L325-R332
> Fix description text if no meta description given

- .changeset/orange-fans-retire.md
- packages/xstate-react/src/index.ts
- packages/xstate-react/test/useMachine.test.tsx
I have some more changes planned to `@xstate/react` - don't want to make them all at once so they can be more easily reviewed. Also can't quite make parallel PRs as they would probably conflict with each other quite a bit.
There are not that many of them though - so if we review & merge them at a good pace then we would be able to release v1 of that package in the next week. That being said - it maybe would be a good thing to create a base branch from the master for those changes, so we don't block releasing of other packages while we work on `@xstate/react` (assuming we release things automatically using changesets versioning PRs - because once we merge this to master it will be immediately added to the next release batch).
> Drop immediate option from useMachine

- packages/xstate-react/package.json
Strict package managers (like yarn v2 or pnpm) don't you require/import stuff unspecified in deps/peerDeps - all your dependencies have to be explicitly defined.
This change can result in false positive peer dep warnings during installations done by older package managers (or ones that just don't implement optional peer deps), but if we want to keep both of those in a single package (`@xstate/react`) then this is very much needed.
Not sure about all package managers, but yarn supports optional peer deps for quite some time (but maybe just a few months? not sure, would have to be tracked if this has been added this year or sometime before that) and npm has added this very recently.
> fix: Add optional peer dependency for @xstate/fsm in @xstate/react

- docs/guides/typescript.md
Added missing import for interpret from 'xstate' for the example.
This will enable readers to copy and paste the code and execute without errors.
> Added missing import to typescript.md

- .changeset/eighty-coins-tease.md
- .changeset/pre.json
- .changeset/shy-walls-develop.md
- .changeset/slow-apples-dance.md
- .github/workflows/release.yml
This will allow us to track everything done on `next` branch using changesets and while in the prerelease mode we can automatically release beta versions of xstate@5 to npm (in the very same way as it can be done with changesets when working on the master branch)
> Enter changeset pre mode

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
Our build+test action takes 2min~ so we definitely don't need 6h of a timeout (GitHub's default)
> Add a custom timeout for GitHub actions

- packages/xstate-react/src/index.ts
- packages/xstate-react/src/useConstant.ts
- packages/xstate-react/test/useMachine.test.tsx
⚠️⚠️⚠️Right now this is just an experiment I'd like to gather feedback on ⚠️⚠️⚠️ 
There is this mantra repeated by React team that subscriptions should be done in a commit phase (inside an effect) - mainly because only then we get also an "access" to a cleanup mechanism. And given the React model - this all is true.
Here, however, we don't deal with an external source - but rather we create our own and we own it. So it seems to me that rules are a little bit different for such a scenario. We could even move subscribing to the moment right after calling `.start()` (in render phase). We don't actually need a cleanup phase because we should be able to rely upon GC doing its job when our component unmounts (or doesn't ever get committed) - the source (service) should be shared **only** in its …
> Reimplement useMachine to always start service immediately

- docs/guides/actions.md
There's no `target` property in `options` but a `to`.
> docs: Update actions.md

- packages/xstate-react/src/fsm.ts
fsm-related code should not depend on `xstate` package. The default I have used here seems to follow what is used in most places in `@xstate/fsm` package.
> Remove a reference to xstate type from @xstate/react/fsm

- .changeset/fifty-pears-hammer.md
- packages/xstate-test/README.md
- packages/xstate-test/src/index.ts
- packages/xstate-test/src/types.ts
- packages/xstate-test/test/index.test.ts
This PR introduces options for `testModel.getCoverage(options)` and `testModel.testCoverage(options)`:
```js
// Only test coverage for state nodes with a `.meta` property defined:
testModel.testCoverage({
filter: stateNode => !!stateNode.meta
});
```
Related issue: #718
> @xstate/test: Introduce coverage options

- .github/actions/change-release-intent/action.yml
- .github/actions/change-release-intent/main.js
- .github/workflows/release.yml
- package.json
- yarn.lock
This fixes generating versioning PRs, quite brute-forcefully. I remove some updated files from the commit - keeping only those files which are in releasable packages. 
This is a temporary solution, Im collaborating with Changesets team on a proper one, but in the meantime we should merge this in.
> Change changeset-generated release to prevent some packages from publishing

- .changeset/young-badgers-yawn.md
- packages/xstate-analytics/package.json
- packages/xstate-graph/package.json
- packages/xstate-immer/package.json
- packages/xstate-react/package.json
- packages/xstate-scxml/package.json
- packages/xstate-test/package.json
- packages/xstate-vue/package.json
IntelliJ based IDE's have difficulty trying to find the types unless you use the main path directly. I.E "@xstate/react/lib/index"
This is most likely down to the wording on the typescript publish page. (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
It says "Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.", so given that the types aren't at the root it isn't resolving it.
Adding this in fixes the issue.
> Add `types` field to all package.json's

- .changeset/lazy-windows-tan.md
- packages/core/src/actions.ts
- packages/core/test/invoke.test.ts
This PR adds the ability for `escalate()` to take in an expression, just like `send` or `sendParent`.
> Escalate action with expression

- packages/core/test/types.test.ts
As discussed in https://github.com/davidkpiano/xstate/issues/949, I added a machine with some raise events that throws type errors.
I added comments explaining which ways to type the `raise` event work, and which ones do not.
Pay special attention to the last `raise` event that I had to comment for the test to fail as it removed the type errors from the other raise events. (`actions: raise('NIGHT')`).
Unfortunately, my TypeScript knowledge of generics is too limited to fix the issue or investigate further.
> Add failing type test for raise events

- docs/recipes/vue.md
Add a context property to the machine's definition
Explain that the context can act as a data store and how it can be updated and referenced on the component instance
Move the machine definition to another file to better represent the decoupling between the machine and Vue (like in the react example)
> Update vue guide

- docs/guides/communication.md
makes it clear that responses are only available in version 4.7+
> docs: add version badge to respond section

- .changeset/beige-plants-share.md
- packages/xstate-vue/src/index.ts
- packages/xstate-vue/test/UseMachine-no-extra-options.vue
- packages/xstate-vue/test/useMachine.test.ts
> Fixed issue with `useMachine` crashing without providing optional `options` parameter

- docs/guides/guards.md
The multiple guards example sets the initial context of `alarm` to `false`. After calling `doorService.send('OPEN')` the example says that the state will update to `{ closed: 'error' }`, which is not true unless `alarm` is set to `true` in the original context definition.
This PR updates the documentation to include a `SET_ALARM` action. Alternatively we could just set the context to `true` 🤷‍♂
> Update Multiple Guards example

- .changeset/witty-hounds-invent.md
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/actions.test.ts
- packages/core/test/actor.test.ts
- packages/core/test/interpreter.test.ts
As discussed in https://github.com/davidkpiano/xstate/issues/998 and on Slack
> Removed support for `service.send(type, payload)`

- README.md
This adds a link to @xstate-vue in the README for Vue.js users to find more easily.
I didn't know what emoji to use so I went for what looks most like a V 😀
> docs: add link to @xstate-vue

- packages/xstate-fsm/src/index.ts
Previously the `stop()` method would loop through the transition listeners and delete each one from the Set.
This change simplifies that to using the [Set#clear()][1] method.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/clear
> Use Set#clear() when stopping an interpreter

- packages/core/src/index.ts
- packages/xstate-analytics/src/types.ts
- packages/xstate-fsm/src/index.ts
- tsconfig.base.json
This is in preparation for supporting extra entries like `xstate/invoke`. 
I'm not yet sure if I'm going to actually leverage this mode (but most likely I would like to) - it's not much harmful though so worth to keep anyway as it's going to make it easier to switch transpiling tools. Main downside of this is that it's not possible to just reexport type from a file because of a single-file transpilation not knowing if a particular thing is a type or a runtime value and has to emit it as runtime export (the default). TS 3.8 will improve this situation a little bit by introducing `import type` syntax.
When trying this out I have actually expected that I would have to change way more code to accommodate `isolatedModules` constraints, but it seems that only a single thing had to be changed (a …
> Use isolatedModules TS mode

- .changeset/twelve-tables-tap.md
- packages/core/src/State.ts
`config` had a reference to `.history` and it had managed to "recursively" retain all of the past histories through closures, as we copy the `configuration` onto the `this` anyway the fix was simple - just use a different object to access it.
> Fixed memory leak - `State` objects had been retained in closures

- packages/core/src/invoke.ts
- packages/core/src/scxml.ts
- packages/core/test/scxml.test.ts
Those comments **are not** exhaustive. If we resolve a particular mentioned issue a test in question might still be failing for some other reason - so the comment would have to be adjusted then.
> Annotate failing SCXML tests

- docs/guides/interpretation.md
👋  Noticed that `clock` was missing in the docs, in the interpreter options section:
https://xstate.js.org/docs/guides/interpretation.html#options
I'm aware of https://github.com/davidkpiano/xstate/pull/1037, however this is still valid for the current version. Let me know if it's useful, I set `next` as the target branch but perhaps this is incorrect.
> Document `clock` in the interpreter options

- .changeset/wise-wombats-invite.md
- packages/core/src/stateUtils.ts
- packages/core/test/invalid.test.ts
Followup to https://github.com/davidkpiano/xstate/pull/1041#discussion_r389410440
> Do not try to handle invalid state values in the core

- .changeset/tame-turkeys-live.md
- packages/core/src/types.ts
This PR loosens the `SendAction` type in `Actions` to accept `AnyEventObject`, since the target of the send action might accept different types of events (and can't be easily determined compile-time)
> Loosen types for SendAction. Fixes #570

- .changeset/modern-pumas-applaud.md
- packages/core/src/StateNode.ts
- packages/core/test/final.test.ts
fixes #1079 , cc @RafalFilipek
This shouldnt be a breking change as this incorrecty generated done event had no chance to be caught by the machine (as it has reached the final state it has stopped by then and ignores all events)
> Fixed an issue with data expressions of root's final nodes being called twice

- packages/xstate-react/README.md
The `xstate-react` docs regarding matching states bothers me because it suggests that using a `switch` is not possible with more complex machines, ie hierarchical and parallel, etc. This is not accurate. It simply requires using `switch` in an opposite manner to how it's normally used.
A `switch` evaluates its expression to each case with a strictly equals check `===`. Thus, by making the expression `true`, and each `case` a predicate utilizing `state.matches()`, we can continue to use a `switch` where the result for a `case` is `true === state.matches()`.
This update to the doc demonstrates that pattern.
> docs: demo switch with hierarchical and parallel states for `xstate-react`

- .changeset/good-countries-cross.md
- packages/core/src/StateNode.ts
- packages/core/src/actionTypes.ts
- packages/core/src/actions.ts
- packages/core/src/scxml.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/actions.test.ts
- packages/core/test/scxml.test.ts
- packages/xstate-scxml/test/scxml.test.ts
closes https://github.com/davidkpiano/xstate/issues/990
TODO
> Implement conditional actions

- .changeset/ninety-toys-smile.md
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/test/types.test.ts
- packages/xstate-react/test/types.test.tsx
This fixes issues where the state returned by `useMachine` looses the `TTypestate` information
> Include `TTypestate` for methods

- .changeset/good-countries-cross.md
`decide` has been renamed to `choose` in #1095.
> doc(core): update changeset for decide -> choose renaming

- docs/guides/machines.md
The text below the code referred to the `strict` parameter, which wasn’t present in the code. This small fix adds it to the example.
> Added mentioned ‘strict’ parameter to the code

- packages/xstate-react/README.md
It seems to me that the `current` variable is a typo and should be `state`
> [Docs] Correct variable name in xstate-react example

- .changeset/wise-lemons-travel.md
- packages/xstate-fsm/src/index.ts
- packages/xstate-fsm/src/types.ts
- packages/xstate-fsm/test/fsm.test.ts
The `StateMachine.Config` interface should accept a third generic for our state type, which should then be provided when used in the `createMachine` function. I think. I have declared my own module and haven't had any issues, but if there are any reasons this wasn't set up this way originally let me know.
Using the state type provides helpful intellisense when defining the state chart transitions! 
**NOTE:** I ran tests locally but a bunch of them failed because local modules weren't resolved. Not sure if there is a step missing in `CONTRIBUTING.md` to link these packages.
> Passed state type generic to the Config interface

- .changeset/twenty-weeks-share.md
- .github/actions/change-release-intent/main.js
- docs/README.md
- docs/packages/xstate-react/index.md
- docs/packages/xstate-vue/index.md
- packages/xstate-immer/README.md
- packages/xstate-immer/package.json
- packages/xstate-immer/src/index.ts
- packages/xstate-immer/test/immer.test.ts
- packages/xstate-viz/package.json
- yarn.lock
This PR adds the initial implementation of `@xstate/immer`
```js
import { createMachine, interpret } from 'xstate';
import { assign, createUpdater } from '@xstate/immer';
const levelUpdater = createUpdater('UPDATE_LEVEL', (ctx, level) => {
ctx.level = level;
});
const toggleMachine = createMachine({
id: 'toggle',
context: {
count: 0,
level: 0
},
initial: 'inactive',
states: {
inactive: {
on: {
TOGGLE: {
target: 'active',
// Immutably update context the same "mutable"
// way as you would do with Immer!
actions: assign((ctx) => ctx.count++)
},
// Use the updater for more convenience:
[levelUpdater.type]: {
actions: levelUpdater.action
}
}
},
active: {
on: {
TOGGLE: { target: 'inactive' }
}
}
}
});
const toggleService = interpret(toggleMachine)
.onTransition((state) => { …
```
> @xstate/immer initial release

- docs/packages/xstate-immer/index.md
It looks like the machine is looking for an event with a `type` of `CHANGE_COUNTRY` and value in `value`, but the transition is being called with `UPDATE_COUNTRY` and a value in `country`. I've updated them to match.
Writing code that never runs in docs is hard.
> Fix UPDATE_COUNTRY action type to match

- .changeset/tall-cars-provide.md
- packages/core/src/actions.ts
- packages/core/test/actions.test.ts
> Fixed an issue with `choose` and `pure` not being able to use actions defined in options

- .changeset/grumpy-deers-applaud.md
- packages/core/src/StateNode.ts
- packages/core/src/types.ts
- packages/core/test/json.test.ts
This PR fixes `.toJSON()` for machines containing delayed transitions defined in `after` (and elsewhere).
> Fix toJSON for transitions

- README.md
- Using the new official swapi URL (`https://swapi.dev`)
- Returning data based on received data structure (`res.data` instead of `data.json()`)
- Added an example `.send('FETCH')` call to service
Note: since this is just a readme update, I didn't include a changeset, since I wasn't sure which module to select in the interactive CLI. Happy to go back and do that if you want a changeset included for readme updates. In that case, please let me know which modules I should select in the CLI.
> Updated the promise example

- .changeset/flat-elephants-appear.md
- packages/core/src/State.ts
- packages/core/src/interpreter.ts
I have in my project something like this:
With my fixes I have:
P. S. I have 14 failed tests (cause `error TS2307: Cannot find module 'xstate'.` error) even in master branch without changes. I have no errors while setting up the project through yarn. Could you please help me with setting up the project?
> Fix type inferring mistakes for State

- .changeset/blue-needles-accept.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
This PR fixes the generic types for `send()` and `sendParent()` action creators to accept a third generic type: `TSentEvent`, which represents the event to be sent, which can be (and usually is) different than what the sending machine accepts.
Fixes #711
> Fix types for send() and sendParent()

- docs/tutorials/reddit.md
I found this line confusing
// Use the existing subreddit actor if one doesn't exist
so I propose changing it to:
// Use the existing subreddit actor if one already exists
> Typo: doesn't exist -> already exists (for clarity)

- .changeset/wet-swans-deny.md
- packages/core/src/interpreter.ts
- packages/core/test/interpreter.test.ts
The issue was that when restoring from an initial state, `state.actions` weren't being resolved against the specified `machine.options.actions` action mapping, so actions weren't being executed.
Fixes #1174
> Ensure actions are executed from a restored initial state.

- .changeset/great-toes-vanish.md
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/test/invoke.test.ts
fixes #1180
Problem was that for invoked services `action.activity.type` is always equal to `xstate.invoke` and thus all invoked services were registered/deregistered under the same key in `state.activities`, which led to a problem of an invoked service not being started when another invoked service has been stopped in following microstep because we only start services when machine settles macrostep to avoid starting services unnecessarily.
cc @jschppll
> Fixed an issue with invoked service not being correctly started

- .changeset/seven-gorillas-melt.md
- packages/core/src/Machine.ts
- packages/core/src/State.ts
- packages/core/test/match.test.ts
> Fix resolution to never for state.matches(...)

- docs/guides/typescript.md
Following the discussion in #1195, I've updated the typescript documentation with the following:
- Compound state values inside a typestate should be specified using the object syntax rather than the string syntax.
- Added warning regarding compound states and the need for parent states to be explicitly modelled
- Added example of type state declaration using a type union for the value. This is obviously a typescript feature rather than a feature of xstate itself, however I hadn't considered this pattern prior to your example and it seems this is quite useful to avoid duplication.
I tried to avoid committing the other formatting changes however the post commit hook seemed to force it.
> Add compound state warning to typescript docs

- .changeset/thirty-tomatoes-jump.md
- docs/guides/communication.md
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/invoke.test.ts
The resolved value of the `invoke.data` property is now available in the "invoke meta" object, which is passed as the 3rd argument to the service creator in `options.services`. This will work for all types of invoked services now, including promises, observables, and callbacks. The behavior of `invoke.data` with invoked machines is unchanged.
```js
initial: 'pending',
context: {
id: 42
},
states: {
pending: {
invoke: {
src: 'fetchUser',
data: {
userId: (context) => context.id
},
onDone: 'success'
}
},
success: {
type: 'final'
}
}
},
{
services: {
fetchUser: (ctx, _, { data }) => {
return fetch(`some/api/user/${data.userId}`)
.then(response => response.json());
}
}
}
```
> Pass invoke.data as meta argument to service creators. Closes #529

- docs/packages/xstate-fsm/index.md
Corrected a bug in the xstate/fsm machine.transition() example.  Transitioning from redState to greenState.
Let me know if the changeset is required for this request, thanks!
> xstate-fsm machine transition example update

- docs/packages/xstate-react/index.md
Based on the Type definition, we only support `actions`: https://github.com/davidkpiano/xstate/blob/master/packages/xstate-react/src/fsm.ts#L35
> Documentation: Clarify the XState FSM useMachine hook args

- docs/packages/xstate-vue/index.md
Sorry for the previous pull request. I got too excited and edited the wrong file. Embarrassing. Anyhow, even though the composition API means Vue 3 to those in the know, newer folks might not be aware of this so I clarified in this pull request.
> Docs: clarify code is for Vue 3 (2nd try!)

- .changeset/tiny-guests-wash.md
- packages/xstate-vue/package.json
- packages/xstate-vue/src/fsm.ts
- packages/xstate-vue/src/index.ts
- packages/xstate-vue/test/UseMachine.vue
- packages/xstate-vue/test/UseService.vue
- yarn.lock
- breaking changes in composition-api 0.6.x, so I've adapted the code to conform. This is not backwards compat with previous version of @xstate/vue but peerDependencies have been updated. Luckily the changes are more in-line with Vue 3, so this will make it easier to upgrade to Vue 3 when needed.
- Uses new watcher option since it was changed to be lazy by default
- now using shallow ref since xstate objects should not be refs deeply
> chore(dep/vue) bump peerDep composition-api to 0.6

- .changeset/tidy-feet-occur.md
- docs/guides/transitions.md
- docs/packages/xstate-fsm/index.md
- docs/packages/xstate-react/index.md
- docs/packages/xstate-vue/index.md
- packages/core/src/StateNode.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
- packages/core/test/after.test.ts
- packages/core/test/fixtures/omni.ts
- packages/core/test/guards.test.ts
- packages/core/test/history.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/invoke.test.ts
- packages/core/test/transient.test.ts
- packages/core/test/types.test.ts
This PR adds support for the `always` transition, which works exactly the same as eventless transitions:
```diff
on: {
- '': 'someTarget'
},
+always: 'someTarget'
```
As the tests show, this is not a breaking change. The original way for defining eventless transitions will continue to work.
TODO:
> Add `always`

- packages/xstate-react/package.json
- packages/xstate-react/src/useMachine.ts
- yarn.lock
`use-isomorphic-layout-effect` is a one-liner package **but** it is configured correctly to support browsers, node and React Native environments and as such, I believe it is worth using here - especially that on the `next` branch there is no straightforward way of adding React-Native-only code so far (it's not supported by preconstruct yet)
> Do not use useLayoutEffect directly as it causes server renderer warnings

- .changeset/fluffy-terms-sleep.md
- .changeset/old-dolphins-wink.md
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/xstate-react/src/types.ts
- packages/xstate-scxml/src/index.ts
- yarn.lock
Addresses https://github.com/davidkpiano/xstate/discussions/1261
I still need to write changeset for this but I would like to get feedback first.
1. I've removed all `| any` that I could find because it's like multiplying by 0 - you always get ~0~ any, all other union members are just lost
2. Had to rename `StateNode#data` to `StateNode#doneData` because TS couldn't infer things correctly due to overlapping `.data` properties in both `InvokeConfig` and `StateNode` which are both allowed for `invoke` property. A simplified version of the problem can be checked out [here](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAsghmSAnAPAFQMIHsB2wIAewANFGgKIBuEepaACnEnALYDOUh+OAJhwN4BfAHxQAvFAAUAY2AEAXGWx4upCJUUVqeAJTjRDJqzYAoE9IA2cNhwDKwOPgByWHhHTL8ROlRrBh-FBQJkFgAK4ARhYAltJQPI5wAPyK8I …
> Node data stricter types

- .changeset/mighty-terms-fry.md
- packages/xstate-react/src/index.ts
Make asEffect and asLayoutEffect public (importable). Fixes #1268
> [React] Re-export asEffect and asLayoutEffect

- .changeset/eight-guests-wait.md
- packages/core/src/Actor.ts
- packages/core/src/Machine.ts
- packages/core/src/MachineNode.ts
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/behavior.ts
- packages/core/src/interpreter.ts
- packages/core/src/patterns.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/actions.test.ts
- packages/core/test/machine.test.ts
- packages/core/test/types.test.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-react/test/types.test.tsx
- packages/xstate-vue/src/index.ts
This PR makes the order of `TContext, TEvent, TStateSchema` consistent across the codebase.
> Change order of TContext, TEvent, TStateSchema

- .changeset/real-buses-film.md
- packages/xstate-test/src/types.ts
TestPath interface is not currently exported. Having this type exported is useful when writing tests.
> Export TestPath

- .changeset/light-news-add.md
- docs/packages/xstate-fsm/index.md
- packages/xstate-fsm/src/index.ts
- packages/xstate-fsm/src/types.ts
- packages/xstate-fsm/test/fsm.test.ts
The main `xstate` library provides a lot of functionality, but also quite big in size. For most of the frontend projects, the minimalistic implementation is more than enough. But it is impossible to restore the state of the FSM after page reload. This PR targets to solve this issue.
It also makes it possible to improve `@xstate/react` and rehydrate the FSM state when using `@xstate/fsm`
The solution is inspired by the main library:
Method `start` of the interpreted machine set machine in a state, provided by optional `initialState` parameter.
> [@xstate/fsm] Allow to rehydrate interpreted state machine 

- .changeset/curly-apples-remain.md
- packages/core/src/Actor.ts
- packages/core/src/StateNode.ts
- packages/core/test/transient.test.ts
- packages/xstate-react/test/useMachine.test.tsx
fixes https://github.com/davidkpiano/xstate/issues/1277
This has a caveat though - in a normal situation a service creator is called here:
https://github.com/davidkpiano/xstate/blob/8226700aab94031f66133c6518430786aab4780c/packages/core/src/interpreter.ts#L871-L877
and it is called with different values - `_event` (nor `context`) is not guaranteed to be the same between those 2 points in time. I don't feel this is fixable easily in v4 though.
> Fixed an issue with initial state of invoked machines being read without custom data

- docs/examples/calculator.md
Can we add a react calculator example in the docs? 🤔
This project uses xstate 4.x. I'm still working on the typescript and testing side but the calculator itself is finished.
> Add react Calculator example in the Examples section

- .changeset/light-news-add.md
- .changeset/soft-bulldogs-relax.md
- .changeset/swift-pigs-taste.md
- docs/guides/communication.md
- packages/core/package.json
- packages/core/src/Actor.ts
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/invokeUtils.ts
- packages/core/src/machine.schema.json
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/invoke.test.ts
- packages/core/test/json.test.ts
- yarn.lock
This PR adds support for invoke source objects. This is not a breaking change; `src: 'someString'` will continue to work.
```js
invoke: {
src: {
type: 'search',
endpoint: 'google.com'
},
// ...
}
// ...
services: {
search: (ctx, e, { src }) => {
console.log(src);
// => { type: 'search', endpoint: 'google.com' }
}
}
// ...
```
TODO:
> Add support for invoke source object

- docs/.vuepress/config.js
- docs/examples/covid-tracker.md
I went through the `Example` section of the XState documentation and it doesn't have an example regards of using XState to fetch data from the API, so I just add this example to demonstrate how fetching data should be done using XState and pass down to its descendant using React Context API
> add covid tracker example to the xstate doc

- docs/tutorials/reddit.md
until the line 409
subreddit is just string not object, so doesn't have id inside it.
> fix react component key prop

- .changeset/gentle-vans-visit.md
- .changeset/polite-goats-peel.md
- .changeset/ten-phones-trade.md
- packages/core/src/Machine.ts
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/types.test.ts
- packages/xstate-fsm/src/index.ts
- packages/xstate-fsm/src/types.ts
- packages/xstate-react/src/fsm.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-vue/src/fsm.ts
- packages/xstate-vue/src/index.ts
Fixes https://github.com/davidkpiano/xstate/issues/1301
I've unified this across the codebase. I have one problem though:
The search&replace hit `@xstate/fsm` as well and while reviewing applied changes I've noticed that its `.matches` implementation is different than what is in the core, so I've decided to just unify both (it's not yet part of this PR, but can be seen [here](https://github.com/davidkpiano/xstate/commit/98bbf9b3ceb35bf04aacba97b9ee1244acf66dfa)). I have wanted to confirm that this has indeed fixed something so I could write a proper changeset so I've looked into [the latest `.matches`-related PR](https://github.com/davidkpiano/xstate/pull/1189/files) to check out tests that have been added there and... given the same test (but using `@xstate/fsm`) I can't get it working …
> Unified declarations with TTypestate

- packages/core/src/StateNode.ts
- packages/core/test/types.test.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/test/useMachine.test.tsx
This PR fixes #1334 (in a workaround-ish way) by always reading the `machine.initialState` first, which will trigger `machine._init()` to properly initialize all transitions, which includes resolving delayed transitions.
The real fix for this is to do the transition resolution eagerly in the machine's constructor after adding all state nodes, but this would be a breaking change in v4 for state node getters (which will be deprecated in v5), so that will wait til the next major version.
This is not a breaking change.
> [@xstate/react] Rehydration should initialize machine first. Fixes #1334

- .changeset/nine-gorillas-brake.md
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
Hi. Ran into a typing problem when using `MachineConfig`. The following code does not compile in TypeScript with `"strict": true`
```typescript
type TestContext = {};
type TestEvent =
| { type: 'EVENT_WITH_PAYLOAD'; payload: string }
| { type: 'OTHER_EVENT_WITH_PAYLOAD'; payload: number };
const services = {
testService: (_context: TestContext, _event: TestEvent) => Promise.resolve(),
testService2: (_context: TestContext, _event: TestEvent) => Promise.resolve(),
};
const partialMachineOptions: Partial<MachineOptions<TestContext, TestEvent>> = {
services, 
// Type ... is not assignable to type 'Record<string, ServiceConfig<TestContext, AnyEventObject>>'
// ...
// Types of parameters '_event' and 'event' are incompatible. 
// Type 'AnyEventObject' is not assignable to type 'TestEvent'.
}; …
```
> fix: use event generic in ServiceConfig type

- .changeset/modern-mugs-lie.md
- packages/xstate-fsm/src/types.ts
Fixes typing of value in State interface 
I was using an enum for the states and discovered that the `value` is still strings no matter what
```ts
export enum States {
flow = 'flow',
search = 'search',
default = 'default',
}
type HeaderState =
| {
value: States.flow
context:{
}
| {
value: States.search
context: {}
}
| {
value: States.default
context: {}
}
const machine = createMachine<HeaderMachineContext, HeaderEvents, HeaderState>(...)
...
machineState.value // the type should be `States` instead of `string`
```
> updated State interface value type

- .changeset/ten-seahorses-smile.md
- packages/core/src/types.ts
Consider the following schema:
type LightStateSchema = {
states: {
green: {},
yellow: {},
red: {
states: {
walk: {},
wait: {},
stop: {},
},
},
},
}
The current implementation of the ExtractStateValue type generates the
following type:
{
green?: {} | undefined
yellow?: {} | undefined
red?: "walk" | "wait" | "stop" | {
walk?: {} | undefined
wait?: {} | undefined
stop?: {} | undefined
} | undefined
}
This does not describe the StateValue of LightStateSchema as provided
in State.value.
The new implementation generates the following type:
"green" | "yellow" | "red" | {
red?: "walk" | "wait" | "stop" | undefined
}
> fix(core): fix type ExtractStateValue to describe real state value

- .changeset/nervous-shoes-retire.md
- packages/core/src/interpreter.ts
Currently, the code of the interpreter assumes that the code runs either in the browser's main thread (`window` is defined) or in node. This PR allows it to run in a web-worker, in which the _global_ is `self`
> allow running xstate in a web-worker

- docs/guides/communication.md
Updates the documentation related to promise rejection to align with changes from https://github.com/davidkpiano/xstate/pull/461.
> Update event name reference in docs

- docs/recipes/ember.md
This updates the Ember.js recipe to mention [ember-statecharts](https://ember-statecharts.com). The addon has existed for multiple years now and sees quite a lot of usage in the Ember.js ecosystem when looking at the stats from [emberobserver](https://emberobserver.com/addons/ember-statecharts) - it's in the 10% most downloaded Ember.js addons.
Using the addon also makes it much easier to use XState with Ember.js in general and writing your own integration layer will just be more work than installing the addon - especially if you want to come up with a nice api.
ember-statecharts mostly follows what xstate/react and xstate/vue are doing - i.e. it provides a `useMachine`-api that will create an interpreter for you that you can then use directly in your application code.
> Update Ember.js recipe

- packages/xstate-react/package.json
My original motivation for this pull request was to get `@xstate/react` to play nicely with Snowpack by just adding an ESM build for this particular package.
While doing so, however, I found that there is a wide range of different build setups for all the packages in this repository and was wondering if it might make sense to unify that setup in one sweeping change instead.
As `tsdx` is already used in one package and I personally also use this for my own libraries I went with that but am also open for other options.
Would you be open to accepting a pull request that reconfigures the entire repository more broadly to use tsdx throughout instead of typescript project reference builds. I'd also suggest to move the dependencies to each package individually as well as the jest runtime and …
> chore: use tsdx to build @xstate/react

- docs/guides/context.md
I was just playing around `xstate` with examples and saw a warning which said `''` deprecated and use `always` instead. I saw also in others, If it's useful then I can change them too.
Thanks
> used always stead of ''

- .changeset/poor-flowers-end.md
- .changeset/thin-teachers-approve.md
- packages/core/src/index.ts
- packages/core/src/interpreter.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-react/test/useService.test.tsx
> Fixed issue with `useService` returning an initial state for services in their final states

- docs/.vuepress/config.js
I think you mentioned you wanted to move Xstate specific non-bug-report conversations to [here](https://github.com/davidkpiano/xstate/discussions)?
Besides, Spectrum is flaky lately.
> move Community to Github-Discussions

- docs/guides/final.md
I had to build a mini-prototype to figure out that final substates a parallel state aren't really final until all parallel zones are final. Maybe this note can save someone else 15 minutes 😸
> Describe when final isn't really final yet

- docs/guides/machines.md
It looks like `delays` was missing from the options docs.
- add link to delays docs
- add delays to example option code
- update total to 5
- add delays description
\*Inserted in alphabetical order position.
Please let me know if I made any mistakes. Just trying to help document this great tool :)
> Add delays to options documentation

- docs/guides/context.md
* Adds a missing comma to fix a syntax error in the first code block.
* Changes the `nextState.context` to properly show "amount" instead of "count"
> [docs] Update context.md

- .changeset/funny-spiders-push.md
- packages/core/src/interpreter.ts
- packages/core/test/interpreter.test.ts
- packages/xstate-react/src/useMachine.ts
This PR ensures that all actors (spawned/invoked) are represented in `state.children`.
> Ensure spawned actors are present in state.children. Fixes #795

- packages/core/LICENSE
- packages/xstate-analytics/LICENSE
- packages/xstate-dev/LICENSE
- packages/xstate-fsm/LICENSE
- packages/xstate-graph/LICENSE
- packages/xstate-immer/LICENSE
- packages/xstate-react/LICENSE
- packages/xstate-scxml/LICENSE
- packages/xstate-test/LICENSE
- packages/xstate-vue/LICENSE
closes https://github.com/davidkpiano/xstate/issues/1557
Here's the result of `npm publish --dry-run`:
> include license for packages

- .changeset/chatty-wombats-worry.md
- packages/core/src/interpreter.ts
- packages/core/test/actions.test.ts
This PR fixes #1109 by executing exit actions when an invoked machine reaches its final state.
> Ensure exit actions are called for finalized invoked machines. Fixes #1109

- packages/xstate-test/README.md
This tripped me up before and caused me to spend a few hours debugging @xstate/test and my tests to determine why it seemed like tests were being run for the wrong state.
Turns out that @xstate/test executes not just the `meta.test` for the current state, but also all the parent states of the current state. Seems like a good thing to note in the docs as it's not immediately obvious (but makes sense now in retrospect).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/davidkpiano/xstate/1535)
> docs(xstate-test): add note about nested states

- .changeset/cyan-pants-walk.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/deep.test.ts
- packages/core/test/interpreter.test.ts
- packages/xstate-scxml/src/index.ts
This PR allows expressions to be used in the `stop()` action creator:
```js
actions: stop(context => context.someActor)
```
This should be the way to stop spawned and invoked actors (as well as activities in v4, which are going away in v5 in favor of invoked actors). 
- Replaces https://github.com/davidkpiano/xstate/pull/1559
- Related: https://github.com/davidkpiano/xstate/pull/1434 (will need to be updated)
> Make stop() accept an expression. Fixes #1457

- docs/guides/communication.md
There seems to be a bug in vuepress https://github.com/vuejs/vuepress/issues/2679 stopping markdown from rendering when `Badge` is used in the beginning of paragraph:
https://xstate.js.org/docs/guides/communication.html#the-invoke-property
As it might take some time for them to fix it, I've moved the `Badge` to the middle to work around the issue at the moment.
> move Badge away from beginning

- .changeset/khaki-rivers-move.md
- .changeset/lemon-rings-kick.md
- packages/core/src/types.ts
- packages/xstate-react/src/types.ts
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-react/test/useActor.test.tsx
- packages/xstate-react/test/useMachine.test.tsx
- packages/xstate-react/test/useService.test.tsx
This PR makes `send` from the `useActor(...)` hook stable.
Reference: https://spectrum.chat/statecharts/general/xstate-react-1-0-0-breaking-changes~5ce72da1-871f-4ea4-9f70-40680bf02027
> [@xstate/react] Stabilize `send` from useActor

- docs/README.md
as discussed in #1311 
This also aligns the package description with what is written in [github readme](https://github.com/davidkpiano/xstate/tree/master/packages/xstate-test#xstatetest) and <https://xstate.js.org/docs/packages/xstate-test/> (which looks like the first is the source for the latter).
~PS: I'm not sure about creating a changeset for this PR, just created it from the browser. If this is needed please let me know.~ From the message from changeset-bot I would assume this doesn't need a changeset.
> docs: Clarify scope of @xstate/test

- docs/guides/actions.md
ref: https://spectrum.chat/statecharts/general/trying-to-understand-the-semantic-difference-between-send-and-raise~54667586-2cd2-4433-908d-a65d58b0979c
I was confused also until I made a demo with different paths.
> Improve Raise event example

- docs/guides/transitions.md
Documentation about eventless transitions is extended. The order of guard evaluation and action execution is described in more detail. The fact that eventless transitions are checked with both internal and external transition events is highlighted. More information on when an infinite loop may occur is added.
This docs update summarizes the analysis done in #1592 .
> Docs eventless transitions

- docs/guides/communication.md
I spend a couple of hours trying to get autoForwarding to work on a callback.
It works with forwardTo, though when just quickly trying to prototype a behavior, autoForward comes in handy.
So I thought I am doing something wrong, and keept trying, until I found issue #1112, where it is clearly stated by @davidkpiano that indeed, at the moment it works only for machines. 
So I thought it might be helpful to state it in the docs.
It might save some time of other developers.
Best
Evangelos
> autoForward for machines only (see issue: #1112)

- packages/core/src/types.ts
- packages/core/test/meta.test.ts
This PR just adds a test for `transition.meta`. No behavior changed.
> Add test for transition meta

- .changeset/poor-bugs-reflect.md
- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/types.ts
- packages/xstate-graph/test/graph.test.ts
Options passed into graph functions (e.g., `getShortestPaths(machine, options)`) can now resolve `.events` based on the `state`:
```js
const countMachine = createMachine({
initial: 'active',
context: {
count: 0
},
states: {
active: {
on: {
ADD: {
actions: assign({
count: (context, event) => {
return context.count + event.value;
}
})
}
}
}
}
});
const shortestPaths = getShortestPaths(countMachine, {
events: {
ADD: (state) => {
// contrived example: if `context.count` is >= 10, increment by 10
return state.context.count >= 10
? [{ type: 'ADD', value: 10 }]
: [{ type: 'ADD', value: 1 }];
}
}
});
// The keys to the shortest paths will look like:
// "active" | { count: 0 }
// "active" | { count: 1 }
// "active" | { count: 2 }
// ...
// "active" | { count: 10 }
// "active" | { count: 20 }
// …
```
> [@xstate/graph] Add ability to resolve events from state

- .changeset/chatty-monkeys-nail.md
- packages/core/src/StateNode.ts
- packages/core/test/id.test.ts
- packages/core/test/machine.test.ts
> [v5] Throw error if initial state is not specified. Fixes #674

- README.md
Using GitHub discussions is encouraged instead.
> Remove Gitter chat link

- .changeset/little-bugs-begin.md
- packages/core/src/StateNode.ts
- packages/core/test/history.test.ts
- packages/xstate-graph/test/__snapshots__/graph.test.ts.snap
fixes #1691 
Updating `historyValue` is done within [`exitStates`](https://www.w3.org/TR/scxml/#exitStates) procedure which is part of the [`microstep`](https://www.w3.org/TR/scxml/#microstep) procedure so this should always keep the very latest resolved values and nothing should be "preserved" from older states.
> Fix history state entering after transient transitions

- .changeset/tall-apes-tickle.md
- packages/core/src/interpreter.ts
> Preserve global context with `clock` methods (`setTimeout`/`clearTimeout`)

- jest.config.js
- packages/core/src/devTools.ts
- packages/xstate-inspect/package.json
- packages/xstate-inspect/src/index.ts
- packages/xstate-inspect/test/inspect.test.ts
- yarn.lock
This PR fixes stringifying circular reference in `@xstate/inspect` by using [fast-safe-stringify](https://www.npmjs.com/package/fast-safe-stringify) when normal `JSON.stringify(...)` throws.
Currently, this will result in the string `"[Circular]"` in the inspect UI, which is much better than completely failing (previous behavior):
Fixes #1497
> [@xstate/inspect] Handle circular references gracefully in inspector.

- .changeset/purple-papayas-begin.md
- packages/xstate-inspect/test/inspect.test.ts
This PR adds a changeset for adding `fast-safe-stringify`, as well as an additional test for events with circular structures.
The changeset was omitted in https://github.com/davidkpiano/xstate/pull/1699 (oops), so I'm using this PR to trigger a release.
> [@xstate/inspect] Add changeset for stringify fix

- docs/guides/testing.md
Fixes an issue in the guides where `machine` was used in a test, instead of the imported `lightMachine`.
Issue: https://github.com/davidkpiano/xstate/issues/1724
> Use `lightMachine` instead of `machine` in testing example

- .changeset/proud-clouds-explain.md
- packages/xstate-react/README.md
- packages/xstate-react/package.json
- packages/xstate-react/rollup.config.js
The pull request is based on #1108. 
The pull request should close the following issue: https://github.com/davidkpiano/xstate/issues/1736
> Add UMD bundle for @xstate/react.

- .changeset/pretty-hotels-rush.md
- packages/xstate-react/package.json
- packages/xstate-react/rollup.config.js
- yarn.lock
package: `@xstate/react`
Parent pull request: https://github.com/davidkpiano/xstate/pull/1738
Issue: 
If someone import: https://unpkg.com/@xstate/react@1.2.0/dist/xstate-react.umd.min.js. The import throws the following error: `ReferenceError: process is not defined`
The current patch uses `rollup-replace` to remove the unnecessary variable: `process`.
> Patch: ReferenceError: process is not defined

- .changeset/thin-ads-obey.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/scxml.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/eventDescriptors.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/scxml.test.ts
- yarn.lock
This PR adds support for prefix matching with wildcards (and without wildcards for SCXML machines only):
```js
// ...
on: {
// This transition accepts event types like:
// "mouse", "mouse.click", "mouse.move.out", etc.
// but not events like "mouseclick"
'mouse.*': {/* ... */}
}
});
```
https://github.com/davidkpiano/xstate/projects/1#card-52117183
> [v5] Add support for partial wildcards (prefix matching)

- .changeset/quick-pets-collect.md
- packages/core/src/StateNode.ts
- packages/core/test/machine.test.ts
fixes https://github.com/davidkpiano/xstate/issues/1814
> `machine.resolveState(state)` calls should resolve to the correct value of `.done` property now

- .changeset/eighty-chefs-return.md
- .changeset/rotten-rivers-wonder.md
- docs/packages/xstate-react/index.md
- docs/packages/xstate-vue/index.md
- packages/core/src/Machine.ts
- packages/core/src/MachineNode.ts
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/src/invoke.ts
- packages/core/src/types.ts
- packages/core/test/activities.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/invoke.test.ts
- packages/core/test/machine.test.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-vue/src/index.ts
- packages/xstate-vue/test/UseMachine.vue
Reference: https://github.com/davidkpiano/xstate/projects/1#card-40598347
This PR also renames `options.behaviors` to `options.actors`, as previously discussed.
> [v5] Rename machine.withConfig(...) to machine.provide(...)

- .changeset/breezy-beds-trade.md
- packages/core/src/Actor.ts
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/devTools.ts
- packages/core/src/interpreter.ts
- packages/core/src/serviceScope.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/match.test.ts
reported on Discord: https://discord.com/channels/795785288994652170/799416943324823592/801198150894223411
> Improved `.matches(value)` inference for typestates containing union types as values

- docs/packages/xstate-inspect/index.md
It was pointing to TS template.
> fix @xstate/inspect JS link

- .changeset/afraid-eggs-wonder.md
- packages/xstate-fsm/src/index.ts
- packages/xstate-fsm/test/fsm.test.ts
This PR adds support for transitions with `undefined` targets, which will not exit/re-enter the state.
```js
// ...
someState: {
entry: [/* ... */],
exit: [/* ... */],
on: {
SOME_EVENT: {
// undefined target - will not exit/re-enter
actions: [/* ... */]
}
}
}
// ...
```
> [@xstate/fsm] Add support for targetless transitions

- .changeset/clean-walls-breathe.md
- packages/core/src/interpreter.ts
- packages/core/test/interpreter.test.ts
> Do not crash when stopping already stopped interpreter. 

- README.md
- docs/.vuepress/config.js
- docs/README.md
- docs/about/goals.md
- packages/core/README.md
Either notice Discussions is for XState, not Spectrum or switch Gitter to Discord.
However I can **not** find the source for https://xstate.js.org/  Someone how has access to the landing page source needs to change it please.
> Move links to GH/Discussions & Discord

- .changeset/tall-olives-shop.md
- packages/xstate-test/src/index.ts
- packages/xstate-test/test/index.test.ts
Fixes an issue where `'final'` state nodes were not showing up in the test plan description. For example, given the state node `success: { type: 'final' }`, the description was
```
reaches states:  ({ some_context_val: 0 })
```
The description is now:
```
reaches state: "success"  ({ some_context_val: 0 })
```
> Fixes 'final' state node names not showing in test plan description

- packages/xstate-react/README.md
- packages/xstate-react/src/useSelector.ts
This PR adds documentation for `useInterpret` and `useSelector` hooks.
> [@xstate/react] useInterpret + useSelector documentation

- .changeset/fifty-bears-smash.md
- packages/xstate-react/src/fsm.ts
- packages/xstate-react/test/useMachine-fsm.test.tsx
This PR stems from the discussion I started here: https://github.com/davidkpiano/xstate/discussions/1944.
I was able to create a failing test and I confirmed that passing the Typestate to the returned service from `useMachine` fixes the issue.
> add typestate type to service returned from react/fsm useMachine

- .changeset/unlucky-schools-arrive.md
- packages/xstate-react/src/useInterpret.ts
I haven't tested this in full but it should fix the reported problem.
Fixes https://github.com/davidkpiano/xstate/issues/1948
> Fixed @xstate/react UMD build by redeclaring toObserver

- docs/guides/actions.md
Adds the missing "https://" protocol to a W3 link.
This is huge.
> docs: fix external link target

- packages/xstate-react/test/useMachine.test.tsx
- packages/xstate-react/test/useService.test.tsx
All the other generics have defaults so using this:
```ts
createMachine<any>({})
```
has been caught by the first overload (the Model-related one) and resulted in this:
which in turn has caused some TS error down the road when accessing the `context` which got inferred to unknown: https://github.com/davidkpiano/xstate/pull/1955/checks?check_run_id=2104765685#step:6:1150
> Fixed type errors in tests after introducing createMachine's overload related to Model

- .changeset/fair-lemons-cross.md
- docs/about/resources.md
- packages/core/src/Machine.ts
- packages/core/src/model.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/model.test.ts
Making this PR to discuss and see how we can improve this. This PR provides type inference for **events** in `createModel()` that are specified as "event creators":
```ts
const userModel = createModel(
{
name: 'David',
age: 30
},
{
updateName: (value: string) => ({ value }),
updateAge: (value: number) => ({ value }),
anotherEvent: () => ({})
}
);
// Example of an externally-defined assign action
const assignName = userModel.assign(
{
name: (_, event) => {
return event.value;
}
},
'updateName'
);
const machine = createMachine<
typeof userModel['types']['context'],
typeof userModel['types']['events']
>({
context: userModel.initialContext,
initial: 'active',
states: {
active: {
on: {
updateName: {
actions: assignName
},
updateAge: {
actions: userModel.assign((_, e) => {
return {
age: e.value …
```
> [core] Modeling events with createModel()

- packages/core/src/stateUtils.ts
I've wasted a little bit of time on this when writing a new test on the `next` branch. This would help me to spot the problem much sooner and should result in the same for a good chunk of our users :)
> Throw an error when we encounter cond on a transition to surface this migration problem early

- packages/core/test/invoke.test.ts
The bug is caused by too simplistic logic here:
https://github.com/davidkpiano/xstate/blob/421f85e3bcbfe045ab98bf9f84b84a800b996926/packages/core/src/invoke.ts#L116-L124
Maybe instead of querying actions, we should bookkeep soon-to-be-started actors in the temporary structure (like SCXML does it)?
> Add a failing test for invoked actor not being started correctly when reentering invoking state in the same macrostep

- .changeset/chilled-windows-destroy.md
- packages/core/src/StateNode.ts
- packages/core/src/index.ts
- packages/core/src/schema.ts
- packages/core/src/types.ts
- packages/core/test/schema.test.ts
This PR adds the `schema` property to the machine config and definition.
```ts
// ...
schema: {
// These can be arbitrary meta data, accessible at runtime
// Typecast these (something as SpecificType) for inferred types!
context: someContextSchema,
events: someEventSchemaMap,
actions: someActionSchemaMap,
guards: someGuardSchemaMap,
services: someServiceSchemaMap
},
// ...
});
```
Purpose of this PR:
- Provides a place to specify important metadata for runtime types and validation (e.g., with JSON Schema) as part of the machine definition
- Allows for easier type inference without having to specify generics. Notice how the `context` and `events` are strongly typed, even though their generic types aren't specified:
> [core] Add schema

- packages/xstate-vue/README.md
Hi again!
I've updated the Vue docs, so they have the latest hooks from #1991.
I've also added:
- A table of contents with doctoc at the top as @xstate/react has.
- Added the missing Configuring Machines from #1973 PR that was done only to the docs folder and is deleted when building the project.
- Fixed the Vue links so they point to the latest Vue v3 docs.
> [@xstate/vue] Update Docs: Add new useActor & useInterpret Hooks + Fixes

- .changeset/funny-kiwis-explode.md
- packages/core/src/model.ts
- packages/core/test/model.test.ts
addresses the issue mentioned [here](https://github.com/davidkpiano/xstate/issues/2036#issuecomment-806943242)
cc @VanTanev
> Fixed an issue with creatorless models not being correctly matched by  `createMachine`'s overload

- .changeset/healthy-rice-shout.md
- packages/xstate-react/README.md
- packages/xstate-react/fsm/package.json
- packages/xstate-react/package.json
Thank you for the library and thank you again for providing a bare minimum implementation for it.
However, the recommended way to use `react/lib/fsm` is something I would like to improve, and make it just `react/fsm`, with autopicking the correct implementation for the correct environment.
Not using fancy `package.exports` - adding separate entrypoint in an old fashion way, compatible with completely everything.
Long story short -
```diff
- import { useMachine } from `@xstate/react/lib/fsm`;
- import { useMachine } from `@xstate/react/es/fsm`;
+ import { useMachine } from `@xstate/react/fsm`;
```
> exposing react/fsm as a separate entrypoint

- CONTRIBUTING.md
This is something small, but it bit me when I first tried to do local changes to xstate.
`yarn dev` also will perform a build and make standalone `yarn test` work, but stating it explicitly like this seems most straightforward.
> Clarify that tests will fail unless "yarn build" has been ran

- packages/core/src/Machine.ts
- packages/core/src/State.ts
- packages/core/test/machine.test.ts
Related to the discussion here: https://github.com/davidkpiano/xstate/pull/2060/files#r606933468
I could not find a reason behind those overloads - maybe they were needed at some point in time but they are not anymore? Tests and typecheck are ✅ so I think this should be good to go. If those overloads are needed then we should add tests to cover that.
> Drop unnecessary overloads from createMachine and State.from

- .changeset/hot-pumas-chew.md
- docs/packages/xstate-inspect/index.md
- packages/core/src/devTools.ts
> Allow devTools usage in production

- .changeset/six-chicken-call.md
- packages/core/src/StateNode.ts
- packages/core/test/initial.test.ts
- packages/core/test/machine.test.ts
This PR adds support for combinatorial machines:
- No `initial` property
- No `state` property
- Root-level transitions
```js
const testMachine = createMachine({
context: { value: 42 },
on: {
INC: {
actions: assign({ value: (ctx) => ctx.value + 1 })
}
}
});
```
The finite `state.value` of the combinatorial machine is an empty object: `{}`
> Add support for single-state (combinatorial) machines

- docs/guides/guards.md
The behaviour is expected and it can be implied from the following
sentence in the Hierarchical State Nodes documentation:
> When a simple state does not handle an event, that event is propagated
> up to its parent state to be handled.
This commit explicitly documents the behaviour in the context of Guarded
Transitions.
> Document event propagation for falsy substate guards

- .changeset/fifty-owls-check.md
- packages/core/src/types.ts
Add the convenience type
```typescript
export type InterpreterFrom<
T extends StateMachine<any, any, any, any>
> = T extends StateMachine<
infer TContext,
infer TStateSchema,
infer TEvent,
infer TTypestate
>
? Interpreter<TContext, TStateSchema, TEvent, TTypestate>
: never;
```
This is useful in the following pattern:
```typescript
import React from 'react'
import { createMachine, InterpreterFrom } from 'xstate'
import { useService } from '@xstate/react'
const machine = createMachine(...)
type MachineService = InterpreterFrom<typeof machine>
const MachineServiceContext = React.createContext<MachineService>(null!)
const useMachineService = (): MachineService  => {
const service = React.useContext(MachineServiceContext)
if (!service) throw new Error(`You must call useMachineService in a …
```
> Provide convenience type InterpreterFrom<typeof machine>

- .changeset/eighty-fishes-smoke.md
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/src/useReactEffectActions.ts
This PR fixes a circular dep that `executeEffect` caused, which is an internal function that shouldn't be exported anyway.
> [@xstate/react] Fix circular dependency

- .changeset/stupid-windows-sniff.md
- packages/core/src/types.ts
```typescript
type Event = { type: 'START' } | { type: 'STOP' }
const machine = createMachine<{}, Event>({
invoke: {
id: 'callback-service',
src: () => (callback, onReceive) => {
onReceive(event => {
// event is { type: 'START' } | { type: 'STOP' }
})
callback({ type: 'I_DONT_EXIST' }) // type errors
}
}
})
```
> Improve the type of callback invoke params

- docs/recipes/stencil.md
The "componentDidUnload()" method was removed in Stencil 2. The "disconnectedCallback()" method should be used instead.
> Change componentDidUnload to disconnectedCallback

- .changeset/soft-cats-trade.md
- packages/core/src/StateNode.ts
- packages/core/test/tags.test.ts
Fixes https://github.com/davidkpiano/xstate/issues/2172
When we don't select any transitions then we just return here:
https://github.com/davidkpiano/xstate/blob/64ab1150e0a383202f4af1d586b28e081009c929/packages/core/src/StateNode.ts#L1280-L1282
but tags are set later on, here:
https://github.com/davidkpiano/xstate/blob/64ab1150e0a383202f4af1d586b28e081009c929/packages/core/src/StateNode.ts#L1328-L1330
So this didn't have a chance to be set correctly for the fixed test case.
> Fixed an issue with tags not being set correctly after sending an event to a machine that didn't result in selecting any transitions

- .changeset/pretty-beans-pretend.md
- packages/core/src/Machine.ts
- packages/core/src/MachineNode.ts
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/src/patterns.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/xstate-react/src/useInterpret.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/src/useReactEffectActions.ts
- packages/xstate-react/src/useSelector.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-react/test/useMachine.test.tsx
- packages/xstate-scxml/src/index.ts
- packages/xstate-svelte/src/index.ts
- packages/xstate-test/src/types.ts
- packages/xstate-vue/src/useInterpret.ts
- packages/xstate-vue/src/useMachine.ts
- packages/xstate-vue/src/useService.ts
This PR removes `StateSchema` from all types in v5. We'll figure out a better way to have strong typing of state keys, but this is the first step.
> [v5] Remove `StateSchema`

- package.json
- patches/@vue+runtime-dom+3.0.11.patch
- yarn.lock
It should fix the problem temporarily - so far I couldn't spot any problems with the solution as we don't use JSX with Vue anywhere but maybe it can also somehow affect the content of the `<template>`. Since we don't need typechecking that much in there anyway... it should mostly be fine to just remove this.
> Fixed the typecheck script by removing conflicting JSX namespace

- docs/guides/typescript.md
Does not seem like `createMachineConfig` exists anywhere
> [docs] Replace createMachineConfig with MachineConfig

- docs/packages/xstate-vue/index.md
- docs/recipes/vue.md
This PR adds a link to [xstate-vue2](https://github.com/ChrisShank/xstate-vue2).
Addresses https://github.com/davidkpiano/xstate/discussions/2193
cc. @chrisshank
> [docs] Add links to xstate-vue2

- .changeset/neat-boxes-float.md
- packages/core/src/Actor.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/actor.test.ts
- packages/xstate-inspect/src/browser.ts
This PR adds the `.getSnapshot()` method, which allows you to synchronously retrieve the latest value emitted from that actor. That value may be `undefined` if no value has been emitted yet.
This is the first step in full actor persistence, since persisting the state of a machine at a specific point in time involves synchronously reading the "state" (really the last known emitted values) of each actor.
```js
context: {
promiseRef: null
},
initial: 'pending',
states: {
pending: {
entry: assign({
promiseRef: () => spawn(fetch(/* ... */), 'some-promise')
})
}
}
});
const service = interpret(machine)
.onTransition((state) => {
// Read promise value synchronously
const resolvedValue = state.context.promiseRef?.getSnapshot();
// => undefined (if promise not …
```
> [core] Add `.getSnapshot()` to actor refs

- examples/fetch/package.json
This got accidentally published to npm and this flag should prevent it in the future.
> Mark @xstate/examples-fetch as private

- docs/.vuepress/config.js
This PR sets `docsBranch` to `'main'` so that the edit links work on the documentation pages.
Fixes #2219
> [docs] Fix edit link

- docs/guides/transitions.md
This PR fixes the `target: 'justify'` root transition in the docs to fix #346
> [docs] Fix root-level transition

- CONTRIBUTING.md
All the time (myself included) we change the `/docs/packages/PACKAGE/index.md` file but later is overriden on build, as it's copied from `packages/PACKAGE/README.md`.
Here I add a comment on where we have to do the changes :)
> Add CONTRIBUTING.md instruction for package docs

- packages/core/src/Actor.ts
- packages/core/src/Machine.ts
- packages/core/src/MachineNode.ts
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/StateNode.ts
- packages/core/src/behavior.ts
- packages/core/src/index.ts
- packages/core/src/interpreter.ts
- packages/core/src/invoke.ts
- packages/core/src/scxml.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/definition.test.ts
- packages/core/test/fixtures/id.ts
- packages/core/test/machine.test.ts
- packages/core/test/order.test.ts
- packages/core/test/resolve.test.ts
- packages/core/test/scxml.test.ts
- packages/core/test/utils.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-scxml/src/index.ts
- packages/xstate-scxml/src/scxml.ts
- packages/xstate-scxml/test/scxml.test.ts
- packages/xstate-viz/src/index.tsx
This PR adds `machine.root` to the `StateMachine` class, which represents the root `StateNode` for the machine. Previously, the `StateMachine` (previously named `MachineNode`) _extended_ `StateNode`, but ideally these should be separate.
> [v5] Separate StateMachine and StateNode

- .changeset/chilly-cats-suffer.md
- packages/core/src/types.ts
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/test/useActor.test.tsx
https://github.com/davidkpiano/xstate/pull/2223#discussion_r637368750
> Consider how TEmitted and getSnapshot() return values relate

- docs/guides/models.md
The action and event were named the same (`'updateAge'`) which caused confusion. This PR fixes that ✍️
> [docs] Fix example usage of updateAge

- packages/core/test/actions.test.ts
~The second test is not passing since `a1` is never pushed to the array - it seems like something that should be fixed. Good news is that both pass on the `next` branch.~
For some reason the second test was failing for me locally, maybe some cache issue - nvmd though as it's OK now and CI passes as well
> Add tests for action order for parallel transitions

- docs/packages/xstate-react/index.md
- docs/packages/xstate-vue/index.md
The `service` given to `useService` should be started with `.start()`, or else an error occurs.
This may be an obvious step but it took me awhile to realise (after looking at the test suites for react & vue) 😅
> Fix useService hook API docs

- docs/guides/models.md
There was a missing backtick in the models guide.
> [Doc] Fix typo in models guide

- packages/core/src/Actor.ts
- packages/core/src/ObservableActorRef.ts
- packages/core/src/behavior.ts
- packages/core/src/capturedState.ts
- packages/core/src/dev/redux.ts
- packages/core/src/interpreter.ts
- packages/core/src/invoke.ts
- packages/core/test/actor.test.ts
- packages/core/test/assign.test.ts
- packages/core/test/interpreter.test.ts
- packages/xstate-viz/src/index.tsx
This PR simplifies the `Behavior` interface by consolidating `receive` and `receiveSignal` under the same reducer (as in XActor)
> [v5] Simplify Behavior interface

- .changeset/strange-poets-tap.md
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/stateUtils.ts
- packages/core/test/meta.test.ts
This PR makes `.meta` a property derived from the `.configuration` passed into `State` instead of defined externally (which it shouldn't be).
This allows for `meta` to be calculated from a restored state without it having to be specified:
```js
service.start('someState'); // will fill in `meta`
```
Fixes #1105
> Calculate meta in State

- .changeset/dirty-points-reply.md
- packages/core/src/Actor.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/xstate-inspect/src/types.ts
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/test/useActor.test.tsx
This PR unifies the `ActorRef` type to contain all methods previously only present on the `SpawnedActorRef` type. This was found to be redundant in #2271, so now the types are as follows:
- `ActorRef` contains all methods (required)
- `BaseActorRef` only requires `send`; all other methods are optional. This should seldom be used.
- `SpawnedActorRef` is now an alias to `ActorRef`; it is deprecated and will be removed in v5.
> [core] Unify ActorRef type

- docs/packages/xstate-react/index.md
- packages/xstate-react/README.md
Import statements can't use template literals, I don't believe. That's it. That's the PR!
> docs: Fix invalid import statements

- packages/core/src/State.ts
- packages/core/src/stateUtils.ts
- packages/core/test/state.test.ts
Since this param was basically ignored when `State<any, any, any>` was given to this function I thought that it could be just removed from this overload signature.
> Small change to the type of `State.inert`

- .changeset/fresh-carrots-rule.md
- packages/core/src/Actor.ts
- packages/core/src/interpreter.ts
- packages/xstate-react/README.md
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/src/useService.ts
- packages/xstate-react/test/useActor.test.tsx
- packages/xstate-react/test/useService.test.tsx
- packages/xstate-vue/src/useActor.ts
With `.getSnapshot()`, the `useService()` hooks are virtually the same as `useActor()`.
> Deprecate useService()

- .changeset/grumpy-planes-greet.md
- packages/core/src/Machine.ts
- packages/core/test/model.test.ts
When using a model type in `createMachine<typeof someModel>(...)`, TypeScript will no longer compile machines that are missing the `context` property in the machine configuration:
```ts
const machine = createMachine<typeof someModel>({
// missing context - will give a TS error!
// context: someModel.initialContext,
initial: 'somewhere',
states: {
somewhere: {}
}
});
```
> Ensure that context is defined when model type provided to createMachine()

- .changeset/tasty-books-march.md
- packages/core/src/StateNode.ts
- packages/core/test/transient.test.ts
This PR fixes an issue where, if an event is sent to a machine in a state where it does not accept that event (no enabled transitions), any transient (`always`) transitions will be _ignored_. According to the [SCXML algorithm](https://www.w3.org/TR/scxml/#AlgorithmforSCXMLInterpretation) (see `mainEventLoop`), they should not be ignored.
> Fix issue where always transition not taken in absence of enabled transitions

- .changeset/tender-meals-shave.md
- packages/xstate-vue/src/useActor.ts
- packages/xstate-vue/src/useSelector.ts
- packages/xstate-vue/src/useService.ts
This PR brings the latests changes from `@xstate/react` to `@xstate/vue`. Mainly uses the new `.getSnapshot()` from actors and services, updates some types and removes unnecessary code :)
> [@xstate/vue] Update useActor, useSelector & useService

- docs/packages/xstate-immer/index.md
Seems like Immer slightly updated their doc URLs. All but the first one had working redirects but I updated them anyway.
Also removed an leftover trailing `)` after a link.
> Update Immer Docs URL

- docs/guides/communication.md
I was unclear from reading the documentation what would happen to the default context for a machine when invoking it with a `data` function. Would it merge the contexts together or would it replace it?
From testing, it appears to replace the context of the machine with what you return from the `data` function. This seems worth noting in the documentation
> Clarify Invoking with Context documentation

- .changeset/breezy-countries-tap.md
- packages/core/src/Machine.ts
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/test/actor.test.ts
- packages/core/test/machine.test.ts
Actors can now be spawned directly in the initial `machine.context` using lazy initialization, avoiding the need for intermediate states and unsafe typings for immediately spawned actors:
```ts
const machine = createMachine<{ ref: ActorRef<SomeEvent> }>({
context: () => ({
ref: spawn(anotherMachine, 'some-id') // spawn immediately!
})
// ...
});
```
> [core] Add ability to spawn actors in lazy initial context

- packages/core/src/interpreter.ts
- packages/core/src/types.ts
I believe this fixes the problem mentioned here: https://github.com/davidkpiano/xstate/pull/2358#issuecomment-870615701
It definitely fixes the inference issue on this line:
https://github.com/davidkpiano/xstate/blob/d018a1a22dc4d889fe558842f332bae911f78401/packages/core/test/interpreter.test.ts#L1698
The resulting variable becomes `Observable<State<...>>`, whereas before this change it was `Observable<unknown>`
This obviously is a very weird change but I believe that it's related to how TS, at times, casts overloaded functions to their last overload signature. It happens when performing certain operations on types, when using conditional types etc. Take a look at this simple example:
https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAKKALnlWQFsAjEGASipoaYChRJYEV …
> Allow inferring correct Observable type when working with RxJS

- .changeset/eleven-dancers-study.md
- packages/xstate-react/src/useSpawn.ts
An internal issue where the `spawnBehavior` import for the `useSpawn(...)` hook was broken internally has been fixed.
@Andarist FYI
> [@xstate/react] Fix import in `useSpawn(...)`

- .changeset/red-parrots-judge.md
- packages/core/src/interpreter.ts
- packages/core/test/actor.test.ts
Existing actors can now be identified in `spawn(...)` calls by providing an `id`. This allows them to be referenced by string:
```ts
context: () => ({
someRef: spawn(someExistingRef, 'something')
}),
on: {
SOME_EVENT: {
actions: send('AN_EVENT', { to: 'something' })
}
}
});
```
> Allow existing actors in spawn() to be referenced by name

- docs/guides/states.md
Adds a note on restoring state with spawned actors. See [discussion in Discord](https://discord.com/channels/795785288994652170/799416943324823592/861979176805597216) for context.
I'd love to point to a canonical issue, discussion or PR on the topic, but couldn't find any. Pointers?
> Add note on persisted states with spawned machines

- docs/guides/actions.md
It seems like there's a typo in the docs where the `target` property was defined twice in the same transition. Don't think this was intentional, but feel free to ignore if it was!
> Fix double `target` declarations

- docs/guides/typescript.md
As `StateSchema` is going to be deprecated for v5 and is entirely optional, it's best to discourage its use by omission.
> [docs] Remove StateSchema from typescript.md

- .changeset/warm-spies-cry.md
- packages/core/src/State.ts
- packages/core/src/model.types.ts
fixes #2423 
Note that this PR contains 2 separate fixes for the reported issue. Any of them could be removed and the reported issue would still be fixed. I will comment on each one "inline"
> Fixed an issue with states coming from `model.createMachine` resulting in contexts of type `any` after type refinements

- docs/guides/typescript.md
This PR fixes `typescript.md` and removes a stray, unused type in one of the examples.
Closes #2425
> [docs] Remove stray UserEvents type

- examples/todo-mvc-vue/src/Todos.vue
Selected filter is not a finite state, it is stored in context instead.
The selected filter has border around it.
Before: no border
After: with border
> Fix condition for selected filter class

- .changeset/nasty-ways-trade.md
- packages/xstate-inspect/src/browser.ts
When interpreting machines, when the inspect machine is already in the `connected` state, this makes this `service.event` sent to the inspector right within the `.start()` call:
https://github.com/statelyai/xstate/blob/fb7ea97465dfba0b7ef17edbf327c7c21848c7e8/packages/xstate-inspect/src/browser.ts#L171-L175
but the `service._state` has never been assigned yet up to this point so it's `undefined`. That gets forwarded to the inspector and throws here on `JSON.parse(undefined)`:
https://github.com/statelyai/xstate/blob/fb7ea97465dfba0b7ef17edbf327c7c21848c7e8/packages/xstate-inspect/src/utils.ts#L38
> Fixed a minor issue with sometimes sending `undefined` state to the inspector

- .changeset/dry-kangaroos-roll.md
- packages/core/src/actions.ts
- packages/core/test/deep.test.ts
This method was undocumented and unused (except incorrectly in tests), and removing this improves performance.
Fixes #2488
> Remove `.toString()` method on action objects

- .changeset/forty-chicken-train.md
- packages/xstate-inspect/src/browser.ts
As requested last week. I wonder though if this really should be exposed like that - this is exposing the `inspectMachine`'s state as part of the public API. It could mean that any change to it could be considered a breaking change.
> Call `Inspector`'s `subscribe` callback immediately with the current state at the subscription time

- docs/packages/xstate-react/index.md
- packages/xstate-react/src/useActor.ts
This PR adds warnings for unexpected arguments when migrating from `useService(...)` to `useActor(...)`.
The warnings look like this:
Documentation is also updated. Closes #2412
> [@xstate/react] Improve deprecation warning for send payloads

- docs/about/resources.md
See https://github.com/statelyai/xstate/discussions/2500.
I've split the Articles and Videos section in Articles, Videos, and Repositories. After that I've added  publication or scheduled dates and reordered every section in reverse chronological order. For now I've not merged the Tutorial section.
There were some dead links that I've removed and some entries couldn't be dated. The dates for the repositories are the dates of the first commit.
Feel free to suggest any changes.
> Split and reorder resources

- docs/guides/actions.md
it should be `event object` to work because `send()` action creator tooks as second argument `options` object with only `id`, `to` and `delay` properties.
> fixed "Forward To Action" example

- packages/core/src/types.ts
- packages/core/test/interpreter.test.ts
This PR adds TypeScript annotations for deprecating `activities`.
> Deprecate activities

- .changeset/large-crabs-serve.md
- packages/core/src/interpreter.ts
- packages/core/test/actor.test.ts
This PR fixes #2507 
The problem was a classic race condition:
1. Child machine determining initial state (`this.state` is still `undefined`)
2. Grandchild machine immediately stopping, notifying child machine
3. Child machine trying to remove grandchild from `this.state.children` (remember: `this.state` is still `undefined` at this point) ❌ 
The fix is to _schedule_ the removal of the child, so that it can first complete determining its initial state, so that `this.state` is defined, and then try to remove the child afterward.
> [core] Fix race condition when stopping child of initializing parent machine

- docs/guides/interpretation.md
should be `typeof action.exec === 'function' && action.exec();`?
because got an error ("TypeError: action.exec is not a function") on `action.exec && action.exec();`
> fix action.exec && action.exec()?

- examples/react-tic-tac-toe/package.json
- examples/react-tic-tac-toe/pnpm-lock.yaml
- examples/react-tic-tac-toe/src/ticTacToe.machine.ts
- examples/todo-mvc-react/src/App.jsx
- examples/todo-mvc-react/src/todo.machine.ts
- examples/todo-mvc-react/src/todos.machine.ts
- examples/todo-mvc-svelte/src/todo.machine.ts
- examples/todo-mvc-svelte/src/todos.machine.ts
- examples/todo-mvc-vue/package.json
- examples/todo-mvc-vue/pnpm-lock.yaml
- examples/todo-mvc-vue/src/todoItem.machine.ts
- examples/todo-mvc-vue/src/todos.machine.ts
- packages/core/test/model.test.ts
This PR refactors use of `createMachine<typeof model>` to `model.createMachine` (preferred)
> Refactor use of createMachine with models

- .changeset/modern-pugs-leave.md
- packages/core/src/State.ts
- packages/core/test/rehydration.test.ts
Fixed an issue reported on Discord here: 
https://discord.com/channels/795785288994652170/877294461682602055/878204024803975210
> Fixed an issue with `state.hasTag(someTag)` crashing when the `state` was rehydrated

- .changeset/eight-eggs-press.md
- packages/xstate-react/src/useInterpret.ts
Changed the behaviour of guards, delays and activities when declared as options in `useMachine`/`useInterpret`.
Previously, guards could not reference external props, because they would not be updated when the props changed. For instance:
```tsx
const Modal = (props) => {
useMachine(modalMachine, {
guards: {
isModalOpen: () => props.isOpen
}
});
};
```
When the component is created, `props.isOpen` would be checked and evaluated to the initial value. But if the guard is evaluated at any other time, it will not respond to the props' changed value.
This is not true of actions/services. This will work as expected:
```tsx
const Modal = (props) => {
useMachine(modalMachine, {
actions: {
consoleLogModalOpen: () => {
console.log(props.isOpen);
}
}
});
};
```
This change brings guards, delays and …
> Changed behaviour of guards/actions/services in options of useMachine

- .changeset/chatty-ads-applaud.md
- packages/core/src/types.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/transient.test.ts
Copied from changeset:
Widened the *From utility types to allow extracting from factory functions.
This allows for:
```ts
const makeMachine = () => createMachine({});
type Interpreter = InterpreterFrom<typeof makeMachine>;
type Actor = ActorRefFrom<typeof makeMachine>;
type Context = ContextFrom<typeof makeMachine>;
type Event = EventsFrom<typeof makeMachine>;
```
This also works for models, behaviours, and other actor types.
> Widened the *From utility types to allow extracting from factory functions

- .changeset/metal-guests-pump.md
- packages/xstate-fsm/src/types.ts
I needed this :)
We can probably add some other utility types from `xstate` proper over time.
> Add `ExtractEvent<Event, EventType>` to @xstate/fsm

- .changeset/curvy-snails-wonder.md
- packages/core/src/types.ts
- packages/core/test/model.test.ts
This PR fixes an issue with the `*From<T>` types returning `never`. This was occurring because doing something like:
```ts
T extends Model<infer T, any, any, any>
```
was not working when `T` was actually `Model<Something, never, never, ...>`, since `never` doesn't extend `any` (I think).
The fix was to do this instead:
```ts
T extends Model<infer T, infer _, infer __, infer ___>
```
This also uses the trick that @Andarist proposed in the previous PR 👏 
Fixes #2600
> Fix ContextFrom<T>, EventFrom<T>, EmittedFrom<T>

- docs/README.md
For anyone like me who want to copy-paste examples into Vizualizer without need to add import manually.
> Added missing imports to machine examples

- docs/guides/introduction-to-state-machines-and-statecharts/index.md
Just small typo on the new intro doc, which btw is amazing, well done!!! :)
> Fix: typos on milliseconds of delayed transitions

- .changeset/slow-timers-nail.md
- packages/core/src/model.ts
- packages/core/test/model.test.ts
This PR fixes a regression noticed by some users - when they specified `events` but not `actions` in `createModel(...)`, actions would be typed as `never`:
```ts
const model = createModel(
{},
{
events: {}
}
);
model.createMachine({
// TS will not compile
entry: 'someAction',
exit: { type: 'someObjectAction' },
});
```
Fixes #2619
> [core] Allow any action if action creators are not specified in model

- .changeset/olive-lies-confess.md
- packages/core/src/actions.ts
- packages/core/test/actions.test.ts
fixes #2643 
Sadly, I've noticed this back in July: https://github.com/statelyai/xstate/pull/2430#discussion_r675512313 and even implemented this test back then: https://github.com/statelyai/xstate/commit/c49e058e094c4d565b95668a6cbad5b609158d78 but I've used that as an argument against that linked PR while not realizing that this is already broken on the `main` branch 😢
> Fixed an issue with functions used as inline actions not always receiving the correct arguments when used with `preserveActionOrder`

- .changeset/pretty-poets-try.md
- packages/core/src/model.ts
- packages/core/test/model.test.ts
fixes a regression from here: https://github.com/statelyai/xstate/pull/2632/files#r709015048
> Fixed a regression in the inline actions type inference

- packages/core/src/StateNode.ts
- packages/core/src/machine.schema.json
- packages/core/src/types.ts
- packages/core/test/meta.test.ts
This PR adds `description` as a top-level property for state nodes and transitions:
```js
// ...
states: {
active: {
// ...
description: 'The task is in progress',
on: {
DEACTIVATE: {
// ...
description: 'Deactivates the task'
}
}
}
}
});
```
> Add description property to state and transition

- docs/about/tutorials.md
This PR fixes the link to Kyle Shevlin's [course](https://egghead.io/courses/introduction-to-state-machines-using-xstate) at egghead.io
> Docs: fix link to eggheadio course

- .changeset/long-icons-pull.md
- packages/xstate-react/src/useInterpret.ts
- packages/xstate-react/test/useInterpret.test.tsx
This PR:
- Makes sure we target the correct machine reference in `useInterpret`
- Makes sure the warning is shown when machine reference updates
TODO:
> `@xstate/react`: Correct machine reference in the `useInterpret` hook

- .changeset/dull-bats-hug.md
- .changeset/four-rivers-shave.md
- docs/packages/xstate-graph/index.md
- docs/packages/xstate-test/index.md
- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/index.ts
- packages/xstate-graph/test/__snapshots__/graph.test.ts.snap
- packages/xstate-graph/test/graph.test.ts
- packages/xstate-test/src/index.ts
- packages/xstate-test/test/index.test.ts
The goal of this PR is to use a test model by "manually" defining a sequence of events as opposed to generating them with `getSimplePathPlans`/`getShortestPathPlans`.
```js
dieHardModel.getPlanFromEvents(
[
{ type: 'FILL_5' },
{ type: 'POUR_5_TO_3' },
{ type: 'EMPTY_3' },
{ type: 'POUR_5_TO_3' },
{ type: 'FILL_5' },
{ type: 'POUR_5_TO_3' }
],
{
target: 'success'
}
)
```
This PR adds a `getPathFromEvents(machine, events): StatePath` function which is used by a new method `testModel.getPlanFromEvents(events, options): TestPlan`.
> Generate a test plan from a sequence of events

- docs/recipes/react.md
This PR will properly type the context.
With such way we could inform the users how to properly type our service, since right now it is not clear that we could use the generic `InterpreterFrom<>`
> docs: Typings for the context and the service

- .changeset/optional-activities.md
- packages/core/src/types.ts
Reverts statelyai/xstate#2751
I'm unsure if this change has been sound. We can, of course, make this optional at the type level but in reality this property is **always** defined on the `StateNodeDefinition` object (that is returned from the `stateNode.definition` getter):
https://github.com/statelyai/xstate/blob/c1503b1219d995ebf0f45de46036c5a1d7e6442f/packages/core/src/StateNode.ts#L522
A side note is that the value fallback (`|| []`) is actually redundant because `this.activities` is always an array:
https://github.com/statelyai/xstate/blob/c1503b1219d995ebf0f45de46036c5a1d7e6442f/packages/core/src/StateNode.ts#L442-L444
cc @huan
> Revert "`activities` should be `optional`"

- docs/guides/ids.md
This section should be removed because it's not best practice, and encourages non-deterministic statecharts.
> Removed section on getters from docs

- .changeset/friendly-countries-smash.md
- docs/guides/states.md
- packages/core/test/interpreter.test.ts
This PR removes redundant `resolveState()` invocations from the interpreter tests and the "Persisting State" section of the docs. See https://github.com/statelyai/xstate/discussions/2811.
> Duplicate state resolution

- packages/core/src/StateMachine.ts
- packages/core/src/StateNode.ts
- packages/core/src/memo.ts
This PR introduces internal `memo(...)` and `getMemo(...)` functions that obviate the `__cache` stuff in a more GC-friendly way.
No changeset; internal only.
> [v5] Improve memoization

- .changeset/wise-wasps-drive.md
- packages/xstate-inspect/src/browser.ts
I couldn't get the websocket receiver to work until I changed this line, so I'm assuming this is how it should read (this matches how `createWindowReceiver` is implemented).
> Fix websocket receiver

- .changeset/hungry-jokes-shake.md
- packages/core/src/devTools.ts
`globalThis` is the actual ECMAScript standard for the global object, so this should be returned by `getGlobal()` when available. The existing code (taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) is good as a *replacement* when `globalThis` is not available, but when it is, we should return it directly! See a [similar example in Ember.js](https://github.com/emberjs/ember.js/blob/7b9584bf688c9e5a31447fa690b938ac89d3e656/packages/loader/lib/index.js#L7-L16).
This fixes a real world issue I had when running `xstate` in a rather exotic environment (GraalVM running JS inside a Java server), which correctly supports `globalThis`, but does *not* support `global` (which is node.js specific!) or `self`.
> Support `globalThis` in `getGlobal()` for better compatibility

- packages/core/CHANGELOG.md
I've noticed that those were not mentioned correctly because changeset files were created in separate PRs from the PRs that actually introduced those changes.
> Link more proper PRs/commits to some generated changelog entries

- packages/core/src/types.ts
While I was trying to enable `exactOptionalPropertyTypes` in tsconfig.json, I got tsc errors.
https://github.com/pmndrs/jotai/pull/839
To work around it, it's using a patch now. This is the same fix, without understanding anything.
> Update types.ts to work with --exactOptionalPropertyTypes

- packages/core/src/State.ts
- packages/core/test/state.test.ts
This PR potentially fixes #2837, but reveals another problem in which transitions with multiple targets might be incorrect, preventing this fix from working.
> [core] Add potential fix for failing `state.can` test

- docs/guides/activities.md
This PR adds a deprecation notice for activities, which will be removed in v5.
> Docs: Add deprecation notice for activities

- .changeset/tame-ants-eat.md
- packages/xstate-inspect/examples/server.ts
- packages/xstate-inspect/package.json
- packages/xstate-inspect/rollup.config.js
- packages/xstate-inspect/src/server.ts
- yarn.lock
closes https://github.com/statelyai/xstate/issues/2698 
I've verified that this works with https://statecharts.io/inspect?server=localhost:8888 so it's not a breaking change for that site but it is a breaking change for users of `@xstate/inspect/lib/server`
> Upgrade `@xstate/inspect` to use `ws@8.x`

- .changeset/dirty-birds-sniff.md
- packages/xstate-inspect/src/server.ts
As discussed in #2373, there appears to be a redundant call to `service.subscribe` in the `@xstate/inspect` code.
This PR removes the duplicate call, which used the `JSON.stringify` method instead of the circular object-safe `stringify` utility method that already exists in the package.
> Fix @xstate/inspect crash with circular state object (see #2373)

- CODE_OF_CONDUCT.md
Use the Stately team email address for code of conduct reports.
> Update email address in code of conduct

- .changeset/breezy-onions-thank.md
- packages/core/src/StateNode.ts
- packages/core/test/actor.test.ts
fixes https://github.com/statelyai/xstate/issues/2565
> Fixed an infinite loop when initially spawned actor responded synchronously to its parent

- .changeset/config.json
- .github/workflows/release.yml
- package.json
- scripts/bump-peer-dep-ranges.js
- yarn.lock
Implementing what has been described in the Semver Policy [here](https://github.com/statelyai/xstate#packages-1). It's also somewhat important for fixing the latest `xstate@4.28.0` release that has failed.
> Add a script to bump peer dep ranges when XState version gets bumped

- .changeset/orange-pans-study.md
- packages/core/src/index.ts
fixes #2950
I rly dislike that we are affecting a global thing here - stuff like that causes me harm in the past on several occasions. The risk here is somewhat low but I still dislike the sole notion of doing this 😉
This Symbol is just a „pseudo” standard - it was part of the ES Observable proposal but that never moved far in the standards process. I sympathize with Evan You here: https://github.com/vuejs/core/pull/968#issuecomment-614655701
A funny thing is that… Rx Observables don’t include this property **at the type level** and they dont pass their own `InteropObservable` type-level „check” (although I’ve deduced this from their code and im not sure if I’ve verified this in an actual project, I was playing around with that yesterday and would have to recheck that to be absolutely …
> Bring back the global type declaration for the `Symbol.observable` to fix consuming projects that do not use `skipLibCheck`

- .changeset/sour-candles-exist.md
- packages/core/src/types.ts
fixes https://github.com/statelyai/xstate/issues/2979
> Move @ts-ignore to a JSDoc comment so it gets preserved after compilation

- .changeset/flat-dolls-suffer.md
- packages/core/src/index.ts
Hello xstate team :wave: 
I [asked a question](https://discord.com/channels/795785288994652170/799416943324823592/929512618157285447) some time ago if there are any functions that can retrieve the event names for done/error of services but the answer: 
DIdn't seem to work. I realised later that some of exports from the `actions.ts` file aren't actually exported properly. Especially the ones we're after e.g. `doneInvoke` and `error`.
So this the change I'm making to improve how actions are exported. I don't think I've broken any exports but now everything that's exported from `actions.ts` is now exposed. Let me know if this not the right fix and I can change this to only export the ones we need and were assumed to be exported.
Cheers!
Satya
> improve exporting of 'actions'

- docs/guides/context.md
This PR adds an important note about `assign(...)`, action order, and `preserveActionOrder: true`.
Relevant Discord discussion: https://discord.com/channels/795785288994652170/795785288994652174/937490075179163648
> Add note about `preserveActionOrder: true`

- docs/recipes/react.md
The context value in the [example](https://xstate.js.org/docs/recipes/react.html#global-state-react-context) isn't an interpreter, but contains an interpreter. The type in the accompanying TypeScript note now matches it.
> Updated React recipe context typing advice

- .changeset/breezy-cycles-chew.md
- packages/core/src/interpreter.ts
fixes https://github.com/statelyai/xstate/issues/3010
> Fixed an issue with a reference to `@types/node` being inserted into XState's compiled output

- .changeset/nervous-crabs-cry.md
- packages/core/src/StateNode.ts
- packages/core/test/after.test.ts
> Fixed an issue with states created using `machine.getInitialState` not being "resolved" in full

- .changeset/clean-cobras-exist.md
- docs/packages/xstate-inspect/index.md
- docs/zh/packages/xstate-inspect/index.md
- packages/core/src/interpreter.ts
- packages/core/src/scxml.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/scxml.test.ts
- packages/xstate-analytics/src/index.ts
- packages/xstate-fsm/src/types.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-inspect/src/serialize.ts
- packages/xstate-inspect/src/types.ts
- packages/xstate-inspect/src/utils.ts
- packages/xstate-react/src/useInterpret.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/test/useMachine.test.tsx
- packages/xstate-scxml/src/index.ts
- packages/xstate-scxml/test/scxml.test.ts
- packages/xstate-svelte/test/UseMachine.svelte
- packages/xstate-test/src/types.ts
- packages/xstate-vue/test/UseMachine.vue
This PR:
- Adds `AnyState` to represent `State<any, any, ...>`
- Adds `AnyStateMachine` to represent `StateMachine<any, any, ...>`
- Cleans up internal types using the above two types
> [core] Add `AnyState` and `AnyStateMachine`

- .changeset/long-insects-remember.md
- packages/core/src/types.ts
- packages/core/test/typegenTypes.test.ts
fixes https://github.com/statelyai/xstate/issues/3033
fixes https://github.com/statelyai/xstate/issues/3021
fixes https://github.com/statelyai/xstate/issues/3052
and addresses https://github.com/statelyai/xstate/issues/2984
> Fixed type compatibility with typegen-less functions

- .changeset/curvy-pears-cheat.md
- .github/actions/ci-checks/action.yml
- .github/actions/ci-setup/action.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- package.json
- packages/core/rollup.config.js
- packages/core/src/Actor.ts
- packages/core/src/index.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/types.test.ts
- packages/xstate-inspect/src/browser.ts
- packages/xstate-inspect/src/server.ts
- packages/xstate-react/test/useActor.test.tsx
- packages/xstate-react/test/useSelector.test.tsx
- packages/xstate-svelte/package.json
- packages/xstate-svelte/test/interpreterAsReadable.svelte
- yarn.lock
fixes https://github.com/statelyai/xstate/issues/2533
> Fixed a type compatibility with Svelte's readables

- packages/core/src/Actor.ts
- packages/core/src/interpreter.ts
- packages/core/src/utils.ts
Previously I was trying to use `as typeof Symbol.observable` and this didn't work so I've done those weird transformations to achieve the desired effect. However, it turned out that this can be done much simpler with help of the `as any`
> Simplify how `Symbol.observable` alias is declared

- .changeset/empty-hairs-knock.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
- packages/xstate-react/test/useSelector.test.tsx
Partially fixes https://github.com/statelyai/xstate/issues/3079
> Limit inference sites for TContext

- packages/core/test/typegenTypes.test.ts
Just adding tests to ensure that this kind of generated output would work with the current type machinery
related to https://github.com/statelyai/xstate/issues/2986
> Add typegen tests for never computed for `eventsCausing*` and `invokeSrcNameMap`

- .changeset/red-frogs-yell.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
> Fixed an issue with context type defined using `schema.context` being sometimes widened based on `config.context`

- .changeset/thin-hounds-kiss.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
Fixed the second issue reported here: https://github.com/statelyai/xstate/issues/3028
> Fixed an issue with `ActorRefFrom` not resolving the typegen metadata from machine types

- .changeset/short-eels-cough.md
- packages/core/src/State.ts
- packages/core/src/StateNode.ts
- packages/core/src/index.ts
- packages/core/src/interpreter.ts
- packages/core/src/mapState.ts
- packages/core/src/scxml.ts
- packages/core/src/stateUtils.ts
- packages/core/src/utils.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-inspect/examples/server.ts
- packages/xstate-inspect/src/browser.ts
- packages/xstate-inspect/src/inspectMachine.ts
- packages/xstate-inspect/src/server.ts
- packages/xstate-inspect/src/types.ts
- packages/xstate-react/src/useSpawn.ts
- packages/xstate-scxml/src/index.ts
- packages/xstate-scxml/test/fixtures/assign-current-small-step/test1.ts
- packages/xstate-scxml/test/fixtures/assign/assign_invalid.ts
- packages/xstate-vue/src/useSpawn.ts
Basically, I just removed `keys` as we can easily use `Object.keys`. I've also inlined `flatten` into other packages since it's a one-liner.
Other things that caused "deopts" were moved to the root entry of XState, you can check out what exports have been added
> Fixed compatibility with Skypack

- .changeset/chilled-ghosts-turn.md
- packages/core/src/interpreter.ts
- yarn.lock
fixes https://github.com/statelyai/xstate/issues/3081
> Added some internal `@ts-ignore` comments to fix consuming projects that do not use `skipLibCheck`

- examples/todo-mvc-react/src/todo.machine.ts
In this example the Todo final state is not declared `final` indeed I've noticed that Todos `state.children` keep growing while adding /removing Todo items. With just one line the problem get fixed.  
The problem is probably present also into the other todo-mvc examples.
> fix example todo-mvc-react.

- packages/xstate-inspect/README.md
I think adding `service.start()` here would be a good idea, to make the example work.
I didn't come across interpreted machines / services yet, so I was a bit puzzled why it didn't work.
> Docs: Add `service.start()` to make example work.

- .changeset/kind-waves-provide.md
- packages/core/src/utils.ts
Fixes #3106
The reason that the removal of `keys()` broke the above issue is because various XState tools depend on the `keys()` function to be exported from XState, but it was removed in the newest version.
> Add back export of keys

- .changeset/tasty-bananas-clean.md
- packages/core/src/types.ts
- packages/xstate-react/test/typegenTypes.test.tsx
- packages/xstate-vue/test/typegenTypes.test.tsx
fixes https://github.com/statelyai/xstate/issues/3138
cc @SimeonC
> `InterpreterFrom` and `ActorRefFrom` types used on machines with typegen data should now correctly return types with final/resolved typegen data

- .changeset/hot-trees-occur.md
- packages/core/src/interpreter.ts
- packages/core/test/after.test.ts
> Fixed an issue with interpreters started using a persisted state not being "resolved" in full

- .changeset/giant-suns-wave.md
- packages/core/src/devTools.ts
- packages/core/src/interpreter.ts
In some runtime environments(the Mini Program unique to China), self or global may be empty.
> fix: replace with getGlobal

- .changeset/sweet-snakes-remember.md
- packages/core/rollup.config.js
- packages/core/src/interpreter.ts
attempt 3 to solve the Symbol-related mess, fixes #3141
> Fixed compatibility of `Interpreter` with older versions of TypeScript

- .changeset/hungry-carrots-joke.md
- packages/core/src/stateUtils.ts
- packages/core/test/parallel.test.ts
fixes https://github.com/statelyai/xstate/issues/3170
> Fixed an issue with `onDone` on parallel states with a history state not being called correctly

- docs/.vuepress/config.js
- docs/roadmap/README.md
- docs/updates/2022-03-24.md
A basic Roadmap reflecting our internal Roadmap items. Later on we can make it fancy, but this is the basic content.
Some of them are reworded slightly (based on their issues) for clarity.
Please review considering:
- Is this everything we want to include?
- Should anything here not be included?
- Does grouping by “In Progress”, “Upcoming Q2 2022” and “Later” make sense?
> Add basic Roadmap page

- docs/roadmap/README.md
- docs/updates/2022-04-05.md
As we’re now in Q2, I’ve updated the roadmap.
- Added a link to the blog for updates on new features
- Updated titles to reflect current quarter
- Specified that the work on teams and billing includes private machines (as we get asked this a lot)
Also added an update post about the French translation.
> Update public roadmap in docs

- .changeset/dry-carpets-dream.md
- packages/xstate-inspect/src/browser.ts
- packages/xstate-inspect/test/inspect.test.ts
This builds on top of https://github.com/statelyai/xstate/pull/3198 so it should be merged after it lands on the main branch
> Fixed an issue that caused sending the same event multiple times to the inspector for restarted services

- .changeset/cool-ducks-pretend.md
- packages/core/src/waitFor.ts
- packages/core/test/waitFor.test.ts
Closes #3214
WIP for now as I need figure out how to write a test for this, any pointers?
> Allow passing `Infinity` to `waitFor` as timeout

- .changeset/few-pianos-begin.md
- .changeset/thin-tools-repair.md
- packages/core/src/model.types.ts
- packages/core/src/types.ts
- packages/core/test/typeHelpers.test.ts
- packages/core/test/types.test.ts
Conceptually this is very similar to: https://github.com/statelyai/xstate/pull/3230
> Fixed issues with `TEvent` narrowing

- docs/packages/xstate-react/index.md
Added info to the `options` argument which clarifies how it interacts with any existing `options` that the machine instance was already created with.
> Adding useMachine/useInterpreter options clarity

- .changeset/popular-wolves-tap.md
- packages/core/src/types.ts
- packages/core/test/typeHelpers.test.ts
fixes the issue reported here: https://discord.com/channels/795785288994652170/809564589880639548/974402582393024562
> Fixed an issue in the `EmittedFrom` type helper that could prevent it from inferring the desired type from some service

- packages/xstate-test/src/TestModel.ts
- packages/xstate-test/src/dedupPathPlans.ts
- packages/xstate-test/test/plans.test.ts
This PR optimizes the path deduplication algorithm by:
- Checking paths in path length order descending
- Checking event sequences from the start instead of `.includes()` - for state machines, the subpath must be considered from the initial state, since events "A, B, C" can result in a completely different state traversal in the middle of a state machine rather than at the start
This greatly reduces the number of comparisons made.
> Optimize path deduplication algorithm

- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/types.ts
- packages/xstate-test/src/TestModel.ts
- packages/xstate-test/src/machine.ts
- packages/xstate-test/src/testUtils.ts
- packages/xstate-test/src/types.ts
- packages/xstate-test/src/utils.ts
- packages/xstate-test/test/dieHard.test.ts
- packages/xstate-test/test/events.test.ts
- packages/xstate-test/test/index.test.ts
- packages/xstate-test/test/paths.test.ts
- packages/xstate-test/test/states.test.ts
- packages/xstate-test/test/sync.test.ts
- packages/xstate-test/test/testModel.test.ts
We decided that having `states` and `events` in the test model means you have closure issues.
However, having `cases` only run on `paths` mean they were excluded from path generation.
> Removed states, events from testmodel, removed cases from events

- packages/xstate-test/src/types.ts
this is how we define a very similar type in the core:
https://github.com/statelyai/xstate/blob/eb7856eff2bee10dbb6f80117eec44550cb8bccc/packages/core/src/types.ts#L455-L459
> Refactor `TestTransitionsConfigMap` to use a similar mapped type as the one in `TransitionsConfigMap`

- .changeset/twelve-dingos-fold.md
- packages/core/src/StateMachine.ts
- packages/core/src/actions/invoke.ts
- packages/core/src/actions/stop.ts
- packages/core/src/interpreter.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/invoke.test.ts
fixes https://github.com/statelyai/xstate/issues/3353
> Fixed an issue with actors not being reinstantiated correctly in a microstep

- docs/roadmap/README.md
Update roadmap for June 2022. Just a minor update this month.
> Add share by link and autolayout improvements to Q2 roadmap

- .changeset/flat-melons-tan.md
- packages/xstate-test/src/types.ts
- packages/xstate-test/test/types.test.ts
This narrows down the type of the `event` in the `EventExecutor` to the type that it's keyed by.
I think this is the intention of the code -- am I correct?
> [xstate/test] Narrow down the `event` type passed to `EventExecutor` based on the key

- .changeset/slow-carrots-confess.md
- package.json
- packages/core/src/StateMachine.ts
- packages/core/src/actors.ts
- yarn.lock
Unfortunately `typeof this` cannot be used like this in public methods 😭 See a super simple [TS playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQLYFMAuALA9gCYAUAlIgL4poDmOAspmQFzTYCeADpvgGZu4AljGRox0AE44ArhIB2laJCVz21VBQDcSCkA) demonstrating the problem.
We've missed this because Preconstruct was accidentally swallowing those errors but that has been fixed in [`@preconstruct/cli@2.1.2`](https://github.com/preconstruct/preconstruct/releases/tag/%40preconstruct%2Fcli%402.1.2)
> Fixed the declared signature of one of the `StateMachine`'s methods to avoid using a private name `this`

- .changeset/twenty-fishes-fix.md
- packages/core/actions/package.json
- packages/core/actors/package.json
- packages/core/dev/package.json
- packages/core/guards/package.json
- packages/core/model/package.json
- packages/core/package.json
I'm not a fan of shipping those in 2022 but this has been asked on Discord. I don't want to work too much on those bundles because I think that if somebody needs those then they need to figure out creating those on their end (it's not that hard and we won't have a lot of consumers for those bundles nowadays). 
The main problem with them for us is that Rollup doesn't support code-splitting for such targets:
> Error: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds. 
This can easily be checked on their [playground](https://rollupjs.org/repl/?version=2.75.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBNVUxUSVBMRSUyMEVOVFJZJTIwTU9EVUxFUyUyMColMkYlNUNuaW1wb …
> Add UMD builds backs in the core

- docs/guides/final.md
It wasn't clear what happens to the interpreter after reaching a final state.
This question was asked on Discord and is being written in docs for clarification.
> docs: mention interpreter stopping upon reaching final state

- .changeset/silly-dancers-attack.md
- packages/core/src/StateNode.ts
- packages/core/test/actions.test.ts
fixes https://discord.com/channels/795785288994652170/809564609383890965/986216911459209226
> Fixed an issue with parallel region reentrancy

- .changeset/unlucky-sloths-tell.md
- packages/core/src/StateNode.ts
- packages/core/test/actions.test.ts
> Fixed an issue with targeted ancestor reentrancy

- packages/core/src/StateNode.ts
- packages/core/src/stateUtils.ts
- packages/core/test/history.test.ts
Fixes a regression from https://github.com/statelyai/xstate/pull/3424/files#diff-7f553f4d4c285f1c05cced2e979c5b957d8884e39e74cc6797b32c63a0be7e7aR981 where I've started using `.order` to compare source and target positions in the tree. This has not yet been published so we don't need to add a changeset.
I've removed `.order` from history nodes here: https://github.com/statelyai/xstate/pull/3171/files#r834036363 but back then it was OK because `.order` wasn't actually used in a meaningful way that would impact history states.
> Fixed an issue with reentrancy during external transition when targeting a history state

- examples/fetch/package.json
- examples/fetch/pnpm-lock.yaml
- examples/react-7guis-counter/package.json
- examples/react-7guis-counter/pnpm-lock.yaml
- examples/react-7guis-temperature/package.json
- examples/react-7guis-temperature/pnpm-lock.yaml
- examples/react-list/package.json
- examples/react-list/pnpm-lock.yaml
- examples/react-tic-tac-toe/package.json
- examples/react-tic-tac-toe/pnpm-lock.yaml
- examples/template-js/package.json
- examples/template-js/pnpm-lock.yaml
- examples/template-react-ts/package.json
- examples/template-react-ts/pnpm-lock.yaml
- examples/template-svelte-js/package.json
- examples/template-svelte-js/pnpm-lock.yaml
- examples/template-svelte-ts/package.json
- examples/template-svelte-ts/pnpm-lock.yaml
- examples/template-ts/package.json
- examples/template-ts/pnpm-lock.yaml
- examples/template-vue-ts/package.json
- examples/template-vue-ts/pnpm-lock.yaml
- examples/todo-mvc-react/package.json
- examples/todo-mvc-react/pnpm-lock.yaml
- examples/todo-mvc-svelte/package.json
- examples/todo-mvc-svelte/pnpm-lock.yaml
- examples/todo-mvc-vue/package.json
- examples/todo-mvc-vue/pnpm-lock.yaml
- scripts/update-example-deps.js
This PR does two things:
- Updates dependencies (running `pnpm update`) in each example directory in `/examples`
- Adds a script that makes it easier to update all dependencies (feedback/improvements welcome)
> Update dependencies in example directories

- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
This is an alternative approach to the one taken in https://github.com/statelyai/xstate/pull/3178. This solution only validates that during the development and requires no extra code for the production (as the development-only branch gets stripped down).
This solution here tries to balance the improved DX with the bundlesize concerns
> Alternative solution for #3177 that adds no runtime overhead

- .changeset/spotty-trainers-march.md
- packages/core/src/State.ts
Originally authored by @alexreardon #1115
> [core] Better type information for `state.nextEvents`

- .github/workflows/nodejs.yml
I can't say that I've tested this thoroughly but I checked the GitHub docs and more and I think that it should work.
This is also mentioned here in the `actions/checkout` docs [here](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit). But since we are using the same workflow for both push and pull_request triggers we need to conditionally create the desired SHA.
> Run `pull_request` workflow on its latest commit

- .changeset/pretty-dots-push.md
- packages/core/src/interpreter.ts
- packages/core/src/utils.ts
- packages/core/test/interpreter.test.ts
When an interpreter is stoped, [all listeners get removed](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/core/src/interpreter.ts#L559-L562), therefore a potential subscription should complete.
Closes: #3452
> Call subscription.complete on interpreter stop

- packages/core/test/actions.test.ts
I was testing some scenarios to see if I can break the existing algorithm - I couldn't make it happen so that's good. Since I've already written this test I've concluded that it might be worthwhile to add it either way.
> Add a test for exiting exiting a deep descendant during a self-transition

- .changeset/weak-singers-jog.md
- packages/xstate-react/src/useSelector.ts
- packages/xstate-react/test/useSelector.test.tsx
> Fixed an issue with `useSelector` always computing fresh snapshots internally for uninitialized services

- .changeset/weak-comics-add.md
- packages/core/src/interpreter.ts
- packages/core/test/invoke.test.ts
https://github.com/statelyai/xstate/issues/3522
> Fixed a regression that caused child actors not being correctly stopped when their parent reached a final state

- .changeset/gold-icons-protect.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/test/predictableExec.test.ts
Changes to the algorithm:
1. Instead of flattening the actions in `getActions` into an array I now group them in "blocks".
2. The main purpose for this is to have `invoke` actions and `entry` actions grouped together
3. This allows me to defer `send` actions to the end of the current block and flush them then
> Fixed an issue that caused `invoke`d actors to be created before resolving `assign` actions from `entry` of the same state

- .changeset/lovely-terms-yell.md
- packages/core/src/interpreter.ts
- packages/core/test/predictableExec.test.ts
fixes https://github.com/statelyai/xstate/issues/3548
> Fixed an issue with not being able to send events to initially started child actors when using `predictableActionArguments`

- .changeset/silver-jokes-juggle.md
- packages/core/src/interpreter.ts
- packages/core/test/predictableExec.test.ts
> Fixed an issue with not executing actions in response to received **batched** events when using `predictableActionArguments`

- .changeset/gold-kiwis-mate.md
- docs/fr/guides/actors.md
- docs/fr/packages/xstate-react/index.md
- docs/fr/packages/xstate-vue/index.md
- docs/guides/actors.md
- docs/packages/xstate-react/index.md
- docs/packages/xstate-vue/index.md
- docs/zh/guides/actors.md
- docs/zh/packages/xstate-react/index.md
- docs/zh/packages/xstate-vue/index.md
- packages/core/src/interpreter.ts
- packages/xstate-react/src/useMachine.ts
- packages/xstate-react/src/utils.ts
- packages/xstate-react/test/useSelector.test.tsx
This PR deprecates `someService.state` in favor of `someService.getSnapshot()`.
> [core] Deprecate `service.state`

- .changeset/mean-kiwis-juggle.md
- packages/core/src/actions.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
The `sendTo(actorName, event)` action creator now accepts a string `actorName`:
```js
actions: sendTo('someNamedActor', { type: 'someEvent' })
```
> [core] Allow actor names in `sendTo(...)`

- packages/core/src/types.ts
- packages/core/test/typeHelpers.test.ts
`TEvent` is contravariant and thus `AnyEventObject` can't be used at this position to allow all behaviors:
[TS playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIDcLgPICMBWECYyA3gFDLJgCeADhAFzIDOYUoA5gNzkC+5cqEixEKAIIgaGLGDyFiyCAA9IIACYs0mHASIkKVANoBrCDWZsOITgF1mcKbwHlaDZJJoAhCAAs46MAA9lDIALzIPv6BIQA8njK6CmAANMiONAB8vELg0PBIkX4BwVCxACqJJCpqmmTU9Eys7FzIfGnlAMogcHQsvkFgmWSU1FCOLMBgwSDMABQAthAsLHCcTZU6YACU4cNdPX0DYM6CwvliHsQhAEoQMBVVSqpYdaQNDJYtNm0d3b39QbDQysV7zJYrNYbKq7MLDdBBYDqXhUdZgf5HQbzWH7DGAk78QRuCTXKB3GAAMSgQQWURKcXKwwi5WetS0dJiZVAMGgyE2sjS3N5BwBx0yowA-FcwLd7o8tn9DvjxVRmCAIJgoLxidLZZTqQsKky+azXlpPBzSsgpeJSeSqTTLQzhmqNdAcuoiAAbOBQFAIIIgNjIXAARmYTrK72JzAARJVOuVY796gGAK7gZihtrZVyNDzZiK2mVk+4Ow3EoIwEOh3MAejrVGQAD0JYIA0GSICAO6oKDUqDMC3FTnhGtAA)
For contravariant …
> Fixed `AnyBehavior` to actually allow any `Behavior`

- packages/core/src/StateNode.ts
- packages/core/src/stateUtils.ts
- packages/xstate-react/test/useMachine.test.tsx
This might have not been a bug introduced in the `v5/interpret-all-behaviors` branch but I've noticed it when reviewing it so I'm just creating a branch targeting that.
> Resolve action objects as lazily as possible to avoid stale closure problem in React

- packages/core/CHANGELOG.md
- packages/xstate-fsm/CHANGELOG.md
- packages/xstate-graph/CHANGELOG.md
- packages/xstate-inspect/CHANGELOG.md
- packages/xstate-react/CHANGELOG.md
- packages/xstate-svelte/CHANGELOG.md
- packages/xstate-test/CHANGELOG.md
- packages/xstate-vue/CHANGELOG.md
This combined with https://github.com/statelyai/xstate/pull/3586 should eliminate all of those unrelated changes showing up in PRs in `**/CHANGELOG.md` files.
The problem was that the older version of Changesets was using its local version of Prettier (1.x) but we were using 2.x - so depending on what script was formatting those files we got different results.
> Fixed Markdown formatting in CHANGELOGs

- .changeset/sharp-masks-talk.md
- docs/fr/guides/actions.md
- docs/guides/actions.md
- docs/zh/guides/actions.md
- packages/core/src/index.ts
This PR exports `raise` and `sendTo` directly from `xstate`.
> Export `raise` and `sendTo`

- .changeset/wicked-radios-brush.md
- packages/core/src/StateNode.ts
- packages/core/src/interpreter.ts
- packages/core/test/machine.test.ts
- packages/core/test/rehydration.test.ts
> Fixed a regression that has caused `machine.getInitialState(value)` to not follow always transitions correctly

- packages/core/src/stateUtils.ts
I've just noticed that there was no reason to use an object here if it ended up being converted to an array anyway.
> Simplify `transitionParallelNode` a little bit

- packages/core/src/actions/send.ts
- packages/core/src/exec.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/after.test.ts
Implementing the suggestion from https://github.com/statelyai/xstate/pull/3455/files#r966943424
> Handle events sent to `self` closer to events send to other targets

- docs/about/glossary.md
The same sentence is repeated underneath in a new paragraph.
> Remove duplicate sentence from glossary

- docs/guides/communication.md
The provided example is not working while using it with TypeScript (And I suppose it would not work with JavaScript as well). 
The type on `data` is 
```typescript
Mapper<TContext, TEvent, any> | PropertyMapper<TContext, TEvent, any>
```
Where `PropertyMapper` is not working correctly. TS can'd properly infer the `context` and `event` types if the code was written as in example.
I suppose for that bug could be created, but for now I would like docs to be correct.
> Fix 'Done Data' example code in communications.md

- docs/packages/xstate-react/index.md
How I read and interpreted the docs, there is little difference between `useMachine` from the core package and the FSM package, which is why the missing optional `options` argument in the header of this paragraph caught me a bit off guard, and I think it's clearer to readers to add it.
> Add optional options argument to FSM useMachine docs heading

- docs/guides/states.md
- Add warning that `state.can` will execute transition guards
- Updates `state.can` examples to use the full event object due to valid confusion in the discord discussion below and the fact that TypeScript demands the full event object.
Based on the discussion at https://discord.com/channels/795785288994652170/1022469795582591057/1022481693929635880
> `state.can` docs update

- .changeset/afraid-kids-happen.md
- packages/xstate-svelte/src/useSelector.ts
The Svelte docs say `get`  should [not be used in hot paths](https://svelte.dev/docs#run-time-svelte-store-get). It is used in `useSelector` to compare the updated value with the previous value.  This PR changes the function to store the previous value in a local variable instead.
> xstate-svelte: Avoid using svelte store get in useSelector.

- .changeset/mighty-phones-press.md
- packages/core/src/StateNode.ts
- packages/core/test/actions.test.ts
Found that when the current node was a descendent of the target node, it was re-entering every node as it climbed to the target.
fixes https://github.com/statelyai/xstate/issues/3618
fixes https://github.com/statelyai/xstate/issues/3613
> During external events, only enter target and descendent nodes

- .changeset/large-snails-decide.md
- .changeset/rich-monkeys-relate.md
- packages/core/src/StateNode.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
We didn't have an explicit issue open about those fixed issues. Those are things that I've spotted when investigating some issue reports and when reviewing some other PR.
The issue with the targeted ancestor not being **exited** correctly when it was already being **entered** during reentering transition has been mentioned in the second point here:
https://github.com/statelyai/xstate/issues/3613#issuecomment-1256307617
> Fixed issues around reentrancy during external transitions

- packages/core/src/waitFor.ts
I somehow missed this in the [docs](https://xstate.js.org/docs/guides/interpretation.html#waitfor) and it took me quite a while to figure out where the timeout error came from. If you look at the source, it is obvious as the options mention the timout, but I only looked at the inline docs in my editor which only showed the `waitFor` docstring that didn't mention this timeout at all 😅
> Mention timout in docstring of `waitFor`

- .github/workflows/codesee-arch-diagram.yml
- .github/workflows/docs.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .changeset/seven-ducks-look.md
- packages/core/src/actions.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
This PR allows action `type` strings to be returned from the `getActions` argument of `pure`. `xstate` already handles action strings correctly but the types don't match that functionality.
This PR pairs well with statelyai/xstate-tools#207
> allow action `type` strings in `pure` return array

- .changeset/shiny-kangaroos-battle.md
- docs/fr/guides/models.md
- docs/guides/models.md
- docs/zh/guides/models.md
- packages/core/src/model.ts
The `createModel(...)` function is now marked as deprecated, as it will be removed in XState version 5. It is recommended to use [Typegen](https://stately.ai/blog/introducing-typescript-typegen-for-xstate) instead.
> Deprecate `createModel(...)`

- packages/core/src/interpreter.ts
- packages/core/test/invoke.test.ts
Implements what has been documented as a change here: [.changeset/perfect-ants-count.md](https://github.com/statelyai/xstate/pull/3455/files#diff-7a71c2790bd3a7c7eb671dd7c85372a49cad80b94a99e023d738274308984732)
> Remove `Interpreter#onError`

- packages/core/src/exec.ts
- packages/core/test/actions.test.ts
- packages/core/test/actor.test.ts
- packages/core/test/predictableExec.test.ts
As per comment [here](https://github.com/statelyai/xstate/pull/3455/files#r968358269):
> This tests a very specific situation - with no other machines in the picture etc so a grandchild can't be just stopped for any other reason than because its parent here (child) gets stopped.
> No race condition is possible here even if we assume that sending events is asynchronous because this test tests that events sent from child to grandchild are sent "in order". It also tests that a sent event is sent before an implicit event that informs the grandchild to stop. In other words, it tests that we can send events from a machine to its children before notifying them about them being stopped and it tests that they can process that event (because the stop notification has not been delivered to them yet, …
> Defer stopping actors

- .changeset/quick-lizards-burn.md
- .changeset/quick-lizards-thrive.md
- package.json
- packages/core/package.json
- packages/xstate-analytics/package.json
- packages/xstate-fsm/package.json
- packages/xstate-graph/package.json
- packages/xstate-immer/package.json
- packages/xstate-inspect/package.json
- packages/xstate-react/package.json
- packages/xstate-scxml/package.json
- packages/xstate-svelte/package.json
- packages/xstate-test/package.json
- packages/xstate-vue/package.json
- yarn.lock
fixes https://github.com/statelyai/xstate/issues/3350
> Added `package.json#exports` to all packages

- packages/xstate-test/src/TestModel.ts
- packages/xstate-test/src/machine.ts
- packages/xstate-test/src/types.ts
- packages/xstate-test/test/index.test.ts
This PR removes the ability to execute actions in the upcoming `@xstate/test`. Executing side-effects should only be done either within the event execution or asserting the state (if needed).
@Andarist Not sure how to handle the alpha changeset for this one
> Remove test action execution

- packages/core/README.md
This PR replaces a dead link to Spectrum with a link to the Stately Discord community.
And it fixes a markdown link within the document.
> Remove dead Spectrum link and fix markdown link

- .changeset/serious-chairs-try.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
Addresses #3744 https://github.com/statelyai/xstate-tools/issues/275
> Fix: update types for invoked service target to allow string

- .changeset/serious-chairs-try.md
I noticed that my commit from https://github.com/statelyai/xstate/pull/3745 accidentally referenced an incorrect issue #. This change drops the issue number from the changeset, as the output will already include the correct PR # when a future release is generated.
> chore: remove incorrect issue number from latest changeset

- .changeset/quiet-swans-divide.md
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/src/useInterpret.ts
- packages/xstate-react/src/useSelector.ts
- packages/xstate-react/src/utils.ts
- packages/xstate-react/test/useInterpret.test.tsx
This PR adds a failing test and proposes a "fix" for an issue [reported in Discord](https://discord.com/channels/795785288994652170/1061308540490367006/1061308540490367006):
> I've been putting off updating the xstate package in my company's codebase for some time now as some of our machines break when upgrading from 4.32.1 -> 4.33.0. 
>
> I finally got some time to dedicate to it and have replicated the issue in a simplified code sandbox.  The sandbox has a very basic react app, which uses a parentMachine, which in turn spawns a childMachine. There is a button that sends an event to the parentMachine. The parentMachine should then send an event to the childMachine. The UI should then update to say that the child received the event. Simple.
>
> The issue seems to be that the parentMachine …
> Fixed how the initial state of a service is read by the `useActor` hook

- packages/core/src/types.ts
- packages/core/src/utils.ts
Since this is somewhat unrelated to the `v5/interpret-all-behaviors`, I don't intend to land this immediately - I'm opening this to not forget about this.
> Remove leftover code that was used when it was possible to transition to state nodes using getters

- .changeset/blue-jeans-think.md
- packages/xstate-inspect/src/inspectMachine.ts
Closes https://github.com/statelyai/xstate/issues/3771
> Use predictableActionArguments flag in the createInspectMachine to avoid spurious warnings

- packages/core/test/activities.test.ts
Those tests were accidentally removed in [here](https://github.com/statelyai/xstate/commit/20e08e30de252889cc80f4aaa80d349ac33ffc88#diff-ed77fc7fa7c2ced9d56aa66d3d07015c7865cf93e17a626e25d3c48e89391d2a), leaving this test file expect-less.
I took the liberty to rewrite them in the process, to use separate machines per test.
> Bring back (& rewrite) accidentally removed tests

- .github/workflows/nodejs.yml
I came to the conclusion that this change wasn't needed/desirable. 
The default behavior on GitHub can lead to some weird effects/logs but it's just something to keep in mind and not something that we should prevent. The default behavior gives us stronger guarantees that if the CI is OK in the PR then it will also be OK after merging that PR. It doesn't give us 100% guarantees though as the CI run happens at a different time than the actual merge - but it's still better than not having this at all. To get that 100% guarantee we'd have to enforce "branch is up to date with main" before merging but that sounds like a lot of hassle to me and my opinion is that it's not worth it.
> Revert "Run `pull_request` workflow on its latest commit (#3490)"

- .changeset/sharp-weeks-end.md
- packages/xstate-solid/package.json
Change `prepublish` to `prepare` in package.json to fix build not running on npm publish.
> [xstate/solid] Change prepublish to prepare

- .changeset/curly-candles-learn.md
- packages/xstate-react/src/createActorContext.tsx
- packages/xstate-react/src/useInterpret.ts
- packages/xstate-react/test/createActorContext.test.tsx
Currently, it's not possible to pass interpreter options to the underlying `useInterpret` in `createActorContext`. One of the use cases for passing such options is to add observers to the actor on the creating time or inspect an actor in the runtime using `xstate/inspect`.
> Ability to pass interpreter options and observers to actors created via `createActorContext`

- .changeset/shy-donkeys-glow.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/interpreter.ts
- packages/core/src/model.types.ts
- packages/core/src/scxml.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/types.test.ts
- packages/xstate-immer/src/index.ts
- packages/xstate-react/test/createActorContext.test.tsx
- packages/xstate-react/test/useActor.test.tsx
With this change, the inferred types for `raise` are being improved. We can see here that both `TExpressionEvent` and `TEvent` are inferred correctly here - to `{ type: 'DECIDE'; aloha?: boolean | undefined; }` and `GreetingEvent`, respectively.
In here we can see that this improves autocomplete capabilities in the IDE because the contextual type is restricted to what can actually be sent to this machine:
And in here we can see that a type error is raised (huehue) correctly when we try to use an invalid event:
⚠️ there are some type failures here as I didn't yet adjust everything around the implementation etc. This only touches public-facing APIs etc - as only those had to be adjusted to validate the idea.
I'm not super keen on touching types in v4 as I'd really like to completely rewrite …
> Introduce `TExpressionEvent` generic

- .changeset/healthy-fireants-beg.md
- packages/xstate-react/src/createActorContext.tsx
fixes what was reported [here](https://github.com/statelyai/xstate/discussions/3828#discussioncomment-4957618), cc @equal-matt
#tooclosetothesun
> Fixed compatibility of the generated TS types for `createActorContext` with pre-4.7

- .changeset/mean-oranges-dress.md
- packages/core/src/types.ts
- packages/core/test/typeHelpers.test.ts
- packages/core/test/types.test.ts
Hi yall! I saw a helper type request on Discord today that seemed easy enough to implement: `TagsFrom`
`TagsFrom` allows us to access the typegen `tags` type of a `Machine` ~~`State`, or `Interpreter`~~:
```ts
import { TagsFrom } from "xstate";
tsTypes: {} as {
"@@xstate/typegen": true;
tags: "a" | "b" | "c";
}
});
type Tags = TagsFrom<typeof machine>; // 'a' | 'b' | 'c'
```
If typegen isn't enabled, `TagsFrom` returns `string` (which matches `hasTag`):
```ts
import { TagsFrom } from "xstate";
const machine = createMachine({});
type Tags = TagsFrom<typeof machine>; // string
```
> add `TagsFrom` helper type

- .github/workflows/docs.yml
This PR uses setup-node script to set node 16 for the docs build.
> Build docs using node 16

- .changeset/nasty-suns-film.md
- packages/core/src/actions.ts
> Fixed `forwardTo`, `escalate` and `sendUpdate` to be compatible with required action types

- .changeset/lemon-dancers-repeat.md
- examples/todo-mvc-svelte/src/Todos.svelte
- packages/core/src/interpreter.ts
- packages/core/test/actor.test.ts
- packages/core/test/assign.test.ts
- packages/core/test/event.test.ts
- packages/core/test/final.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/invoke.test.ts
- packages/core/test/meta.test.ts
- packages/core/test/scxml.test.ts
- packages/xstate-inspect/examples/server.ts
- packages/xstate-inspect/test/inspect.test.ts
- packages/xstate-scxml/test/scxml.test.ts
This PR removes `.onTransition(...)` in favor of `.subscribe(...)`
```diff
const actor = interpret(machine)
-  .onTransition(...)
-  .start();
+actor.subscribe(...);
+actor.start();
```
> [v5] Remove `.onTransition()`

- .changeset/stupid-buttons-brake.md
- packages/xstate-react/package.json
- yarn.lock
When installing `@xstate/react` on a React 18 project, we get a warning that `use-isomorphic-layout-effect@1.0.0` doesn't support this version of React. As such, this pull request bumps the required minimum version of the dependency to fix the warning. There were no breaking changes in the dependency between 1.0.0 and 1.1.2 so from what I can see, this can be released as a minor version bump.
> Fix warning about unmet peer dependencies

- packages/core/test/actions.test.ts
- packages/core/test/after.test.ts
- packages/core/test/deep.test.ts
- packages/core/test/deterministic.test.ts
- packages/core/test/final.test.ts
- packages/core/test/guards.test.ts
- packages/core/test/internalTransitions.test.ts
- packages/core/test/transient.test.ts
- packages/core/test/utils.ts
I only left 2 tests depending on those `.actions`, those have to be rewritten later as I wasn't super sure how to best rewrite them today. Perhaps they just will have to be removed or smth
> Rewrite tests to not depend on `State['actions']`

- .changeset/five-mirrors-join.md
- packages/core/src/StateNode.ts
- packages/core/src/actions.ts
- packages/core/src/stateUtils.ts
- packages/core/src/typegenTypes.ts
- packages/core/src/types.ts
- packages/core/test/actor.test.ts
- packages/core/test/final.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/invoke.test.ts
- packages/core/test/json.test.ts
- packages/core/test/typegenTypes.test.ts
- packages/xstate-react/test/useMachine.test.tsx
- packages/xstate-scxml/src/index.ts
- packages/xstate-solid/test/useMachine.test.tsx
- packages/xstate-svelte/test/fetchMachine.ts
- packages/xstate-test/src/types.ts
- packages/xstate-vue/test/UseMachine.vue
- packages/xstate-vue/test/useMachine.test.ts
This PR renames `.data` to `.output` on final states:
```diff
// ...
states: {
// ...
success: {
-     data: { message: 'Success!' }
+     output: { message: 'Success!' }
}
}
})
```
> [v5] Final `.data` to `.output`

- .changeset/odd-pigs-brush.md
- packages/core/src/actors/index.ts
- packages/xstate-react/test/useActor.test.tsx
This PR makes it easy to create null actors which only emit `undefined`.
Especially in `@xstate/react`, this makes working with maybe-undefined actors easier:
```jsx
import { createEmptyActor } from 'xstate/actors';
// ...
function Comp({ maybeActor }) {
const [state, send] = useActor(maybeActor ?? createEmptyActor());
state?.count; // strongly-typed; state can be undefined
}
```
> [v5] `createEmptyActor()`

- .changeset/eighty-trainers-compare.md
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/interpreter.ts
- packages/core/test/actions.test.ts
- packages/core/test/interpreter.test.ts
Event objects should be sent; sending strings is no longer allowed.
> [v5] Throw when sending strings

- .changeset/fuzzy-cows-film.md
- packages/core/src/actions.ts
- packages/core/test/actions.test.ts
Related to https://github.com/statelyai/xstate/issues/3979#issuecomment-1520848768
> Fixed an issue with a referenced action responding to an initial raised event being called with init event

- packages/core/test/interpreter.test.ts
- packages/core/test/meta.test.ts
This just ports test changes from https://github.com/statelyai/xstate/pull/3912 . I feel like `done` often makes it harder to read and debug tests, if something doesnt get called then the test runner has to first wait for the timeout before failing the test case - faster fails -> faster dev cycle -> 💰
> Rewrite a few tests

- jest.config.js
- package.json
- packages/core/package.json
- packages/core/src/actors/promise.ts
- packages/core/src/interpreter.ts
- packages/core/test/eventDescriptors.test.ts
- packages/core/test/interpreter.test.ts
- packages/core/test/scxml.test.ts
- packages/core/test/tsconfig.json
- packages/xstate-test/src/types.ts
- packages/xstate-test/test/types.test.ts
- scripts/jest-utils/console-spies.js
- scripts/jest-utils/index.d.ts
- scripts/jest-utils/index.js
- scripts/jest-utils/package.json
- scripts/jest-utils/setup.d.ts
- scripts/jest-utils/setup.js
I find our test output to be spammy and at times I feel like it's likely that some of the logged messages indicate logical errors in tests. I yet have to verify that - this PR lays out a foundation for deliberate console outputs.
With this PR we will be **forced** to either use `expect(console.warn).toMatchMockCallsInlineSnapshot()` (and similar) or `clearConsoleMocks()` (although that should be done *rarely*, I only used this in our SCXML tests). This should force us to be thoughtful about the logged things and to take appropriate action for each logged information
> Improve control over console logs in tests

- .changeset/selfish-points-know.md
- packages/core/src/actors/observable.ts
- packages/core/test/invoke.test.ts
> [v5] Add `input` support to `fromEventObservable`

- .changeset/nasty-pants-doubt.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Code of conduct is now up to date with [the contributor covenant code of conduct version 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). This adds information about enforcement of the code of conduct.
- Adds more information about how to contribute to XState, including submitting issues and helping provide support.
> Update code of conduct and contributions guide

- .changeset/silver-dolphins-fry.md
- packages/xstate-immer/package.json
- yarn.lock
Just bumping to allow v9 and v10. The breaking changes for this don't affect XState-immer as we don't use the default export of immer or the other features.
> Bump XState-immer immer peer dependency

- CONTRIBUTING.md
This PR just updates the contribution guide with some info about how to contribute to our docs and how the “legacy” docs and xstate.js.org docs + landing page are maintained.
> Add docs contribution info + legacy docs/xstate.js.org upkeep info

- examples/stopwatch/src/stopwatchMachine.ts
Tiny fix to update the machine name in the stopwatch example.
> Rename machine in stopwatch example

- .changeset/slow-peas-repair.md
- packages/core/src/actors/callback.ts
- packages/core/src/actors/observable.ts
- packages/core/src/actors/promise.ts
- packages/core/src/types.ts
- packages/core/test/actorLogic.test.ts
- packages/core/test/system.test.ts
This PR provides access to `system` for all actor logic.
```ts
fromPromise(({ system }) => { ... });
fromTransition((state, event, { system }) => { ... });
fromObservable(({ system }) => { ... });
fromEventObservable(({ system }) => { ... });
fromCallback((sendBack, receive, { system }) => { ... });
```
> [v5] System for all actor logic

- .changeset/tall-flies-occur.md
- docs/packages/xstate-fsm/index.md
- packages/xstate-fsm/README.md
- packages/xstate-fsm/src/index.ts
- packages/xstate-fsm/src/types.ts
- packages/xstate-fsm/test/fsm.test.ts
- packages/xstate-fsm/test/types.test.ts
- packages/xstate-fsm/tsconfig.json
After a recent discussion regarding how to handle unexpected events (#4057) brought wildcard transitions to my attention, I wanted to see what it would take to add them to the @xstate/fsm package. Fortunately, it turned out to be pretty straightforward.
This PR introduces three behavioral changes, in addition to the supporting tests and documentation:
1. If a machine is created with transitions whose event type is a single asterisk, those transitions are added to the list of transitions attempted regardless of event type. This has the effect that, if no other transition has occurred, the wildcard transitions are checked before giving up and returning an unchanged state.
2. To prevent the above from causing typing problems, a single asterisk is considered a valid key in the transitions …
> Add support for wildcard transitions to xstate-fsm

- .changeset/few-lamps-yawn.md
- packages/core/src/spawn.ts
- packages/core/test/actor.test.ts
fixes https://github.com/statelyai/xstate/issues/4077
> Do not use a static string as ID for spawned actors when no explicit IDs are given to them

- .changeset/kind-donkeys-fetch.md
- packages/core/src/index.ts
- packages/core/test/actions.test.ts
The `log`, `pure`, `choose`, and `stop` actions were added to the main export:
```ts
import { log, pure, choose, stop } from 'xstate';
```
> Add missing actions to main export

- .changeset/tender-cups-obey.md
- packages/core/src/StateNode.ts
- packages/core/src/scxml.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/after.test.ts
- packages/core/test/deterministic.test.ts
- packages/core/test/eventDescriptors.test.ts
- packages/core/test/json.test.ts
- packages/core/test/machine.test.ts
- packages/core/test/scxml.test.ts
- packages/core/test/transient.test.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-scxml/src/scxml.ts
- packages/xstate-test/src/types.ts
- packages/xstate-test/src/validateMachine.ts
I think that:
1. `TransitionsConfigArray` complicated our types
2. it also complicated our implementation and slowed down the most basic scenario (we were searching for candidates with explicit descriptors in the array instead of just looking it up in a map)
3. it's **rarely** used feature (if used at all)
4. its existence it makes vizualization harder/less obvious. We don't visually order (nor denote order) anyhow. By removing the ability to order transitions arbitrarily in an array we make it more intuitive to interpret the visualization: explicit descriptions > longest-to-shortest partial descriptors > wildcard
This PR is not meant to refactor all inner bits. The main goal here was to remove this from the types and the public API, the internals could still use some further cleanups but …
> Drop support for `TransitionsConfigArray`

- .changeset/forty-knives-remain.md
- packages/xstate-svelte/package.json
closes: https://github.com/statelyai/xstate/issues/4105, make xstate-svelte compatible with svelte 4.
> Allow Svelte 4 in the specified peer dependency range

- .changeset/big-coats-fetch.md
- packages/core/src/actions.ts
- packages/core/src/types.ts
- packages/core/test/actions.test.ts
This PR allows function actions to be typed in `pure()`:
```ts
actions: pure(() => [
// now allowed!
(context, event) => { ... }
])
```
> Add function action type to pure

- packages/xstate-svelte/src/useSelector.ts
- packages/xstate-svelte/test/UseSelectorDeferredSubscription.svelte
- packages/xstate-svelte/test/useSelector.test.ts
The function provided to svelte's `readable` is only invoked when the first subscriber subscribes to this store.
But because stately’s `actor.subscribe` does not fire immediately after subscribing (it only fires when something changes in the state) the svelte store could have a stale value (with the initial `prevSelected`) until the state in the machine changes and triggers the update.
This PR fixes that, by making sure that the value is not stale when the first subscription happens.
> Make sure useSelector.ts doesn’t create stale values

- .changeset/swift-stingrays-notice.md
- packages/core/src/Machine.ts
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/StateNode.ts
- packages/core/src/scxml.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/final.test.ts
- packages/core/test/input.test.ts
- packages/core/test/types.test.ts
- packages/xstate-react/src/createActorContext.ts
- packages/xstate-scxml/src/scxml.ts
- packages/xstate-solid/src/types.ts
- packages/xstate-test/src/types.ts
Output types can now be specified in the machine:
```ts
types: {} as {
output: {
result: 'pass' | 'fail';
score: number;
};
}
// ...
});
const actor = createActor(machine);
// ...
const snapshot = actor.getSnapshot();
if (snapshot.output) {
snapshot.output.result;
// strongly typed as 'pass' | 'fail'
snapshot.output.score;
// strongly typed as number
}
```
> [v5] Output types

- packages/core/src/State.ts
Currently, the returned values are **event descriptors**. Usually, they match `TEvent["type"]` but they don't have to. Values like this `foo.*` can be returned from this method.
> Change `State['nextEvents']` return type to `string[]`

- .changeset/config.json
- .changeset/grumpy-planes-protect.md
- packages/xstate-graph/src/adjacency.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/index.ts
- packages/xstate-graph/src/pathFromEvents.ts
- packages/xstate-graph/src/shortestPaths.ts
- packages/xstate-graph/src/simplePaths.ts
- packages/xstate-graph/test/graph.test.ts
- packages/xstate-graph/test/shortestPaths.test.ts
- packages/xstate-graph/test/types.test.ts
Remove `getMachineShortestPaths` and `getMachineSimplePaths`
```diff
import {
- getMachineShortestPaths,
+ getShortestPaths,
- getMachineSimplePaths,
+ getSimplePaths
} from '@xstate/graph';
-const paths = getMachineShortestPaths(machine);
+const paths = getShortestPaths(machine);
-const paths = getMachineSimplePaths(machine);
+const paths = getSimplePaths(machine);
```
> Remove getMachineShortestPaths and getMachineSimplePaths

- packages/core/test/types.test.ts
this is a spiritual successor to https://github.com/statelyai/xstate/pull/1604
We don't fully support state composition done this way, typing builtin actions within the "state slice" is currently quite challenging and this pattern limits our current capabilities related to static analysis etc. From the types PoV though this simple example is OK and we can continue to support it.
> Add a type-level test related to states composition

- packages/core/src/types.ts
- packages/core/test/invoke.test.ts
This feature~ was replaced in v5 by `invoke.input` so we don't need it since it's actually not used by the runtime anyhow.
> Remove leftovers of `invoke.meta`

- packages/core/src/StateNode.ts
- packages/xstate-test/src/validateMachine.ts
I only found this to be used in a single place so it's an easy win for the bundlesize
> Removed `StateNode['stateIds']` getter

- .changeset/beige-pianos-give.md
- packages/core/src/actors/index.ts
- packages/core/src/index.ts
Actor types are now exported from `xstate`:
```ts
import {
type CallbackActorLogic,
type ObservableActorLogic,
type PromiseActorLogic,
type TransitionActorLogic
} from 'xstate';
```
> [v5] Export actor logic types

- .changeset/polite-experts-wash.md
- packages/core/src/spawn.ts
- packages/core/test/types.test.ts
this PR redoes https://github.com/statelyai/xstate/pull/3136
> Improved type safety of `spawn`ed inline actors when the actor types are not provided explicitly

- .changeset/big-avocados-raise.md
- packages/xstate-react/src/useMachine.ts
This PR makes it so that `useMachine` (very commonly used hook) doesn't appear as strikethrough in code (technically aliased, not deprecated)
> [v5] Alias `useMachine` in `@xstate/react`

- README.md
Hi there,
I'm Alexander, a designer from Transloadit. I'd like to fix our logo appearance in XState's README, and add some UTM tags to the link to our website.
- Fixed the Transloadit logo wasn't visible when GitHub is used with light theme
- Added UTM tags to the link to Transloadit's website
**Before:**
> <img width="567" alt="Screenshot 2023-09-18 at 11 19 55@2x" src="https://github.com/statelyai/xstate/assets/375537/17ba60f2-eed5-4c7e-a400-c807e6b5f8b3">
**After:**
> <img width="564" alt="Screenshot 2023-09-18 at 11 20 04@2x" src="https://github.com/statelyai/xstate/assets/375537/27f6dc46-f15a-4bdd-8a7c-b13364962bb9">
**Dark/light mode preview:**
> ![Screenshot 2023-09-18 at 11 21 44](https://github.com/statelyai/xstate/assets/375537/6e9e580b-3d20-44d6-bc64-8724e70402d0)
/cc @kvz
> Update the Transloadit's sponsorship link and logo

- babel.config.js
node 16 will soon (in Oct) stop being the LTS version
> Change Babel's target to node 18

- .changeset/angry-seals-sin.md
- packages/xstate-graph/src/actorContext.ts
- packages/xstate-graph/src/adjacency.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/pathFromEvents.ts
- packages/xstate-graph/src/shortestPaths.ts
- packages/xstate-graph/src/simplePaths.ts
- packages/xstate-graph/test/graph.test.ts
- packages/xstate-graph/test/shortestPaths.test.ts
This PR makes machines like this work, that would previously error. The problem was we didn't have a `actorCtx.defer(...)` function.
```ts
initial: 'a',
states: {
a: {
after: {
1000: 'b'
}
},
b: {}
}
});
```
> [@xstate/graph] Mock `actorContext`

- packages/core/src/actions/assign.ts
- packages/core/src/actions/cancel.ts
- packages/core/src/actions/choose.ts
- packages/core/src/actions/invoke.ts
- packages/core/src/actions/log.ts
- packages/core/src/actions/pure.ts
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/actions/stop.ts
It's just an internal change to make it more clear in the call stack what is being executed.
> Give unique names to `resolve` in `execute` helpers used by builtin actions

- .changeset/wise-eggs-train.md
- packages/core/src/actors/callback.ts
- packages/core/test/actorLogic.test.ts
This PR persists the `input` of callback, which was coming back as `undefined` when restoring callback state.
> Persist callback input

- docs/fr/packages/xstate-vue/index.md
- docs/packages/xstate-vue/index.md
- docs/zh/packages/xstate-vue/index.md
- packages/xstate-vue/README.md
This PR replaces `v-if-else` occurrences with `v-else-if` as well as migrating Vue examples from different language folders to use `<script setup>`.
> docs(vue): Fix example conditions typos and migration and script setup migration

- .changeset/silver-coins-shop.md
- packages/core/src/State.ts
This PR changes the type of `state.nextEvents` to use `TEvent['type']`. This is to make the type of the next events compatible with the `send` methods input which use `EventFromLogic`.
> Use TEvent['type'] for .nextEvents

- .changeset/stale-crews-cry.md
- packages/core/src/index.ts
- packages/core/test/inspect.test.ts
Inspection events are now exported:
```ts
import type {
InspectedActorEvent,
InspectedEventEvent,
InspectedSnapshotEvent,
InspectionEvent
} from 'xstate';
```
> Export inspection event types

- .changeset/wild-apes-play.md
- packages/core/src/actions/send.ts
- packages/core/src/stateUtils.ts
- packages/core/test/actions.test.ts
- packages/core/test/final.test.ts
- packages/core/test/rehydration.test.ts
It's important for rehydration. A stopped aka persisted machine can't call its exit actions if we don't call entry actions later on when rehydrating that state. And we can't call those entry actions because we have no sensible `event` to call them with. In addition to that - the whole persisting/rehydrating cycle should be mostly transparent to the user and if we call those actions it's no longer transparent.
Originally, we only started to call those actions in this situation because it was what SCXML mandated. It didn't come from a user request.
> Stop calling exit actions on stop

- packages/core/src/stateUtils.ts
- packages/core/test/final.test.ts
`xstate.done.state.*` events are dispatched for **parent** states and not for final states themselves. As parallel states are completed when all of their child regions are complete we can't dispatch this event in this situation as a completion of a single region would complete the whole parallel state.
> Do not resolve `output` of final states directly nested in parallel states

- .changeset/eight-radios-battle.md
- packages/core/src/guards.ts
- packages/core/test/stateIn.test.ts
closes https://github.com/statelyai/xstate/issues/4383
> Added support to `stateIn` guard for checking a combination of an ID and a path

- .changeset/small-lobsters-tie.md
- packages/core/src/interpreter.ts
- packages/core/test/actions.test.ts
- packages/core/test/final.test.ts
fixes https://github.com/statelyai/xstate/issues/4167
> Fixed an issue with `exit` actions sometimes being called twice when machine reached its final state

- packages/core/src/typegenTypes.ts
- packages/core/src/waitFor.ts
I linted with `eslint-plugin-tsdoc` to identify cases where the JSDoc syntax used is not compatible with TSDoc. Found a couple cases and fixed them.
There is one remaining issue with `@param`, but I'm ignoring that for now. In JSDoc [`@param` can be name-only](https://jsdoc.app/tags-param.html#examples). But in TSDoc, `@param` is expected to always have a hyphen after the name (even if description is missing). We could avoid that linter warning by simply appending a hyphen after every `@param` name. But because it’s just a linter warning, and doesn’t make a difference to API Extractor, I didn’t bother.
> Switch from JSDoc to TSDoc

- packages/core/src/Mailbox.ts
This was needed when we were prepending `xstate.init` to the mailbox but currently, this is not quite an explicit mailbox event - but rather it's handled "out of band". I wonder if we could refine this but, for the time being, this code is redundant. Even if we manage to rethink this design I think it should be possible to just `enqueue` the `xstate.init` event immediately rather than having to "prepend" it.
> Remove unused `Mailbox#prepend`

- .changeset/honest-swans-complain.md
- packages/core/src/stateUtils.ts
- packages/core/test/state.test.ts
Perhaps this should become the actor's responsibility but currently each actor logic does this on its own.
> Update machine snapshots with the stopped status when the actor gets stopped

- .changeset/green-fishes-shave.md
- packages/core/src/actions/stop.ts
- packages/core/test/system.test.ts
fixes https://github.com/statelyai/xstate/issues/4364
> Unregister `systemId`s eagerly

- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
Companion PR for https://github.com/statelyai/docs/pull/237, which now uses `xstate` as a submodule, and requires these changes in order to build API docs.
This PR fixes issues that prevented the XState API docs index page from rendering properly, and fixes two warnings that occurred when API Documenter ran.
Includes and closes https://github.com/statelyai/xstate/pull/4374
> Fixes to support Generating API Documentation

- .changeset/five-queens-behave.md
- packages/core/src/StateMachine.ts
- packages/core/src/actions/assign.ts
- packages/core/src/actions/cancel.ts
- packages/core/src/actions/choose.ts
- packages/core/src/actions/log.ts
- packages/core/src/actions/pure.ts
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/actions/spawn.ts
- packages/core/src/actions/stop.ts
- packages/core/src/actors/transition.ts
- packages/core/src/interpreter.ts
- packages/core/src/spawn.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/actorLogic.test.ts
- packages/core/test/deterministic.test.ts
- packages/core/test/invoke.test.ts
- packages/core/test/microstep.test.ts
- packages/xstate-graph/src/actorScope.ts
- packages/xstate-graph/src/adjacency.ts
- packages/xstate-graph/src/graph.ts
- packages/xstate-graph/src/pathFromEvents.ts
- packages/xstate-graph/src/shortestPaths.ts
- packages/xstate-graph/src/simplePaths.ts
- packages/xstate-graph/test/graph.test.ts
Changed the actor context type from `ActorContext` to `ActorScope` to mitigate confusion.
> [v5] ActorContext -> ActorScope

- packages/core/test/history.test.ts
a test case based on https://github.com/statelyai/xstate/issues/3640
> Add a test case related to invokes and history states

- packages/xstate-react/src/createActorContext.ts
> [@xstate/react] Add deprecation notice for `machine` in Provider prop types

- .changeset/clever-jars-fly.md
- packages/core/src/interpreter.ts
- packages/core/src/system.ts
- packages/core/test/inspect.test.ts
All inspector events (snapshot, event, actor) now have a common `actorRef` property. This makes it easier to discern which inspection event is for which actor:
```ts
const actor = createActor(someMachine, {
inspect: (event) => {
// Was previously a type error
if (event.actorRef === actor) {
// This event is for the root actor
}
if (event.type === '@xstate.event') {
// previously event.targetRef
event.actorRef;
}
}
});
```
In the `'xstate.event'` event, the `actorRef` property is now the target actor (recipient of the event). Previously, this was the `event.targetRef` property (which is now removed).
> [v5] Consistent `actorRef` property for inspection events

- .changeset/flat-jokes-breathe.md
- packages/core/src/StateMachine.ts
- packages/core/src/actions/spawn.ts
- packages/core/src/actions/stop.ts
- packages/core/src/index.ts
- packages/core/src/interpreter.ts
- packages/core/src/spawn.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/errors.test.ts
- packages/core/test/interpreter.test.ts
- packages/xstate-react/src/useActor.ts
- packages/xstate-react/src/useActorRef.ts
- packages/xstate-solid/test/useMachine.test.tsx
I think that perhaps it would even be cool to move this to the mailbox. However, I bumped into small issues while trying to do so and I don't want to spend more time on this right now.
> Removed `Interpreter['status']` from publicly available properties

- .changeset/shy-poets-sleep.md
- packages/core/src/waitFor.ts
The default `timeout` for `waitFor(...)` is now `Infinity` instead of 10 seconds.
> [v5] Remove `waitFor` timeout

- packages/core/src/interpreter.ts
- packages/core/src/types.ts
> API Docs: ActorOptions

- packages/core/src/types.ts
While working on docs for "Custom actor logic" I felt it would be helpful to have the `ActorLogic` interface better documented.
Related to https://github.com/statelyai/docs/pull/252
> Add `ActorLogic` interface docs

- packages/xstate-vue/test/typegenTypes.test.tsx
In Vue , returning null from the setup function may lead to unexpected behavior, so it's best to follow the recommendation to return undefined. This change should resolve the warning message mentioned.
> setup function may lead to unexpected behavior

- packages/core/src/interpreter.ts
Adds documentation for createActor with two overloaded signatures.
Moved the most common signature (logic) to the top, so VS Code IntelliSense will suggest it first.
> API Docs: createActor

- .changeset/always-as-pure.md
- packages/core/src/stateUtils.ts
- packages/core/test/transient.test.ts
This essentially reverts https://github.com/statelyai/xstate/pull/2343 . I open this PR to spark the conversation about this behavior. It wasn't a change requested by any user - we just did it to comply with SCXML. However, this behavior "promotes" impurity and I really wonder if we want to keep this behavior.
> Do not select always transitions when no regular transition gets selected

- .changeset/always-as-pure.md
- packages/core/src/stateUtils.ts
- packages/core/test/transient.test.ts
This reverts commit 5da17f20db96c485e9c93bef5404302ffd2fd577.
We had a follow-up discussion about this offline and finally, we couldn't agree on what is better so we decided to revert this change for the time being.
> Revert "Do not select always transitions when no regular transition gets selected (#4449)"

- packages/core/src/interpreter.ts
- packages/core/test/typegenTypes.test.ts
- packages/xstate-vue/src/useActorRef.ts
fixes https://github.com/statelyai/xstate/pull/4416/files#r1407630794
Before the final release, we might consider removing all those `AreAllImplementationsAssumedToBeProvided` code paths. For the time being though this is kinda a bug so let's fix it and then bikeshed that removal.
> Merge `createActor` overloads into one

- .changeset/rotten-spoons-sleep.md
- packages/core/src/eventUtils.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/actor.test.ts
- packages/core/test/invoke.test.ts
The error event (`type: 'xstate.error.*'`) now has the error data on the `event.error` instead of `event.data`:
```diff
// ...
invoke: {
src: 'someSrc',
onError: {
actions: ({ event }) => {
-     event.data;
+     event.error;
}
}
}
```
> [v5] `event.data` -> `event.error` for error events

- .changeset/config.json
- .changeset/yellow-wasps-switch.md
- packages/xstate-solid/package.json
- packages/xstate-solid/src/createImmutable.ts
- packages/xstate-solid/test/useMachine.test.tsx
- Additional iteration on store array diffs to ensure middle value is checked
- Update package.json to match script and export pattern of other packages
Fixes #4369 & #3853
> [@xstate/solid] Fix full array replacement bug

- examples/todomvc-react/package.json
- examples/todomvc-react/pnpm-lock.yaml
- examples/todomvc-react/readme.md
- examples/todomvc-react/src/Todos.tsx
Hello,
I hope I'm not stepping out of line here but I had pulled down the `xstate` repo to help myself learn about the library in more detail and attempted to run `examples/todomvc-react` but found a few minor issues related to the v5 upgrade:
• Initially, running `pnpm run dev` resulted in the error:
```
[vite] Dep optimization failed with error:
'ActorStatus' is not exported by node_modules/.pnpm/xstate@5.2.1/node_modules/xstate/dist/xstate.esm.js, imported by node_modules/.pnpm/@xstate+react@4.0.0-beta.10_@types+react@17.0.59_react@17.0.2_xstate@5.2.1/node_modules/@xstate/react/dist/xstate-react.esm.js
```
Pinning `xstate-react` at `^4.0.0` rather than `beta` resolved this issue.
• On using the example app re-opening the page caused a failure due to the change in state persistence …
> Minor Fix to todomvc-react Example Project

- .changeset/strong-jobs-unite.md
- packages/core/src/actions/enqueueActions.ts
- packages/core/test/actions.test.ts
Updates the argument object of `enqueueActions(...)` to include a `self` property:
```ts
// ...
entry: enqueueActions(({ self }) => {
// ...
});
```
> [core] Add `self` and `system` to `enqueueActions(...)`

- .github/actions/ci-setup/action.yml
Node 16 is EOL: https://nodejs.org/en/blog/announcements/nodejs16-eol
Bump github-actions CI to NodeJS v20.
Using Node 16 will block (future) dependency updates: https://github.com/statelyai/xstate/pull/3637
cc: @davidkpiano
> ci(github-actions): bump node to v20

- packages/xstate-react/README.md
Resource `https://unpkg.com/@xstate/react/dist/xstate-react.umd.min.js` no longer exists so added a valid link to the `README.md`
> Update xstate-react.umd.min.js url to valid link

- .changeset/tender-rocks-lay.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
fixes https://discord.com/channels/795785288994652170/1190416887063007263/1190416887063007263
> Allow `event` in transitions to be narrowed down even when its `.type` is defined using a union

- .changeset/brave-llamas-hammer.md
- packages/core/src/StateMachine.ts
- packages/core/src/stateUtils.ts
- packages/core/src/utils.ts
- packages/core/test/id.test.ts
State IDs that have periods in them are now supported if those periods are escaped.
The motivation is that external tools, such as [Stately Studio](https://stately.ai/studio), may allow users to enter any text into the state ID field. This change allows those tools to escape periods in state IDs, so that they don't conflict with the internal path-based state IDs.
E.g. if a state ID of `"Loading..."` is entered into the state ID field, instead of crashing either the external tool and/or the XState state machine, it should be converted by the tool to `"Loading\\.\\.\\."`, and those periods will be ignored by XState.
---
Quick demo of the problem in Stately Studio:
https://github.com/statelyai/xstate/assets/1093738/3da093ac-fdb0-4534-a12b-1534b86b6112
The solution would be to escape the …
> Allow escaped periods in state IDs

- .codesandbox/ci.json
Node 16 is EOL: https://nodejs.org/en/blog/announcements/nodejs16-eol
Bump codesandbox CI to NodeJS v20.
Follow up of: https://github.com/statelyai/xstate/pull/4579
Blocking: https://github.com/statelyai/xstate/pull/3637
https://ci.codesandbox.io/status/statelyai/xstate/pr/3637/builds/455896
```shell
error lint-staged@15.2.0: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "16.18.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process rejected with status code 1
at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
at ChildProcess.emit (node:events:517:28)
at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
code: 1
}
```
c: @davidkpiano
> Use node 18 on CodeSandbox CI

- .changeset/honest-spoons-drum.md
- packages/xstate-react/src/createActorContext.ts
- packages/xstate-react/test/createActorContext.test.tsx
Options in `createActorContext` are now properly merged with provider options. Previously, provider options replaced the actor options.
```tsx
const { inspect } = createBrowserInspector();
const SomeContext = createActorContext(someMachine, { inspect });
// ...
// Options are now merged:
// { inspect: inspect, input: 10 }
<SomeContext.Provider options={{ input: 10 }}>
{/* ... */}
</SomeContext.Provider>;
```
> Merge `createActorContext` options with Provider options

- .changeset/lucky-mice-lick.md
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
fixes https://github.com/statelyai/xstate/issues/4662
> Fixed compatibility with the upcoming TS 5.4

- .changeset/slow-swans-punch.md
- packages/core/src/types.ts
closes https://github.com/statelyai/xstate/issues/4711
> Expose InteropObservable and InteropSubscribable

- .changeset/fifty-beds-love.md
- packages/core/src/State.ts
- packages/core/test/types.test.ts
Resolves https://github.com/statelyai/xstate/issues/4734. I tested locally using the same scenario as used in the issue and the types behaved as expected. I couldn't really figure out a way to programmatically prove work and test the types directly. Please advise if there is something you'd like to see there.
> #4734 bugfix: removed `this` from snapshot methods

- .changeset/khaki-toes-wait.md
- packages/core/src/actions/assign.ts
- packages/core/src/actions/enqueueActions.ts
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/actions/spawnChild.ts
- packages/core/src/setup.ts
- packages/core/test/setup.types.test.ts
- packages/core/test/types.test.ts
- packages/xstate-react/test/createActorContext.test.tsx
- packages/xstate-test/test/dieHard.test.ts
- tsconfig.json
fixes https://github.com/statelyai/xstate/issues/4743
fixes https://github.com/statelyai/xstate/issues/4545
> Forbid unknown implementations from being used

- .changeset/nasty-foxes-move.md
- packages/core/src/StateMachine.ts
- packages/core/src/stateUtils.ts
- packages/core/test/final.test.ts
fixes https://github.com/statelyai/xstate/issues/4762
> Correctly use falsy outputs

- .changeset/healthy-camels-report.md
- packages/core/src/actions/enqueueActions.ts
- packages/core/src/actions/send.ts
- packages/core/test/setup.types.test.ts
fixes https://github.com/statelyai/xstate/discussions/4770 (a regression of sorts from https://github.com/statelyai/xstate/pull/4750 )
> Fixed a type issue that prevent `sendParent` to be accepted by `setup` when `delays` stayed not configured

- .changeset/tall-actors-call.md
- package.json
- packages/core/src/StateMachine.ts
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/guards.ts
- packages/core/src/types.ts
- yarn.lock
This PR updates the TypeScript version in the XState monorepo to 5.4, which includes replacing `NoInfer` with the native `NoInfer` (doesn't work yet)
> TypeScript 5.4

- .changeset/metal-elephants-impress.md
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/StateNode.ts
- packages/core/src/createMachine.ts
- packages/core/src/setup.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/src/utils.ts
- packages/core/test/setup.types.test.ts
- packages/core/test/typegenTypes.test.ts
- packages/core/test/types.test.ts
- packages/xstate-test/src/machine.ts
- packages/xstate-test/src/types.ts
Meta objects for state nodes and transitions can now be specified in `setup({ types: … })`:
```ts
const machine = setup({
types: {
meta: {} as {
layout: string;
}
}
}).createMachine({
initial: 'home',
states: {
home: {
meta: {
layout: 'full' // strongly typed
}
}
}
});
const actor = createActor(machine).start();
actor.getSnapshot().getMeta().home!;
// typed as { layout: string }
```
Fixes #809
> [core] Add `meta` types

- .changeset/twenty-parrots-add.md
- jest.config.js
- packages/core/src/actions/assign.ts
- packages/core/src/actions/emit.ts
- packages/core/src/actions/raise.ts
- packages/core/src/actions/send.ts
- packages/core/src/actions/spawnChild.ts
- packages/core/src/stateUtils.ts
- packages/core/test/actions.test.ts
This PR warns for improper imperative calls of built-in actions, which is a very common problem.
https://stately.ai/docs/actions#built-in-actions
> [core] Add warning for imperative built-in action calls

- examples/express-workflow/index.ts
Added content-type to curl call so that the examples work as intended. 
without it, example server crashed
> Express workflow fix: Add Content Type to curl call

- .changeset/nice-spiders-perform.md
- packages/xstate-store/src/store.ts
- packages/xstate-store/test/store.test.ts
The `context` type for `createStoreWithProducer(producer, context, transitions)` will now be properly inferred.
```ts
const store = createStoreWithProducer(
produce,
{
count: 0
},
{
// ...
}
);
store.getSnapshot().context;
// BEFORE: StoreContext
// NOW: { count: number }
```
> [@xstate/store] Fix `createStoreWithProducer(…)` types

- .changeset/big-ghosts-develop.md
- packages/core/src/createActor.ts
- packages/core/src/types.ts
- packages/core/test/emit.test.ts
You can now use a wildcard to listen for _any_ emitted event from an actor:
```ts
actor.on('*', (emitted) => {
console.log(emitted); // Any emitted event
});
```
> [core] Wildcard emitted event listener

- .changeset/nervous-chicken-eat.md
- packages/core/src/actors/index.ts
- packages/core/src/createActor.ts
- packages/core/src/types.ts
- packages/core/test/emit.test.ts
- packages/core/test/types.test.ts
- packages/xstate-solid/src/fromActorRef.ts
> [core] Fix type issues with emitted events

- .changeset/cold-planes-clap.md
- packages/core/src/system.ts
- packages/core/test/inspect.test.ts
Inspecting an actor system via `actor.system.inspect(ev => …)` now accepts a function or observer, and returns a subscription:
```ts
const actor = createActor(someMachine);
const sub = actor.system.inspect((inspectionEvent) => {
console.log(inspectionEvent);
});
// Inspection events will be logged
actor.start();
actor.send({ type: 'anEvent' });
// ...
sub.unsubscribe();
// Will no longer log inspection events
actor.send({ type: 'someEvent' });
```
> [core] Inspect subscription

- .changeset/giant-bananas-drive.md
- packages/core/src/eventUtils.ts
- packages/core/src/types.ts
- packages/core/test/inspect.test.ts
- packages/core/test/invoke.test.ts
This changes `DoneActorEvent` (`xstate.done.actor.*`) and `ErrorActorEvent` (`xstate.error.actor.*`) to have an `actorId` prop which is equal to the ID of the Actor associated with the event.
Previously, this information was only available by extracting it from the `type` property of the event object using string operations.
* * *
Updated a test for `DoneActorEvent` to prove that `actorId` gets passed, but may want the same test for an `ErrorActorEvent`.
Ref: https://discord.com/channels/795785288994652170/1250894522616123494
> feat(core): add actor ID to DoneActorEvent, ErrorActorEvent

- .changeset/strange-fireants-tap.md
- packages/core/src/types.ts
- packages/core/test/types.test.ts
`AnyActorRef` is problematic for some use cases, because the result of the `AnyActorRef['getSnapshot']` function is of type `any`.
However, changing `AnyActorRef` to use a narrow type in `ActorRef`'s first type argument, `TSnapshot`, breaks conditional types which perform inference based on `TSnapshot`.
This change introduces `UnknownActorRef`, which is like `AnyActorRef`, but is not intended to be inferred from in future conditional types. A consumer can use `UnknownActorRef` like so:
```ts
const actor: UnknownActorRef = getSomeActor();
// inferred as `Snapshot<unknown>`
const snapshot = actor.getSnapshot();
// do things w/ snapshot
```
`AnyActorRef` would return `any` from `actor.getSnapshot()`, which make it unsuitable for this use-case in a strictly-typed environment.
> feat(core): expose UnknownActorRef

- .changeset/smooth-crabs-dress.md
- packages/core/src/actors/callback.ts
- packages/core/src/actors/observable.ts
- packages/core/src/actors/promise.ts
- packages/core/src/actors/transition.ts
- packages/core/test/emit.test.ts
This PR adds support for emitting events from all actor logic types:
**Promise actors**
```ts
const logic = fromPromise(async ({ emit }) => {
// ...
emit({
type: 'emitted',
msg: 'hello'
});
// ...
});
```
**Transition actors**
```ts
const logic = fromTransition((state, event, { emit }) => {
// ...
emit({
type: 'emitted',
msg: 'hello'
});
// ...
return state;
}, {});
```
**Observable actors**
```ts
const logic = fromObservable(({ emit }) => {
// ...
emit({
type: 'emitted',
msg: 'hello'
});
// ...
});
```
**Callback actors**
```ts
const logic = fromCallback(({ emit }) => {
// ...
emit({
type: 'emitted',
msg: 'hello'
});
// ...
});
```
> [core] Add emit support for all actor logic creators

- .github/ISSUE_TEMPLATE/config.yml
This PR updates this repo's issue template config:
- update `url` for Feature Request/Ask a Question to point to the corresponding discussions category
- update `about` text for Feature Request/Ask a Question
- add entry for Documentation linking to new issue page of the `statelyai/docs` repo
- add entry for Stately Studio linking to the issue page of the `statelyai/studio-issues` repo
Here's what the updated new issue page will look like:
> update issue template config

- .changeset/mighty-guests-hunt.md
- packages/core/src/actors/callback.ts
- packages/core/src/actors/index.ts
- packages/core/src/actors/observable.ts
- packages/core/src/actors/promise.ts
- packages/core/src/actors/transition.ts
This PR exports actor logic-specific `ActorRef` types. Noticed in #4974 that these weren't actually exported.
In addition to exporting them, I added a `jsdoc` comment block for each.
Also fixed a small issue where the `jsdoc` block for `fromPromise` was attached to a variable defined before `fromPromise` rather than `fromPromise` itself.
> export actor logic-specific ActorRef types

- packages/core/src/index.ts
Fixes the warning that we got during builds etc:
```
The exported identifier "Interpreter" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.
This problem is likely caused by another plugin injecting
"Interpreter" without registering it in the scope tracker. If you are the author
of that plugin, please use "scope.registerDeclaration(declarationPath)".
```
> Fixed annoying Babel warning

- .changeset/nervous-snails-help.md
- packages/core/src/actions/enqueueActions.ts
- packages/core/test/actions.test.ts
Added `sendParent` to the `enqueueActions` feature. This allows users to enqueue actions that send events to the parent actor within the `enqueueActions` block.
```js
import { createMachine, enqueueActions } from 'xstate';
const childMachine = createMachine({
entry: enqueueActions(({ enqueue }) => {
enqueue.sendParent({ type: 'CHILD_READY' });
})
});
```
> [core] Add `enqueue.sendParent(…)`

- .changeset/famous-crabs-build.md
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/types.ts
This PR exports a new `SnapshotStatus` type which represents the `status` type of an actor snapshot— `'active' | 'done' | 'error' | 'stopped'`.
Hardcoded uses of this string union were also replaced with the type.
[Discussion](https://discord.com/channels/795785288994652170/989186412450553957/1266027308201021491)
> [core] Expose actor snapshot `status` type as SnapshotStatus

- package.json
- yarn.lock
This PR upgrades `@types/node` to `^20.14.13`. This matches the latest LTS version specified in `.node-version`.
> upgrade @types/node to ^20.14.13

- .changeset/lucky-horses-pay.md
- packages/core/src/system.ts
- packages/core/test/actions.test.ts
- packages/core/test/after.test.ts
Fix an issue where `clearTimeout(undefined)` was sometimes being called, which can cause errors for some clock implementations. See https://github.com/statelyai/xstate/issues/5001 for details.
> [core] Do not clear undefined timer IDs

- .changeset/cold-suits-build.md
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/StateNode.ts
- packages/core/src/createMachine.ts
- packages/core/src/stateUtils.ts
- packages/core/src/types.ts
- packages/core/test/types.test.ts
- packages/xstate-graph/src/TestModel.ts
- packages/xstate-graph/src/types.ts
- packages/xstate-graph/test/index.test.ts
- packages/xstate-react/test/types.test.tsx
The internal types for `StateMachine<...>` have been improved so that all type params are required, to prevent errors when using the types. This fixes weird issues like #5008.
> [core] Tighten `StateMachine` types and fix issue #5008

- .changeset/slimy-gifts-boil.md
- packages/xstate-store/src/types.ts
This PR adds the `EventFromStore` utility type to `@xstate/store`. `EventFromStore` allows us to extract the type of events from a given store:
```ts
import { createStore, type EventFromStore } from '@xstate/store';
const store = createStore(
{ count: 0 },
{
add: (context, event: { addend: number }) => ({
count: context.count + event.addend
}),
multiply: (context, event: { multiplier: number }) => ({
count: context.count * event.multiplier
})
}
);
type StoreEvent = EventFromStore<typeof store>;
//   ^? { type: 'add'; addend: number } | { type: 'multiply'; multiplier: number }
```
This idea came about thanks to @qiushiyan in #5017.
> add `EventFromStore` utility type to `@xstate/store`

- .changeset/sweet-tools-compare.md
- packages/core/src/inspection.ts
- packages/core/src/types.ts
- packages/xstate-store/src/store.ts
- packages/xstate-store/src/types.ts
- packages/xstate-store/test/store.test.ts
You can now inspect XState stores using the `.inspect(inspector)` method:
```ts
import { someStore } from './someStore';
someStore.inspect((inspEv) => {
console.log(inspEv);
// logs "@xstate.event" events and "@xstate.snapshot" events
// whenever an event is sent to the store
});
// The "@xstate.actor" event is immediately logged
```
> [@xstate/store] Add `store.inspect(…)`

- .changeset/empty-seas-live.md
- packages/core/src/actions/emit.ts
- packages/core/test/setup.types.test.ts
fixes https://github.com/statelyai/xstate/issues/5038
> Fixed an inference issue that prevented `emit` used directly in `setup` (or bare `createMachine`) to benefit from `types.emitted` types

- .changeset/pretty-chicken-lie.md
- packages/core/src/waitFor.ts
- packages/core/test/waitFor.test.ts
This PR adds a `signal?: AbortSignal` option to `WaitForOptions`, so that a call to `waitFor()` can be externally aborted.
> feat(core): add signal option to waitFor

- .changeset/mean-news-sell.md
- packages/core/src/actors/callback.ts
- packages/core/src/actors/index.ts
The `CallbackLogicFunction` type (previously `InvokeCallback`) is now exported. This is the callback function that you pass into `fromCallback(callbackActorFn)` to create an actor from a callback function.
```ts
import { type CallbackLogicFunction } from 'xstate';
// ...
```
> [core] Export `CallbackLogicFunction` (prev. `InvokeCallback`)

- .changeset/mean-peaches-decide.md
- babel.config.js
- packages/xstate-store/README.md
- packages/xstate-store/package.json
- packages/xstate-store/solid/package.json
- packages/xstate-store/src/solid.ts
- packages/xstate-store/test/solid.test.tsx
I've added `useSelector` support to xstate/store for SolidJS which seems to be working well in my tests. Let me know what I can improve and I'd be happy to do it.
> Add initial support for xstate/store/solid

- .github/actions/ci-setup/action.yml
This PR should hopefully fix the `ENEEDAUTH` error we're receiving in actions. 
According to https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry:
> Please note that you need to set the `registry-url` to https://registry.npmjs.org/ in `setup-node` to properly configure your credentials.
> add `registry-url` to `actions/setup-node`

- .changeset/long-ravens-yell.md
- packages/xstate-svelte/package.json
Svelte 5 is "almost" entirely backwards compatible with svelte 4. Breaking changes can be found [here](https://svelte.dev/docs/svelte/v5-migration-guide#Breaking-changes-in-runes-mode). 
`@xstate/svelte` only uses `onDestroy`, `readable`, and `Readable` from svelte, which are backwards compatible.
> Add Svelte 5 to the allowed peer dependency range

- .changeset/big-pumas-search.md
- packages/core/src/spawn.ts
- packages/core/src/types.ts
- packages/core/test/spawn.test.ts
- packages/core/test/spawn.types.test.ts
Similar to #5055, this PR makes `input` required when using `spawn` and the `input` type  in the referenced actor is defined.
This prevents issues when forgetting to pass an input when using `spawn` (causing runtime errors).
```ts
const childMachine = createMachine({
types: { input: {} as { value: number } }
});
types: {} as { context: { ref: ActorRefFrom<typeof childMachine> } },
context: ({ spawn }) => ({
ref: spawn(
childMachine,
// Input is now required!
{ input: { value: 42 } }
)
})
});
```
> Required input for `spawn` when defined inside referenced actor

- .changeset/soft-apples-smoke.md
- packages/core/src/types.ts
fixes https://github.com/statelyai/xstate/issues/4613
> Improved compatibility of inferred types in projects with `exactOptionalPropertyTypes` enabled

- .changeset/modern-scissors-bow.md
- .changeset/serious-onions-call.md
- .changeset/two-laws-smoke.md
- packages/xstate-store/src/index.ts
- packages/xstate-store/src/react.ts
- packages/xstate-store/src/store.ts
- packages/xstate-store/src/types.ts
- packages/xstate-store/test/react.test.tsx
- packages/xstate-store/test/store.test.ts
There is now a `useStore()` hook that allows you to create a local component store from a config object.
```tsx
import { useStore, useSelector } from '@xstate/store/react';
function Counter() {
const store = useStore({
context: {
name: 'David',
count: 0
},
on: {
inc: (ctx, { by }: { by: number }) => ({
...ctx,
count: ctx.count + by
})
}
});
const count = useSelector(store, (state) => state.count);
return (
<div>
<div>Count: {count}</div>
<button onClick={() => store.trigger.inc({ by: 1 })}>
Increment by 1
</button>
<button onClick={() => store.trigger.inc({ by: 5 })}>
Increment by 5
</button>
</div>
);
}
```
---
Added `createStoreConfig` to create a store config from an object. This is an identity function that returns the config unchanged, but is useful for type inference.
```tsx
const …
```
> [@xstate/store] `useStore()` and other improvements

- .changeset/wild-shoes-eat.md
- packages/xstate-store/src/types.ts
- packages/xstate-store/test/store.test.ts
The types for emitting events with no payload have been fixed so that the following code works:
```ts
const store = createStore({
emits: {
incremented: () => {}
},
on: {
inc: (ctx, ev, enq) => {
// No payload is expected
enq.emit.incremented();
}
}
});
```
Previously, this would have been an error because the `incremented` event was expected to have a payload.
> [xstate/store] Fix types for emitting with no payload

- .changeset/rude-keys-grab.md
- packages/core/src/State.ts
- packages/core/src/StateMachine.ts
- packages/core/src/types.ts
- packages/core/test/history.test.ts
This is a fix for issue here: https://github.com/statelyai/xstate/issues/5178
featuring new helper functions to restore _StateNode class instances deeply.
> [core]: bugfix restoring historyValue | feature reviveHistoryValue

- eslint.config.mjs
- package.json
- packages/core/src/createActor.ts
- packages/core/src/types.ts
- pnpm-lock.yaml
This makes those references clickable in the IDE and they now correctly auto-link in the tooltips.
> Fixed JSDoc `@link` references

- .changeset/fresh-mails-shake.md
- packages/xstate-store/src/react.ts
- packages/xstate-store/src/types.ts
- packages/xstate-store/test/react.test.tsx
- packages/xstate-store/vitest.config.mts
This PR adds the `useAtom` hook for reading the value of an atom or selecting a value from the atom.
It is meant for the common use-case where the entire value of the atom (usually granular data) is needed.
```tsx
const atom = createAtom(0);
const Component = () => {
const count = useAtom(atom);
return (
<>
<div onClick={() => atom.set((c) => c + 1)}>{count}</div>
<button onClick={() => atom.set(0)}>Reset</button>
</>
);
};
```
With selectors:
```tsx
const atom = createAtom({ count: 0 });
const Component = () => {
const count = useAtom(atom, (s) => s.count);
return <div>{count}</div>;
};
```
> [@xstate/store] Add `useAtom(atom)` + fix vitest config

- .changeset/fine-apes-switch.md
- packages/xstate-store/src/react.ts
- packages/xstate-store/test/react.test.tsx
This PR fixes the types for `useAtom` to accept `ReadonlyAtom` values.
Fixes #5306
> [@xstate/store] Fix `useAtom` to accept `ReadonlyAtom`

- .changeset/dirty-donuts-clean.md
- packages/xstate-store/src/atom.ts
- packages/xstate-store/test/atom.test.ts
Fix: `createAsyncAtom` now properly propagates status updates after promise resolves/rejects.
Fixes #5327
> [@xstate/store] Fix `createAsyncAtom` propagation

- .changeset/full-signs-give.md
- packages/xstate-store/src/store.ts
- packages/xstate-store/src/types.ts
- packages/xstate-store/test/store.test.ts
The `createStore` function now supports explicit generic type parameters for better type control when needed. This allows you to specify the exact types for context, events, and emitted events instead of relying solely on type inference if desired.
```ts
type CoffeeContext = {
beans: number;
cups: number;
};
type CoffeeEvents = { type: 'addBeans'; amount: number } | { type: 'brewCup' };
type CoffeeEmitted =
| { type: 'beansAdded'; amount: number }
| { type: 'cupBrewed' };
const coffeeStore = createStore<CoffeeContext, CoffeeEvents, CoffeeEmitted>({
context: {
beans: 0,
cups: 0
},
on: {
addBeans: (ctx, event, enq) => {
enq.emit.beansAdded({ amount: event.amount });
return { ...ctx, beans: ctx.beans + event.amount };
},
brewCup: (ctx, _, enq) => {
if (ctx.beans > 0) {
enq.emit.cupBrewed(); …
```
> [@xstate/store] Add support for generics 

- .changeset/selfish-readers-sniff.md
- packages/xstate-store/src/index.ts
need these types in our repo 🙇🏽
https://github.com/statelyai/xstate/pull/5334
would be great too!
> [@xstate/store]  chore: add missing EventFromStoreConfig, EmitsFromStoreConfig, ContextFromStoreConfig types

- .changeset/twenty-bars-relate.md
- packages/xstate-store/src/react.ts
- packages/xstate-store/test/react.test.tsx
From #5298
Add `createStoreHook(…)` function for React. Creates a store hook that returns `[selectedValue, store]` instead of managing store instances manually.
```tsx
const useCountStore = createStoreHook({
context: { count: 0 },
on: {
inc: (ctx, event: { by: number }) => ({
...ctx,
count: ctx.count + event.by
})
}
});
// Usage
const [count, store] = useCountStore((s) => s.context.count);
store.trigger.inc({ by: 3 });
// Usage (no selector)
const [snapshot, store] = useCountStore();
```
> [@xstate/store] React `createStoreHook(…)` helper

- .changeset/kind-regions-mate.md
- packages/xstate-store/src/store.ts
- packages/xstate-store/test/react.test.tsx
- Fix: `trigger` methods now work when passed directly as event handlers, even for events with no payload. Before, the React `event.type` would overwrite the intended event type.
> [@xstate/store] Fix event type overwriting

- .changeset/nice-teeth-lead.md
- packages/core/src/system.ts
- packages/core/test/system.test.ts
This PR adds `system.getAll` that returns a record of running actors within the system by their system id.
This is very helpful for a tool to visualize active actors in a system given the system reference.
> Get list of currently running actors in system
